### PR TITLE
Change OpenXR loader documentation to refer to new asset library entry

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR changes the OpenXR android deployment documentation to include info about the new asset library entry and refer to the additional loaders we added.

### CODE REVIEW

**Review by skyace65 — CHANGES_REQUESTED** [review]
The content of this PR looks good. However the images look overly compressed, I can see compression artifacts in them.

**Comment by BastiaanOlij** [comment]
Just compressed with default webp settings for krita... :(

**Comment by skyace65** [comment]
That's weird, Krita doesn't give artifacts for me. I'll see if I can figure out what's going on.

**Comment by skyace65** [comment]
I took a look at this with Krita on my computer. I'm only getting compression artifacts if "lossless" is unchecked when saving, and it's turned on by default for me. If it's not that on your end I'm not sure what's going on

I made my own copy of those images to test this. Feel free to use them if you want
[XRImages.zip](https://github.com/godotengine/godot-docs/files/11217132/XRImages.zip)

**Review by mhilbrunner — APPROVED** [review]
Pushed to use the new images provided by skyace65 above.
Otherwise looks good to me.

**Comment by mhilbrunner** [comment]
Thank you! Merged.

**Comment by mhilbrunner** [comment]
Pushed to `4.0` and `stable`.

**Pull request merged**
