### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by MrOrangeTan**
Fixed the issue on line 35. The issue being the perfect opportunity for a pun not taken.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by AThousandShips** [comment]
You will also have to rebase your PR on master, with `git rebase -i master`, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by Calinou** [comment]
I don't think we should use this pun, as it won't translate well to other languages. In its original meaning, "Git" is an insult after all.

Also, the `master` branch should remain called the `master` branch to match the GitHub repository.

**Comment by YuriSizov** [comment]
So thanks for lightening the mood, but we are going to reject this ;)

**Pull request closed without merging**
