### PR TITLE
Remove duplicate reminders that are very close to each other

### PR DESCRIPTION
**Pull request by hidalgob**
Was reading through the tutorial and saw this information popping up at least 3 times. There's another reminder a couple lines below saying the same thing. So I'm proposing to remove this one.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [PR Workflow - Updating your branch](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch).

**Comment by AThousandShips** [comment]
Updated your branch

**Comment by skyace65** [comment]
Important information. We added the other note on this page recently knowing it was a duplicate, and the author of that PR missed this note when they read it. I'm in favor of removing it because this seems like excessive repetition to me, and if people don't fully read the page that's on them. Though I do remember we made an exception for something else because people kept reporting an issue.

@mhilbrunner @cbscribe you guys approved the PR that added the second note. Any change in opinion or do you still want two notes?

**Comment by Piralein** [comment]
#8213 is doing the same change.

**Comment by skyace65** [comment]
@Piralein I'd be in favor of removing both notes and adding a warning as you suggested in #8213.

**Comment by mhilbrunner** [comment]
> I'd be in favor of removing both notes and adding a warning as you suggested in #8213.

I'm fine with this too. :)

**Comment by mhilbrunner** [comment]
Thanks for contributing! I've merged https://github.com/godotengine/godot-docs/pull/8437, which aims to fix this and supersedes this PR. Thanks for bringing this to our attention and taking the time to contribute :)

**Pull request closed without merging**
