### PR TITLE
Document how to compare floats properly in Shading language

### LINKED ISSUE #4342: Shading reference should warn about comparing floats
Hi, I made an animated sprite character and made an override material that replaces a single color on the shirt of my sprite.

However It works for one sprite, but when I make an animation at the animationplayer using the sprites, they look like no shader has changed them.

### PR DESCRIPTION
**Pull request by Calinou**
This closes #4342.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Maybe we should like to this as well https://floating-point-gui.de/

**Comment by NathanLovato** [comment]
Good, but I'd recommend splitting the code example and moving comments out of it; that's because at the moment, they're not translatable and won't be available to users internationally. At least, that's unless you or someone else is planning to tackle #4211 soon-ish.

**Comment by NathanLovato** [comment]
If you're okay with the idea of turning comments into paragraphs so they can be translated, may I go ahead, make the edits, and merge?

**Comment by clayjohn** [comment]
@Calinou ping. 

For the record, I agree with @NathanLovato

**Comment by Calinou** [comment]
@NathanLovato Sure, feel free to do it. Apologies for the late reply.

**Comment by NathanLovato** [comment]
Done, thanks!

**Pull request merged**
