### PR TITLE
Make it easier to build pages for Windows users

### PR DESCRIPTION
**Pull request by Xrayez**
Added a batch script to simplify the process of building html pages on
Windows platform. The script was auto-generated by Sphinx.

Allows typing `make html` directly from the command line just like in Linux.

~~Created .gitattributes for the *.bat files to be commited with CRLF in~~
~~order to prevent possible incorrect interpretation.~~

### CODE REVIEW

**Comment by akien-mga** [comment]
> Created .gitattributes for the *.bat files to be commited with CRLF in
order to prevent possible incorrect interpretation.

Is this really needed? AFAIK Git on Windows is configured by default to autoconvert to CRLF, and I'd prefer not to enforce CRLF files on non-Windows (since Linux and macOS Git are not configured to modify the EOL by default AFAIR).

**Comment by Xrayez** [comment]
> Git on Windows is configured by default to autoconvert to CRLF

What about those who configured Git on Windows to autoconvert to LF by default instead?

Either way, I checked out the `make.bat` file with LF and it doesn't seem to break anything compared to CRLF, not to mention that there might be additional issues on Linux and macOS Git that I wasn't aware of. Should I remove `.gitattributes` then?

**Comment by akien-mga** [comment]
> Either way, I checked out the make.bat file with LF and it doesn't seem to break anything compared to CRLF, not to mention that there might be additional issues on Linux and macOS Git that I wasn't aware of. Should I remove .gitattributes then?

If it still works fine as LF on Windows for those who considered their Git this way, I'd prefer we remove the .gitattributes yeah. No exceptions unless really needed.

**Comment by Xrayez** [comment]
Yep, reasonable enough, updated.

**Pull request merged**
