### PR TITLE
multiple_resolutions.rst: Remove confusing stretch.png graphic

### PR DESCRIPTION
**Pull request by jpaugh**
Remove confusing stretch.png graphic, which does not correspond to the available 4.x stretch modes, nor is it referred to by any of the surrounding text. In fact, the actual stretch modes behave quite differently than what this graphic implies.

### CODE REVIEW

**Comment by Sauermann** [comment]
I agree, that this picture doesn't help to describe to different stretch modes.
When removing the link to the picture, you should probably also delete the picture `img/stretch.png` itself.
It doesn't seem to be used anywhere else.

**Comment by jpaugh** [comment]
> you should probably also delete the picture img/stretch.png itself.

@Sauermann Good idea, thanks! I have deleted that image, although I left the corresponding SVG in place. Perhaps someone will want to edit that into a usable image, later. It seems like it corresponds to 3.x stuff, maybe?

**Comment by Calinou** [comment]
I'd remove both the SVG and PNG and the image will have to be redone from scratch to be more descriptive anyway.

**Comment by mhilbrunner** [comment]
Thanks for contributing! This has been superseded by https://github.com/godotengine/godot-docs/pull/9049.

**Pull request closed without merging**
