### PR TITLE
Fixed the GridMap issue in the Godot FPS Tutorial

### LINKED ISSUE #3151: FPS tutorial maps broken in 3.2
Works in 3.1.2-stable
Broken in 3.2-stable

FPS tutorial at https://docs.godotengine.org/en/3.2/tutorials/3d/fps_tutorial/part_three.html
When launching the scenes for the included levels the character falls through the floor.
The instruction that fails "Space_Level.tscn and Ruins_Level.tscn are complete custom FPS levels created for the purpose of this tutorial. Press F6 to play the open scene, or press the play current scene button, and give each a try."

Editor complains on load that the project is from a old version and upgrades it. Turns out the zip files are two years old.

There are some errors when switching to the scene (in both 3.1.2-stable and 3.2-stable):
 core/math/quick_hull.cpp:401 - Condition "O == E" is true. Continuing.
 core/math/quick_hull.cpp:401 - Condition "O == E" is true. Continuing.

An repeating error in the error log when launching Ruins_level.tscn:
E 0:00:02.308   recover_from_penetration: Condition "shape_idx < 0 || shape_idx >= cs->getNumChildShapes()" is true. Returned: false
  <C++ Source>  modules/bullet/space_bullet.cpp:1241 @ recover_from_penetration()
  <Stack Trace> Player.gd:221 @ process_movement()
                Player.gd:71 @ _physics_process()

The scene switching errors exits in 3.1.2-stable, but the recover_from_penetration is not there, and it seems to work.

Do not have a clue on how to fix this as I only just started with godotengine.

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
The GridMaps should now work with Godot 3.2, making the tutorial doable. I didn't look at the collision shape issues, but I think it is a quick hull issue. If it is, I'm not sure on a great way to fix it without redoing all of the collision shapes.
Closes #3151

### CODE REVIEW

**Comment by aaronfranke** [comment]
Since these are binary files, if we are changing them, we should probably fix many things at once. Some notes when I tried out the "Finished" version:

* Tons of unused argument and return value warnings which should be silenced. For example, change `delta` to `_delta`, and add `# warning-ignore:return_value_discarded`.

* The scripts are mostly complaint with the GDScript style guide, but not everywhere. I noticed that arguments with default values are missing spaces around `=`, some method calls have spaces `print (`, `Debug_Display.gd` should have two lines between `_ready` and `_process`, and `Globals.gd` shouldn't have extra newlines at the end of the file (it should have just one). There may be more style violations that I'm not seeing right now.

* The project files are not organized at all, every script and scene is stored in the project root. It would be much better if the files were organized.

* While we don't currently have a solid guide for [project organization](https://github.com/godotengine/godot-docs/issues/3104), one item of consensus so far has been to use `PascalCase` for nodes. This means no underscores in node names (which the FPS tutorial uses everywhere).

* There is no tutorial level, tutorial menu, or controls menu. While I know that this is itself a tutorial that shows users how to build it step-by-step and therefore they would know everything anyway, some users may skip straight to the final version to see what they're building before they build it, and it would also be good practice to encourage game devs to add a tutorial/help system.

**Comment by akien-mga** [comment]
As I mentioned when those archives were first added, I still think it's a bad idea to have ZIP files for project code in this repo. It makes the Git repo bigger (every update increases the size of the repo by the size of the updated ZIP), and it's difficult to keep in sync with the ever changing docs and Godot API.

I believe this should be moved to a dedicated Git repo, which can then be referenced from the docs and downloaded from tagged versions matching the Godot API using the auto-generated GitHub ZIP archives.

**Comment by TwistedTwigleg** [comment]
That is fair. I’m fine with moving the project to a dedicated Git repo. Right now I have it stored [here](https://github.com/TwistedTwigleg/Godot_FPS_Tutorial), though it is a little out of date and would need to be tagged according to Godot versions. We could link to that repo, or we can make a new, official repository for it.

I think that if we link to a dedicated repository, we should limit the downloads to the starter assets and final project, as maintaining the additional 4+ zip files is cumbersome, time consuming, and I’m not sure it is benefiting anyone.

**Comment by mhilbrunner** [comment]
Note: this depends a little on how/if we move forward with https://github.com/godotengine/godot-docs/issues/3390

**Comment by aaronfranke** [comment]
Perhaps the project should be moved to the demo projects repo?

Also, how feasible is it to maintain 6 different versions of the same project? It might make sense to only have starter assets and the final version.

**Comment by TwistedTwigleg** [comment]
Yeah. I’ve glanced through the issue a few times, and it seems the general consensus is to remove tutorials like the FPS tutorial.

> how feasible is it to maintain 6 different versions of the same project? It might make sense to only have starter assets and the final version

I agree. In hindsight, having multiple versions was a bad idea and I do not think it honestly benefits anyone from a learning perspective (or the learning benefits are really minor).

**Comment by NathanLovato** [comment]
I confirm we're moving towards a reference manual and moving away from step-by-step, follow-along tutorials for the official docs. We're only looking to keep dodge the creeps and have a beginner 3D series in the getting started guide.

Would you be OK to move your FPS tutorial series to your own website or another website, or repository? I'll be removing some tutorials and series from the `latest` branch of the docs soon.

And as @aaronfranke said, we're also looking to remove binary files from this repository. It'd be best to have the project in the demos repo, or maybe on a dedicated repo.

Closing this PR for now.

**Comment by aaronfranke** [comment]
Yeah, we can just delete these files from the repo. They still exist in the Git history and in older branches (and in the branch this PR is based on), so it would be easy to salvage it later.

**Comment by TwistedTwigleg** [comment]
> Would you be OK to move your FPS tutorial series to your own website or another website, or repository? I'll be removing some tutorials and series from the `latest` branch of the docs soon.

It's already on my website, RandomMomentania, so I guess that's fine.

> And as @aaronfranke said, we're also looking to remove binary files from this repository. It'd be best to have the project in the demos repo, or maybe on a dedicated repo.

There's a repository for it here: https://github.com/TwistedTwigleg/Godot_FPS_Tutorial

**Comment by NathanLovato** [comment]
Thanks!

**Pull request closed without merging**
