### PR TITLE
Update introduction.rst

### PR DESCRIPTION
**Pull request by N3ST0R-byte**
Changed Q&A to forum, and the link.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by N3ST0R-byte** [comment]
@AThousandShips Please do.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2.

**Pull request merged**
