### PR TITLE
Update 05.the_main_game_scene.rst for global_position

### PR DESCRIPTION
**Pull request by libroraptor**
Replace 
mob.position = mob_spawn_location.position
with
mob.position = mob_spawn_location.global_position

Please check csharp because I don't know it.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Why is this requried? The position here should be in local space as the `mob_spawn_location` is *also* in the same space, under the main scene, further this doesn't match the demo project which works correctly, so I do not think this is valid

Please explain why this should be done

**Comment by libroraptor** [comment]
This change (or something else) is required because it doesn’t work in the tutorial – the effective path in local space functions as if it is only half as big as the screen, resulting in mobs spawning along the edges of the upper left quadrant, not the edges of the whole screen.

Maybe there a change needed in how the path is defined? Or to ensure that it points to the correct parent?

I am a novice; I just came across this problem while working through the tutorial so don’t know what is really wrong. Just posted this modification (which works) in order to start conversation about where the actual problem is.

**Comment by libroraptor** [comment]
I found this:
https://github.com/godotengine/godot-docs/issues/6372 <https://github.com/godotengine/godot-docs/issues/6372>

and I wonder whether the actual problem is that the path’s datum point needs to be set as a tutorial step.

**Comment by AThousandShips** [comment]
I tested the demo project, which is identical to this, and the code works perfectly as it is without this change, this change is not needed

This is not a valid change, you must have missed some detail in the tutorial as the code is fully valid

Closing as this change isn't required and isn't valid

I'd suggest asking in the other [community channels](https://godotengine.org/community) for help with your problem, chances are you missed some detail when applying this tutorial, check out the [demo code](https://github.com/godotengine/godot-demo-projects/tree/master/2d/dodge_the_creeps) and compare your code

Thank you for your contribution nonetheless

**Comment by libroraptor** [comment]
I have figured out the problem. You are right: it isn’t the code that needs to change. 

The problem is that the MobPath.Position was not (0,0), but at approximately mid-screen. 

Thus the MobPath looks to be in the right place in the construction interface but gets displaced during build to be centred on the upper left corner.

So I suggest considering an extra line to the tutorial for drawing the MobPath: 

Ensure that the path’s position is (0, 0). If not, set it to (0, 0) and move the MobPath nodes so that they are close to the corners of the display boundary.

**Pull request closed without merging**
