### PR TITLE
Remove outdated custom mouse cursor demo project reference

### PR DESCRIPTION
**Pull request by Daniel-The-Fox**
Hi there,

I'm totally new to Godot (version 4.1.2) and I'm currently trying to get the [custom mouse tutorial by Jon Topielski](https://www.youtube.com/watch?v=JrQ1-Ea6_KM) I found [on YouTube](https://github.com/jontopielski/cursor-tutorial/tree/main) to work in Godot 4.1.2. His tutorial also doesn't work out of the box in Godot 4.1.2, but it doesn't seem as outdated as the one currently linked in the docs. 

Once I have a working code snippet for a custom mouse cursor demo project in Godot 4.1.2, I'd be happy to share and link it here in the docs, if that sounds interesting for you? :)

### CODE REVIEW

**Review by skyace65 — APPROVED** [review]
Putting aside the fact that it's very outdated I'm fine removing it because I don't think be should be linking to non-official github repositories for demos.

Daniel if you want to add your own code in the future that covers this feel free to open a PR. But keep it in a code block in the docs instead of a link to your own repository.

**Comment by Daniel-The-Fox** [comment]
> Putting aside the fact that it's very outdated I'm fine removing it because I don't think be should be linking to non-official github repositories for demos.
> 
> Daniel if you want to add your own code in the future that covers this feel free to open a PR. But keep it in a code block in the docs instead of a link to your own repository.

Sure, once ready, I'll happily open another PR to add an up-to-date working code example directly on the document page for custom mouse cursors. 👍🏻

**Review by Piralein — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1.

**Pull request merged**
