### PR TITLE
Update singletons_autoload.rst

### PR DESCRIPTION
**Pull request by Hugo-Trentesaux**
fix scene name to match zip template

### CODE REVIEW

**Comment by raulsntos** [comment]
The template seems to be a GDScript project, in which case I believe the [naming convention](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#file-names) is to use snake_case so maybe the [template](https://github.com/godotengine/godot-docs-project-starters/tree/master/src/singleton_autoload_starter) should be updated instead.

That said, the naming convention in C# is to use PascalCase for all files and this PR only updates the C# code, so maybe we should make this change regardless of how the files are named in the template.

**Comment by Piralein** [comment]
Both should be changed, the files in the template project should be all `snake_case` and the C# version in the docs should be `PascalCase`.
(In my opinion)

**Review by Piralein — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Sorry this has been sitting for a bit. I agree with the discussion above, we should fix this regardless of the GDScript template (but we should likely fix that too :))

Merged. Thanks for contributing, and congrats on your first merged contribution to Godot's docs!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
