### PR TITLE
Document file path String methods in File paths in Godot projects

### PR DESCRIPTION
**Pull request by Calinou**
- See https://github.com/godotengine/godot-docs-user-notes/discussions/106#discussioncomment-10525790.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]
Mild approval, because I wonder if just that sentence (and maybe one example) is enough, with a link to the class ref.

I'm not a big fan of reproducing the class ref like this, because it tends to produce lots of additional effort with the list getting outdated, people creating issues and PRs, us reviewing + merging + cherrypicking etc. If we can, we should have information once and link to it, instead of duplicating. That said, it can be worth it if its especially important, I'm just not sure thats the case here?

**Review by skyace65 — COMMENTED** [review]
I agree with mhilbrunner that this isn't ideal. I think it would be better to just say something like "The string class offers several methods to work with strings that represent file paths, you can find a list of it's class reference page here" and link to the class reference page.

**Comment by Calinou** [comment]
> I think it would be better to just say something like "The string class offers several methods to work with strings that represent file paths, you can find a list of it's class reference page here" and link to the class reference page.

The String class has a lot of methods unrelated to path manipulation, which is why I opted to explicitly list all relevant methods.

**Comment by mhilbrunner** [comment]
@Calinou That makes sense. Do we maybe want to maintain the list in the class reference for `String` then, and link to it here? That at least increases the chance that we remember to update it when changing `String`.

**Comment by tetrapod00** [comment]
As a *user* of the engine, a list in the File Paths page is clearly the right place for this information. Whether the maintenance burden is worth it is up to you.

Putting the list in the class reference page (presumably in the intro section?) and linking also seems fine, but is there any real precedent for listing a subset of methods like that in the class reference? It means that there is a redundant list of the same methods twice (once as a subset, and once in the main methods list), and it clutters the class reference for String if you're looking at it for other reasons.

**Review by skyace65 — APPROVED** [review]
Given the discussion I'm in favor of merging this as is. I'd also recommend that instead of copying this list in the class reference we should link to this page in the "tutorials" section of the string class.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merging as per the above. Thank you!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.

**Pull request merged**
