### PR TITLE
Always use variables to access iOS-only singletons in Plugins for iOS

### PR DESCRIPTION
**Pull request by Calinou**
Follow-up to https://github.com/godotengine/godot-docs/pull/4465.

This is required to avoid script compilation errors on other platforms.

@naithar Could we expose dummy singletons that do nothing on other platforms to avoid the need to do this?

### CODE REVIEW

**Comment by Difference** [comment]
Both stable and latest docs are missing an underscore in product_id in the responce event example 
image

**Comment by naithar** [comment]
> @naithar Could we expose dummy singletons that do nothing on other platforms to avoid the need to do this?

I'm not sure why it's needed, especially since this singletons are coming from non-engine Godot code. Would it be required to create singleton for every possible plugin?

As far as I understand Android plugins are used the same way - singleton are stored in a variable: https://docs.godotengine.org/en/stable/tutorials/platform/android_in_app_purchases.html. So I don't see a reason to handle iOS plugins differently.

**Comment by Calinou** [comment]
> Both stable and latest docs are missing an underscore in product_id in the responce event example

Fixed :slightly_smiling_face: 

(This will be visible in the deployed documentation once this pull request is merged and cherry-picked to the `stable` branch.)

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by Difference** [comment]
It seems the SKPaymentTransactionStateRestored also returns the app receipt in ["receipt"] .
This should be documented, because it is currently the only way to get the receipt.

In my understanding, it is the recommend way to check date of purchase (important if updating app form Paid->Premium) and also to check in app purchases, without calling restore_purchases.

I think there to important functions should be added to the IOS plugin:
RefreshRecipt()  see https://developer.apple.com/documentation/storekit/skreceiptrefreshrequest
GetRecipt() returning the receipt in the same way that SKPaymentTransactionStateRestored gets it.

**Pull request merged**
