### PR TITLE
Update compiling_for_x11.rst

### PR DESCRIPTION
**Pull request by gau-veldt**
Mention the lib-xrandr-dev dependency on X11 platform.

### CODE REVIEW

**Comment by gau-veldt** [comment]
This is a recent dependency: https://www.facebook.com/photo.php?fbid=10209230842386256&set=gm.788687757934487&type=3&theater

**Comment by gau-veldt** [comment]
someone needs to tweak those oneliners though...

**Comment by vnen** [comment]
This was already done with #175...

**Comment by gau-veldt** [comment]
someone beat me to it... :P

**Pull request closed without merging**
