### PR TITLE
Add instructions for updating a GDExtension for Godot 4.1

### PR DESCRIPTION
**Pull request by dsnopek**
This follows up on https://github.com/godotengine/godot-docs/pull/7611 to add some more detailed instructions for updating a GDExtension for Godot 4.1.

I'm not entirely sure I'm showing the C++ changes in the most understandable way. With the incomplete syntax highlighting it's really hard to immediately see difference between the two code snippets. If anyone has any suggestions on how to make it clearer, please let me know!

### CODE REVIEW

**Review by paddy-exe — APPROVED** [review]
From looking over it, this looks great. Not sure if we need to also mention that there will be a new branch of godot-cpp named `4.1` to checkout?

**Comment by dsnopek** [comment]
Thanks!

I've added a small note regarding the `4.1` branch of godot-cpp

**Review by paddy-exe — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks! Merged.

**Comment by Syogren** [comment]
I am so sorry if this is a silly question, but are these instructions for gdextensions that we have made, or ones we downloaded from the assetlib?  Because I can't find where the faulty code is in the godot git plugin.

**Pull request merged**
