### PR TITLE
Typo in Bug Triage Guidelines

### PR DESCRIPTION
**Pull request by Shaswath31**
Typo

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by Shaswath31** [comment]
My bad. I found the error in 4.2 documentation and hence targeted that branch. I changed the base to "master". There seems to be a minor conflict. I don't think I have the permission to resolve it. Also, was this GitHub workflow of changing branches proper? I'm a bit new to open source contributions.

**Comment by Piralein** [comment]
You need to rebase your branch,
please read the workflow about the "Rebasing your branch onto another" linked above. (second link)
For more information about git rebase, see [github docs](https://docs.github.com/en/get-started/using-git/about-git-rebase).

**Comment by Shaswath31** [comment]
Changing the base branch within the pull request is not enough??

**Comment by AThousandShips** [comment]
If you cannot use the command line interface you can close this branch and open a new correct one, but no the base branch is the *target* branch, it doesn't change your branch in any way

**Pull request closed without merging**
