### PR TITLE
Removing " a" (singular) in front of "ViewportContainers" (plural)

### PR DESCRIPTION
**Pull request by golddotasksquestions**
This is basically a test for me in order to learn how to properly submit PRs, while also doing something tiny bit useful.

I submit this PR against the stable branch since this is first and foremost a test and this doc page has moved in the master branch to a different folder location (master: scripting, stable: misc), but I'm very happy to also submit it to master if this is wished :)

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by golddotasksquestions** [comment]
Hm, I was trying to make a new PR to submit an improvement on the "[Using Tilemaps](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html)" tutorial, but it seems like it automatically got lumped together with this first test PR.

I would think this kind of lumping together is not desirable.

**Comment by pycbouh** [comment]
You need to use different branches in your fork, one for each PR. You can still fix this by creating a new branch for your second PR, moving new commits there and force pushing the branch used here to it's original state.

I hope this gives you related keywords to start learning these parts of distributed VCSs like git.

**Comment by akien-mga** [comment]
Note that PRs shouldn't go to the `stable` branch, this branch is a carbon-copy of the current stable branch (`3.2`).

Changes that are valid for all Godot releases should go to `master`, and they can be cherry-picked for the branches which are still actively updated (`3.3`, `3.2`, and stable as copy of `3.2`).

**Comment by golddotasksquestions** [comment]
@akien-mga I am aware about this (obviously read the text in the comment), but the "Using Tilemaps" docs page for example does not exist in master (naturally, as the new 4.0 TileMap is not finished yet), and the "Manually Change Scenes" page is in a different folder on master.

So while I understand I would normally submit PRs to the master branch, I thought in this case it is the right move to submit it to stable directly. Is this a wrong assumption?

**Comment by golddotasksquestions** [comment]
I managed to make two separate PRs now, one for each issue:
The "Manually Change Scenes" to master and the "Using Tilemaps" one to stable (does not exist in master):

https://github.com/godotengine/godot-docs/pull/4846
https://github.com/godotengine/godot-docs/pull/4847

Thank you guys for your support on my first PRs ever!

**Comment by golddotasksquestions** [comment]
I managed to make two separate PRs now, one for each issue:
The "Manually Change Scenes" to master and the "Using Tilemaps" one to 3.2 (does not exist in master):

https://github.com/godotengine/godot-docs/pull/4846
https://github.com/godotengine/godot-docs/pull/4848

Thank you guys for your support on my first PRs ever!

**Pull request closed without merging**
