### PR TITLE
Add Martin Donald to tutorials.rst

### PR DESCRIPTION
**Pull request by JamesC01**
He has high quality godot shader videos. (re-opened pull request to master branch.)

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Hey! Thanks for contributing. Am I missing something or is there only a single recent video for Godot?

**Comment by skyace65** [comment]
Yeah it looks like it's just the one. I don't want to add him unless he makes more videos for Godot 4.x.

**Comment by mubinulhaque** [comment]
All of his videos are for Godot but only his latest one actually puts Godot in the title.

**Comment by skyace65** [comment]
> All of his videos are for Godot but only his latest one actually puts Godot in the title.

The issue isn't the name of the video. The issue is he only has one video that's applicable to Godot 4.

Given the large gaps between uploads and that his latest video is two months old I'm going to close this PR for now. If he makes more Godot 4 content in the future feel free to suggest him again.

**Pull request closed without merging**
