### PR TITLE
fix getting started URL

### PR DESCRIPTION
**Pull request by sethmccombs**
This PR should fix https://github.com/godotengine/godot-docs/issues/8030

this is my first Godot Docs PR so please let me know if I've missed anything!

### CODE REVIEW

**Comment by pranabekka** [comment]
I think it should reference toc-learn-introduction (getting_started/introduction/index.rst), which is the introduction to the Getting Started section and includes overview of key concepts, first look at editor, and how to learn new features

**Comment by sethmccombs** [comment]
@YuriSizov I see your 👍 on @pranabekka comment - what's the best way to link to that page? - Using [`:ref:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role) to a new `reST` label? (example below)  

something like 
**`about/introduction.rst`**
```
... Otherwise, :ref:`Getting Started <doc_getting_started>`
is a great starting point. ...
```

**`getting_started/about/introduction.rst`**
```
.. _doc_getting_started:

Introduction
============
```

**Comment by YuriSizov** [comment]
Yes, that's correct. I would probably call it `doc_getting_started_intro` to avoid ambiguity, but otherwise this is fine.

**Review by YuriSizov — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged. Thanks and congrats on your first merged contribution!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
