### PR TITLE
Mention antialiasing workaround in Custom drawing in 2D

### PR DESCRIPTION
**Pull request by Calinou**
This closes https://github.com/godotengine/godot-docs/issues/2379.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
The addon mentions Godot 3.x (https://github.com/godot-extended-libraries/godot-antialiased-line2d), should this really go in `master` then?

**Review by mhilbrunner — APPROVED** [review]
Discussed on Rocketchat, this is planned to be ported to Godot 4. If it isn't, we can remove the mention from GD4 docs down the line, its good to have this in all docs for now I think.

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by Calinou** [comment]
Cherry-picked to the `3.4`, `stable` and `3.3` branches.

**Pull request merged**
