### PR TITLE
Fix some more errors

### PR DESCRIPTION
**Pull request by YeldhamDev**
Only thing I couldn't fix was the `multimesh_set_as_bulk_array()` reference, as I have no clue to what substitute it for.

### CODE REVIEW

**Comment by clayjohn** [comment]
Looks like it is now ``multimesh_set_buffer``

Funny you did this! I started going through to fix errors this morning, but then realized we hadn't moved over all the class renames, so I decided to wait.

**Comment by YeldhamDev** [comment]
@clayjohn This PR is just to fix actual formatting errors, adapting the docs to the new names is out-of-scope and should be its own PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Yeah I haven't synced the classref for 4.0 as it's still very WIP, and it will prompt lots of changes to the docs that will make merging 3.2-relevant changes on 3.2 harder.

**Pull request merged**
