### PR TITLE
Fix grammar in step-by-step

### PR DESCRIPTION
**Pull request by JohnVeness**
Here are a few suggested edits.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Hey, welcome and thank you for contributing! In the future, it's better if you can submit your logical changes contained in a single commit (i.e. proof-reading a single file as a single commit). We can use squash and merge here on the docs, so its not a huge issue, but in general its cleaner for us to have a single commit (or one per logical change if its a larger PR).

Thank you, and congrats on your first contribution to Godot Engine's documentation! 🎉

**Comment by mhilbrunner** [comment]
Ah, missed that. Then congrats on your second one! :P Also, if you have any questions feel free to poke us in #documentation on chat.godotengine.org

**Comment by JohnVeness** [comment]
Can this please be cherry-picked for 3.4 and 3.5? It should apply cleanly as-is.

**Comment by Calinou** [comment]
Cherry-picked to the `3.5`, `3.4` and `stable` branches.

**Pull request merged**
