### PR TITLE
Update GLES2 differences doc with recent changes

### PR DESCRIPTION
**Pull request by clayjohn**
This PR reflects the functions added to the shader language in https://github.com/godotengine/godot/pull/31556, https://github.com/godotengine/godot/pull/30993, and https://github.com/godotengine/godot/pull/30895

And it reflects the post-processing options that will be added in https://github.com/godotengine/godot/pull/31845

https://github.com/godotengine/godot/pull/31845 needs to be merged before this PR is merged.

### CODE REVIEW

**Comment by clayjohn** [comment]
I need to update this now before it is merged.

**Comment by akien-mga** [comment]
> I need to update this now before it is merged.

Bump :)

**Comment by clayjohn** [comment]
Should be good now :) Thanks for the ping.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
