### PR TITLE
Updated "Reporting node configuration warnings"

### PR DESCRIPTION
**Pull request by FeatherAntennae**
- Replaced `func _get_configuration_warning():` by `func _get_configuration_warnings():`
- Replaced `string` with `PackedStringArray` as the former doesn't work anymore.
- Removed the line breaks that were added to the String to visually separate warnings, as it is no longer required.
- Replaced the "empty string" with "empty array" in the comment about how to report no errors.
- Renamed `warning` variable to `warnings` to indicate that it can contain multiple warnings.

### CODE REVIEW

**Comment by Piralein** [comment]
While the majority of the PR got superseded by #7145, it didn't contain the last 2 changes.
Please rebase the PR with only the last 2 points and its good to go.

**Comment by FeatherAntennae** [comment]
@Piralein Was there something wrong with the contribution, so I know better what to do next time? Otherwise, is there something I don't understand about how to contribute?

It seems every time I contribute here, or on the engine itself, the PR only gets attention much later, once a newer PR from someone else got merged with half the things I had done.

I'm happy to contribute whenever I can, but at this point I might as well just make bug reports and wait for someone else to fix the problems instead.

**Review by Piralein — APPROVED** [review]

**Comment by Piralein** [comment]
@FeatherAntennae Your contribution is totally fine.

I don't follow the main repository to much, but in regards to the documentation repository it really just boils down to not enough reviewers/time. Members and contributors of different areas chime in from time to time to review PR's in their field of expertise or just general changes of new PR's. This means if a PR is already some days older they may not know the new PR is a duplicate of an already existing one and approve/merge it. The same problem is probably 10x times higher in the main repository. In the end, the only thing we can do is try to catch up with the PR backlog to minimize the overlaps and use the new tools like [PR's by file](https://godotengine.github.io/godot-prs-by-file/#godotengine/godot-docs) to spot duplicates. 

I'm sorry about this, I know this has to be frustrating. The only thing I can give as advise is joining the [contributor chat](https://chat.godotengine.org/) and asking for a review in the related channel. (for this PR it would be the documentation channel)

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
100% what Piralein said. Sorry you had this experience so far, we're just really swamped with the backlog compared to the resources we have. Help welcome, but I get it if you feel discouraged. :) If you think your PR is ready to go, feel free to ping us here or on the Rocketchat #documentation channel, or even if you're unclear whats still left to do.

Things sometimes slip through, this one should absolutely have been merged way earlier.

Thanks for contributing, we desperately _do_ need more docs contributors! Unfortunately, we reviewers too. :)

**Pull request merged**
