### PR TITLE
Edit first paragraph under "Light nodes"

### PR DESCRIPTION
**Pull request by puchik**
Edited the first paragraph under "Light nodes" for concision. Removed the first part of the second sentence. Instead of noting that lights are discussed later in the article, added internal links.

(Reverted grammar fixes in thread safe APIs since I'm trying to put these in separate pull requests)

### CODE REVIEW

**Comment by clayjohn** [comment]
Looks good to me!

**Comment by NathanLovato** [comment]
Thanks 🙂

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.

**Comment by NathanLovato** [comment]
Excuse-me, I forgot about that. I'll try to remember to cherry-pick relevant PRs when I merge :)

**Pull request merged**
