### PR TITLE
Fix broken link to Getting Started in About/Introduction

### PR DESCRIPTION
**Pull request by pranabekka**
In [about/introduction](https://docs.godotengine.org/en/stable/about/introduction.html) "Getting Started" link points to [index.html#sec-learn](https://godotengine.org/en/stable/index.html#sec-learn) which shows offline documentation options on the docs landing/home page.
expected url is [getting_started/introduction/index.html](https://docs.godotengine.org/en/stable/getting_started/introduction/index.html)

See Issue #8030

### CODE REVIEW

**Comment by AThousandShips** [comment]
Your branch is from the wrong origin, you need to rebase your branch to 4.x not 4.1, see: [PR Workflow - Updating your branch](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch).

**Comment by pranabekka** [comment]
Sorry, this is the first time I'm creating a PR: I saw while creating it that I should do it against master, but Github said I could still submit the PR, so I went ahead.

Would it be easier if I just close this one, then make the changes to master* and submit a PR for that?

* The placeholder PR comment says master, plus I don't see a 4.x?

**Comment by AThousandShips** [comment]
Meant `master` which is 4.x

**Comment by AThousandShips** [comment]
Another PR with the right branch has been opened:
* https://github.com/godotengine/godot-docs/pull/8034

**Comment by pranabekka** [comment]
Cool. Seems like mine was incorrect anyway, since I'm not familiar with reST

**Comment by AThousandShips** [comment]
Superseded by:
* https://github.com/godotengine/godot-docs/pull/8034

**Pull request closed without merging**
