### PR TITLE
Fix code example in Using NavigationMeshes

### LINKED ISSUE #7088: unable to iterate object of collisionpolygon2d
**Your Godot version:4.0.1**

**Issue description: Example code does not work**

**URL to the documentation page:https://docs.godotengine.org/en/4.0/tutorials/navigation/navigation_using_navigationmeshes.html#doc-navigation-using-navigationmeshes**

See screenshot for the error:
navigationmesh

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #7088.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Review by smix8 — APPROVED** [review]
Sure this broken example should be fixed for now and Godot 4.0.

Heads up that I planned to removed the entire section from the doc rewrite for the NavigationMeshGenerator pr as the buildin baking and the change to outlines make this manual script code more or less obsolete.

**Comment by mhilbrunner** [comment]
Thanks! 🎉 Merged.

**Comment by acloudmovingby** [comment]
@kleonc I'm not very familiar with the Godot contribution process, but someone on the godot chat said we have to add a `cherrypick:4.0` tag to this to make sure it gets cherry-picked back onto the 4.0 branch and therefore will show in the website. 

I'm a total beginner to Godot and was just using the docs to learn and I noticed this problem. Once I realized that the issue was old Godot 3 code, I figured it was an easy fix and so I forked the docs repo and started to make a PR...that's when I realized it had already been fixed. Long story short, the website doesn't show master, it shows the 4.0 branch and we have to cherry-pick this PR onto that somehow.

**Comment by kleonc** [comment]
@acloudmovingby Oh, I forgot to mark it for cherry-picking to 4.0, indeed. Done so now. Thanks for the remainder. :slightly_smiling_face:

**Comment by mhilbrunner** [comment]
Pushed to `4.0` and `stable`.

**Pull request merged**
