### PR TITLE
Update GDExtension docs with 4.1 branch info

### PR DESCRIPTION
**Pull request by paddy-exe**
Fixes https://github.com/godotengine/godot-docs/issues/7648

### CODE REVIEW

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Comment by dcuny** [comment]
I don't understand how this bug process works. It's been over a week, the original bug has been closed, this ticket merged, and the page _still_ is incorrect.

Additionally, this bullet point is _also_ incorrect:

> a Godot 4 executable,

With the changes to GDExtension, this needs to be the Godot 4.1. Godot 4.0 is not binary compatible with GDExtensions compiled under 4.0.

One of the problems with writing:

> Godot 4.1 is being used here as an example.

is that it glosses over the _other_ difference between Godot 4.0 and 4.1 (which is mentioned in #7648) - the change to the code in the class initializer `example_library_init`.

It would be better to state at the top of the article something along the lines of:

* GDExtension in Godot 4.1 breaks binary compatibility with Godot 4.0;
* The instructions here only apply to Godot 4.1; and
* Instructions for building GDExtension in Godot 4.0 can be found [[INSERT LINK HERE]]

The text can then proceed with the assumption that the user is using Godot 4.1 (or later).

**Comment by dsnopek** [comment]
@dcuny I just posted PR https://github.com/godotengine/godot-docs/pull/7699 in attempt to address your concerns! Please let me know what think.

I didn't follow your suggestions exactly, as I wanted to still attempt to make the page as "future proof" as possible, and not clutter it up with all the specifics related to the GDExtension breakage between Godot 4.0 and 4.1.

**Comment by dcuny** [comment]
The most important thing is that the instructions provided work with the version that it says it work with. 😄 

I'm not sure how future-proof you can make it. You can be optimistic and _hope_ that `GDExtention` remains stable, but honestly, I'd expect it to continue to be problematic in the foreseeable future.

Thanks!

**Pull request merged**
