### PR TITLE
📄Fix internationalizing games outdated setting path

### PR DESCRIPTION
**Pull request by Leggy7**
Updated path to Locale setting to match the doc version 4.1

### CODE REVIEW

**Comment by skyace65** [comment]
Looks good! The image right below that part of text needs to be updated as well. Here's an image to replace it with.
[locale_test.zip](https://github.com/godotengine/godot-docs/files/12775669/locale_test.zip)

**Comment by Leggy7** [comment]
Image updated @skyace65

**Comment by skyace65** [comment]
The image needs to be in webp format. We've slowly been converting everything from pngs. Also please try and keep everything in 1 commit, if you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request).

**Comment by Leggy7** [comment]
Uh sorry, wasn't aware of the workflow. Set up the correct image format.

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
