### PR TITLE
Remove DevDocs from Readme file

### PR DESCRIPTION
**Pull request by skyace65**
Follow up to PR #8896, didn't realize it was also in the readme file at the time.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]
I'm actually not sure whether we should link to the stable version instead of indev/master. (Like in this PR: https://github.com/godotengine/godot-docs/pull/9225)

Maybe both.

This also needs to be rebased to fix CI because of an error in master that has since been fixed.

**Comment by skyace65** [comment]
Rebased

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Pull request merged**
