### PR TITLE
Fixed wrapf() error in the custom drawing in 2d tutorial

### PR DESCRIPTION
**Pull request by thebspin**
The docs had a mistake where it said wrap (And Wrap for c#) where it should be wrap and Wrapf for c#

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thank you! For GDScript this indeed seems right.

For C#, `Wrap` still seems to be correct: https://github.com/godotengine/godot/blob/abc6dd7fa20bf3cb7bda6a555a76c1cf2ba1aff8/modules/mono/glue/Managed/Files/Mathf.cs#L326

Wondering whether that should be `Mathf.Wrap()` in this place in the docs, and whether we should change the C# function to match GDScript. cc @neikeq

**Comment by thebspin** [comment]
Ah maybe i should have not assumed that the notation is the same for C# my bad :)

This being my first time contributing do i now need to update my master with just the GDScript example?

**Comment by mhilbrunner** [comment]
No worries, IMO these two functions *should* really be the same :)

Yeah for now the best is probably to just fix the GDScript example.

You need to update your master branch. (as its the branch you created this PR with)

In general, there are two ways:

You either edit your last commit by amending your changes, or you create a new commit with the fix and then for cleanliness squash those two commits (the original + the fix) into one.

See https://www.burntfen.com/2015-10-30/how-to-amend-a-commit-on-a-github-pull-request or other tutorials around :)

Don't worry, this *is* a little involved when first getting used to it, if you need help or have questions feel free to ask here or on the docs channel on Discord!

**Comment by neikeq** [comment]
It's `Mathf.Wrap` in C#, both for int and float. We named is this way as C# supports overloading, so the "f" suffix was unnecessary.

**Comment by thebspin** [comment]
I tried the amending part, not sure if it went okay? Can you check? :)

**Comment by bojidar-bg** [comment]
@thebspin It almost worked. You should have done a `git push --force` instead of `git pull` though, since the `git pull` generated a merge commit.
Something like this should get the PR to a proper state:
```
git reset --hard HEAD^
git push --force
# And, in case something went wrong:
# git reflog
# git reset --hard <commit SHA from reflog>
```

**Comment by thebspin** [comment]
@bojidar-bg thanks!
I just did ``git reset --hard HEAD^
git push --force``
I am not sure where i can see myself if everything went correct? If i look at my own repo it says last commit 3 days ago so i assume i need to do something else/more?

**Comment by mhilbrunner** [comment]
Were you on the right branch? If you force-pushed the PR branch, that force push would show up here :)

**Comment by thebspin** [comment]
I should be..I didn't change or made any other new branch. I just tried it again, i now see my commit message underneath your comment.

**Comment by mhilbrunner** [comment]
Yay, that looks correct now - besides that the commits should be squashed into one, but for now I'll do that with the merge. Thanks for this, and thanks for your patience with figuring out git :)

Thank you and congrats on your first contribution to Godot!

**Pull request merged**
