### PR TITLE
Fix animation name in Your first 2D game

### PR DESCRIPTION
**Pull request by Calinou**
- See https://github.com/godotengine/godot-docs-user-notes/discussions/105#discussioncomment-10624281.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you, merged.

**Comment by Piralein** [comment]
This change is wrong in my opinion.
The images are called `playerGrey_up1.png`, `playerGrey_up2.png` and `playerGrey_walk1.png`, `playerGrey_walk2.png`.

**playerGrey_up[1/2]** means `playerGrey_up1.png` and `playerGrey_up2.png`
**playerGrey_walk[1/2]** means `playerGrey_walk1.png` and  `playerGrey_walk2.png`

> Drag the two images for **each** animation, named...

**Comment by Dreyseth** [comment]
The file names are not the problem here.  The issue is in readability of the text "[1/2]", which reads as "one OF two" rather than the intended "one AND two".

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.

**Comment by Calinou** [comment]
@Piralein @Dreyseth This should be addressed by https://github.com/godotengine/godot-docs/pull/10101.

**Pull request merged**
