### PR TITLE
MultiSheet Tutorial

### PR DESCRIPTION
**Pull request by nonunknown**
Added a tutorial for 2D section. It will teach to the user how to use multiple spritesheets for one sprite only (i.e: In a case that Character A has multiple 1024x1024 files )

### CODE REVIEW

**Comment by nonunknown** [comment]
Whay is needed for this tutorial to get into the docs?

**Comment by mhilbrunner** [comment]
Hey! Thanks for your contribution and sorry it took a little to get a reply :)

We're currently thinking about restructuring the Godot Docs for Godot 4.0 (see this proposal: https://github.com/godotengine/godot-docs/issues/3390).

We're especially thinking and talking about trying to cut the number of tutorials to get a more manageable maintenance workload for the docs maintainers.

At a first glance, this tutorial (while great!) is more of a general TexturePacker / how to use Spritesheets tutorial, and my first thought is it may be better fit in a future community tutorials section or similar.

Thats just my opinion however.

cc @NathanLovato

**Comment by nonunknown** [comment]
I Apreciate the feedback!, And understand that. I've know about this proposal which is excellent btw!

**Comment by NathanLovato** [comment]
Same feedback as @mhilbrunner. I'm personally waiting for a green light on at least some parts of the proposal to work on the next steps, and content guidelines + cleaning up the docs would come first to me (removing and improving content before adding more).

**Comment by mhilbrunner** [comment]
Seems we agree then. :)

I'm closing this for now, of course it'd be great if you could still publish that tutorial somewhere, it *is* useful!

And maybe keep a watch out in case we either provide a better place for *community tutorials* or there is a place for this after the 4.0 reorg.

Thanks again for the effort to contribute to the docs!

**Pull request closed without merging**
