### PR TITLE
Added minimal documentation for _get_configuration_warning method

### PR DESCRIPTION
**Pull request by hasahmed**

### CODE REVIEW

**Comment by volzhs** [comment]
it would be great to have the same description at here too.

https://github.com/godotengine/godot/blob/9c3ddf05cb9c59817d885e9daca6e8f61c89dc97/doc/classes/Node.xml#L44-L45

**Comment by Calinou** [comment]
Thanks for your contribution! :smiley:

The class reference in the online documentation is automatically generated based on XML files in the main Godot repository. As @volzhs said, please edit `Node.xml` in the [godotengine/godot](https://github.com/godotengine/godot) repository to add the description and send a pull request there.

PS: Documentation changes for other pages should be sent to the `master` branch of this repository, not the `3.1` branch.

**Comment by hasahmed** [comment]
> Thanks for your contribution! 😃
> 
> The class reference in the online documentation is automatically generated based on XML files in the main Godot repository. As @volzhs said, please edit `doc/classes/Node.xml` in the [godotengine/godot](https://github.com/godotengine/godot) repository to add the description and send a pull request there.
> 
> PS: Documentation changes for other pages should be sent to the `master` branch of this repository, not the `3.1` branch.

Thanks for the heads up. I edited repo because clicking the 'edit on github' link on http://docs.godotengine.org/en/3.1/ takes you to the docs repo. Can that be changed to link to the docs of the main repo because thats what people actually need to edit?

**Comment by Calinou** [comment]
> Can that be changed to link to the docs of the main repo because thats what people actually need to edit?

I'm afraid we don't have control on that link, as it'll always point to the link to the page generated in this repository.

**Pull request closed without merging**
