### PR TITLE
Add note around mob velocity to direct users to next section

### PR DESCRIPTION
**Pull request by Starkandco**
The idea of mob completion often creates an expectation of movement. Note to encourage users to test and move on to next section

### CODE REVIEW

**Comment by Starkandco** [comment]
@AThousandShips - I'm not sure if I got this right or I've totally overcomplicated this in my head, sorry if this isn't right now

**Comment by AThousandShips** [comment]
The branch is correct now!

**Comment by skyace65** [comment]
Closing this PR. There's nothing in the mob code that should make someone following this expect the mob to move.

**Comment by Starkandco** [comment]
> Closing this PR. There's nothing in the mob code that should make someone following this expect the mob to move.

Well you're missing a trick here to be frank, the point wasn't that the code indicates that it should move. It's the idea that the mob is complete, which, holistically it isn't functioning how it will function later on in the tutorial. I've seen other people, and personally experienced myself, expecting the mob to do something when you test at this stage, and being concerned that they have missed something in the instructions, and spend time going back over the tutorial on this one.

**Pull request closed without merging**
