### PR TITLE
Update VisualShader page for 4.3

### LINKED ISSUE #7563: Outdated Visual shader documentation/tutorial
**Your Godot version:**
4.1beta3

**Issue description:**
The tutorial/documentation page for the visual shader functionality has not been updated for 4.x even though the page is marked as up to date. The screenshots are all outdated, and some of the information may need to be rewritten. 

The page contains a couple of node descriptions, but these seem to be picked quite arbitrarily, with no direct mention of how to get a better understanding of all the other nodes available. So perhaps a good idea would be to include a link to the class reference listing for all the visual shader nodes
https://docs.godotengine.org/en/latest/classes/class_visualshadernode.html
For further information on the individual nodes.

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/tutorials/shaders/visual_shaders.html

### PR DESCRIPTION
**Pull request by skyace65**
Updates the visual shader page for Godot 4.3. There was a major redesign of it in https://github.com/godotengine/godot/pull/85017. I've also documented the new reroute node added in https://github.com/godotengine/godot/pull/90534.

This solves some of the issues in #7563. The only images that still need to be updated are some from the last section, I was unable to put together visual shaders I could use for screenshots.

### CODE REVIEW

**Comment by skyace65** [comment]
@clayjohn is this something you want to review?

**Review by paddy-exe — APPROVED** [review]
LGTM

**Review by AThousandShips — APPROVED** [review]

**Comment by skyace65** [comment]
CC @mhilbrunner

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you! And thanks everyone for the reviews. Merged.

**Pull request merged**
