### PR TITLE
Various fixes to rotations doc.

### PR DESCRIPTION
**Pull request by tagcup**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Looks good, however this re-adds a few removed instances of the words *really* and *very*. Could you re-remove them? :)

**Comment by tagcup** [comment]
Did you actually read those sentences? Those words convey a meaning, that's why they're there in the first place.
And before you tell me anything about writing, I basically write (scientific) papers and books for a living. And dropping certain words regardless of the context doesn't make any sense to me.

**Comment by tagcup** [comment]
If you wanna remove those anyway, you can go ahead and do it yourself but to me they're perfectly fine.

**Comment by mhilbrunner** [comment]
>While it is a very extensive subject and most programmers haven't even heard of it, it is very relevant in game development

What do the two *very*s here add to the overall content?

**Comment by mhilbrunner** [comment]
See [Godot docs writing guidelines](http://docs.godotengine.org/en/3.0/community/contributing/docs_writing_guidelines.html#remove-unnecessary-adverbs-and-adjectives).

I'm not saying what people are allowed or not allowed to do; just that [usual advice](http://writerscircle.com/very-and-other-useless-words-to-erase-forever/) is to aovid empty filler words like *very* and *really*.

>change it after merging

I personally just spent hours going through the docs to try to actually make them adhere to those guidelines (which, by the way, were not written or decided by me). So I have no interest in merging a PR undoing those changes to then make them again.

But I don't want to argue, the PR looks good besides this so I'll just leave it to somebody else to merge. Thanks for the work. :+1:

**Comment by tagcup** [comment]
I disagree that those are "empty filler words". Like I said, they convey meaning by adding emphasis/weight on things.

If you're against "merging a PR undoing those changes to then make them again" then maybe you shouldn't remove them in the first place.

And as I mentioned, I do research and write it as a living, and so I routinely work with professional editors and publishers, and I've never experienced this kind of nitpicking --this is just nonsense, and I recommend you to revise your writing guidelines.

**Comment by tagcup** [comment]
And FYI, those "empty filler words" are pretty important when teaching, when you actually see people getting tired --you can't assume you audience is like a bunch of robots who will absorb what you say at 100% fidelity, you need to add "empty filler words" to convey what is important, that you started talking about a different thing, etc.

**Comment by NathanLovato** [comment]
> this is just nonsense, and I recommend you to revise your writing guidelines.

The writing guidelines were made with professional writers, for the needs of an online community filled with non native speakers, people of all ages, from all around the world. With accessibility in mind. As we work on educational material and especially for open online docs I think making it accessible to the readers should be a priority.

Looking at the PR removing most of the `very` doesn't change the sentences' meaning. It takes a second to remove them (one `s/very //g` command here)...

> you need to add "empty filler words" to convey what is important, that you started talking about a different thing, etc.

No. Not at all. You can use punctuation, stylistic figures, tone, specific vocabulary, anecdotes and plenty of alternate writing techniques that work a lot better than adverbs. If your goal is to make your work more accessible to the readers.

**Comment by tagcup** [comment]
Yes, you do.

And no, I don't agree with anything you said, it's all subjective and opinionated. If you don't want to merge it, it's fine, I can live with it.

**Comment by tagcup** [comment]
> The writing guidelines were made with professional writers

This is very hard to believe since the work they do isn't professional at all

**Comment by NathanLovato** [comment]
Okay just do your thing

**Comment by Noshyaar** [comment]
> apparently @Noshyaar has blocked me for whatever reason

**Comment by tagcup** [comment]
...because I din't even remember talking to you, and I also don't remember how you're related to this thread, or how useful your contribution of leaving a nasty passive-aggressive comment here is.

Then again, trying to have a rational argument in the face of tribalism is like pissing against the wind.

**Comment by tagcup** [comment]
On that regard, maybe you can consider blocking yourself too

**Comment by Noshyaar** [comment]
>trying to have a rational argument

I'd rather be irrational if this is your idea of being "rational".

I expect rational individuals to blame themselves first before they blame others.

I expect rational individuals not to use "guidelines for scientific papers" on an official game engine documentation with existing guidelines without community's consent.

---

>how useful your contribution of leaving a nasty passive-aggressive comment here is.

Even if I properly contribute you're just going to disregard it, so what's the point? I'm not gonna waste my time.

And it was quoted from your message. It's you being aggressive.

---

> you can consider blocking yourself too

I see you're the only one blocking yourself because you don't even realize how you appear to other people.

---

Am I being irrational?

I don't care if you're a math "expert". This is an Open Source project. If you keep on treating other maintainers as inferior and not going to respect other people's opinions, I totally suggest you stop working on it so you're not wasting everyone's time.

---

To those finding this comment and not knowing me before, this is not how I usually treat people. I'm very sorry if it bothers you.

**Pull request closed without merging**
