### PR TITLE
Fix incorrect setup instructions in The profiler

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot-docs/issues/9902.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good. I just checked and the old language was true for Godot 3.5.3. So we might want to see why the behaviour changed and consider bringing back the ability to start the profiler before running the game

**Comment by skyace65** [comment]
Thanks!

**Comment by Calinou** [comment]
> Looks good. I just checked and the old language was true for Godot 3.5.3. So we might want to see why the behaviour changed and consider bringing back the ability to start the profiler before running the game

This was changed by https://github.com/godotengine/godot/pull/70151.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.

**Pull request merged**
