### PR TITLE
Corrected a few things in the openxr android documentation

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Now that Godot 4.2 is officially out and our vendors plugin has a full release, fixed up a few outdated things in the docs.

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
Thanks! Looks good to me :-)

**Review by Malcolmnixon — APPROVED** [review]
Looks good to me

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2.

**Pull request merged**
