### PR TITLE
Add Olde Sküül to list of porting companies in Console support in Godot

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot-docs/issues/7695.

@burgerbecky Sorry for the late turnaround on this. I've noticed there doesn't appear to be a working contact form on the Olde Sküül website. Is there a way potential customers could reach out to you?

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks, merged. Was waiting for a reply but I guess we can just go ahead and add this :)

**Comment by wkubiak** [comment]
@mhilbrunner @Calinou Just to be sure about this one - the merge went in even though no info was shared in terms of how to contact the Olde Skuul team about porting and/or publishing Godot Engine games?

**Comment by adamscott** [comment]
> the merge went in even though no info was shared in terms of how to contact the Olde Skuul team about porting and/or publishing Godot Engine games?

The production team decided to go ahead because we confirmed that Olde Sküül is a serious porting company. Unfortunately, we overlooked the fact that the contact page is currently broken, even if it was correctly pointed out by @Calinou.

I've personally asked Olde Sküül to update their contact page. So things should resolve soon.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
