### PR TITLE
update your first 2D game font information

### LINKED ISSUE #5562: Outdated description of adding custom font to label in "Your First 2D Game"
**Your Godot version:**
v3.4.2.stable.official [45eaa2daf]

**Issue description:**
There are some discrepancies between the docs under "Your first 2D game » Heads up display" when it comes to adding the custom font.

The docs are as following:
image

The editor as per version v3.4.2.stable.official:
image

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html

### PR DESCRIPTION
**Pull request by skyace65**
Updates the font instructions for your first 2D game. I also reordered when you're supposed to copy the font to make more sense. All images have gone through png compression. Closes #5562.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks! 🎉

**Comment by pycbouh** [comment]
This is not the correct fix for master, and there was already a PR that fixed it properly https://github.com/godotengine/godot-docs/pull/5542

**Comment by pycbouh** [comment]
Note that this should be fine for 3.x, so feel free to reopen it for the 3.4 branch 🙂 The problem is with the font sizes being their own thing in master, but not in 3.x.

**Comment by mhilbrunner** [comment]
Reverted due to the above in `master`, please resubmit for 3.4 :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
