### PR TITLE
Split visual_script_basics in three, fix typos, and improve grammar

### PR DESCRIPTION
**Pull request by DiemenDesign**
I close the other PR #546 as I created new files to split the original single doc, with additions as per suggested.

### CODE REVIEW

**Comment by cbscribe** [comment]
Splitting this seems reasonable to me. Once it's split, we can accept edits separately for each of the three docs, so I suggest we merge and add separate issues for revising each of them. @NathanLovato @akien-mga do you agree?

**Comment by NathanLovato** [comment]
@cbscribe agreed. @DiemenDesign can you squash the 12 commits? Ping me when it's done and i'll merge your PR

**Comment by NathanLovato** [comment]
Congrats for getting your contribution in!

**Comment by DiemenDesign** [comment]
I didn't do that much, I"m just glad I can help even in some small way.

**Pull request merged**
