### PR TITLE
Updated c_sharp_basics.rst

### PR DESCRIPTION
**Pull request by MightyPrinny**
Added some extra information about setting up C# for Godot in Windows.

### CODE REVIEW

**Comment by StraToN** [comment]
Can you squash these 2 commits into one? Thanks in advance ;)

**Comment by akien-mga** [comment]
.NET Framework 4.5 is actually a requirement for all platforms, so it should probably be mentioned further up and not specifically for Windows.

CC @neikeq

**Comment by neikeq** [comment]
Ideally that dependency would not be needed since we are using Mono's BCL and not .NET Framework's. This is a problem with MSBuild we will have to tackle in the future. If you look at the MSBuild output, it passes the .NET Framework's assemblies to CSC instead of Mono's. It seems to be a Windows-only issue, but I wouldn't be surprised if it could happen on other platforms as well under certain circumstances with .NET Core.

**Comment by MightyPrinny** [comment]
Ok I'll open a new one with one commit

**Pull request closed without merging**
