### PR TITLE
Fix reference to the editor/docs localization guide in the "Ways to contribute" page

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by Calinou** [comment]
I've had an issue where an otherwise valid reference was considered invalid by Sphinx. Clearing my local build folder using `make clean` solved the issue, but I don't know if you can do this on Read the Docs.

**Comment by akien-mga** [comment]
Indeed, I could reproduce the issue in my local build from when I wrote the content, but a simple `make html` after poking at one of the files fixed it. It's still fixed even with no changes.

**Comment by akien-mga** [comment]
It's the `.. highlight: none` before the title which breaks it.

**Comment by akien-mga** [comment]
Superseded by b181d3f07fd10152cf71035db9333dfa7395dd0a.

**Pull request closed without merging**
