### PR TITLE
IAP_method_getProducts

### PR DESCRIPTION
**Pull request by trash-max**

### CODE REVIEW

**Comment by trash-max** [comment]
Hi!

Changes:      tutorials/platform/android/android_in_app_purchases.rst

Replacing the DEPRECATED getSku method with getProducts.
The author of the module made changes, but did not specify them in
the documentation.

Now instead of signals:
sku_details_query_completed
sku_details_query_error

Need using:
product_details_query_completed
product_details_query_error

Now the purchase list is in:
purchase.products

Single item:
dictionary.put("sku", skus.get(0)); # Not available in plugin
Not avaible.

Oginal plugin code:
https://github.com/godotengine/godot-google-play-billing/blob/billing-v5/godot-google-play-billing/src/main/java/org/godotengine/godot/plugin/googleplaybilling/GodotGooglePlayBilling.java

**Comment by Foxomat** [comment]
please merge... I also stumbled upon this and it gave me quite a headache

**Comment by mhilbrunner** [comment]
cc @timoschwarzer, you seem to have previously worked on this, any input? :)

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I have reviewed these tentatively and from looking at the plugin/library, these changes seem goodt at a glance. I have no time to test them, but I'm going to merge these for now as they seem to be an improvement over the status quo. Still, reviews welcome!

Thanks for contributing and congrats on your first merged PR in this repository :)

**Pull request merged**
