### PR TITLE
Update images in tutorial "Scenes and nodes" to 2.0

### PR DESCRIPTION
**Pull request by flurick**
Solves #16

### CODE REVIEW

**Comment by StraToN** [comment]
Thanks a lot !
@akien-mga Should we remove old screenshots?

**Comment by akien-mga** [comment]
Thanks a lot, those screenshots are great.

Could you merge all commits into one to clean up the git history a bit?

To do so, you can run in your master branch:
```git rebase -i HEAD~7```

You should get an editor with a list of the last 7 commits (yours).
Replace "pick" by "fixup" for the last 6 commits, and save, that should merge them all into the first commit.

Then to be sure check the ``git log``, and if it looks good (one commit), you can force push your changes to the remote:
```git push -f```

Alternative you could also ```git rm``` the old images as @StraToN suggested (we don't support Godot < 1.0 anymore, so no need to keep those around). But I can also do it after merging this PR if need be :)

**Comment by akien-mga** [comment]
If the above seems like black magic to you, I can also do it myself, I know git can be daunting ;)

**Comment by akien-mga** [comment]
I've merged in your changes manually in this single commit: 7bb4816
(+ I removed the old screenshots)

**Pull request closed without merging**
