### PR TITLE
Update spatial material page for Godot 3.2

### PR DESCRIPTION
**Pull request by skyace65**
A new SpatialMaterial flag was added to the screenshot needed to be updated. its gone through png compression. The description for the flag was taken from the shading reference page.

### CODE REVIEW

**Comment by clayjohn** [comment]
Brief description already here. http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/spatial_shader.html#render-modes

I think there is a more detailed explanation in the PR adding this to the docs

**Comment by skyace65** [comment]
Thanks!

**Comment by BastiaanOlij** [comment]
Looks good to me :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
