### PR TITLE
Update images in "Your first 2D game - Coding the player" with wrong settings

### LINKED ISSUE #8078: Missing information in 2D tutorial for _ready
**Your Godot version:**
4.1.1

**Issue description:**
You tell the user:
_"The _ready() function is called when a node enters the scene tree, which is a good time to find the size of the game window:"_

Is this a new script?  Is _ready() called by something else?  Where does this code go?  Do I make it?  Extremely confusing.  Whenever you call a process of show code, please show a screenshot of the file/location and exactly what the name of the file is.  This documentation is difficult to follow.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html

### PR DESCRIPTION
**Pull request by Piralein**
- The "Attach Node Script" image didn't had the `Template` checkbox checked, which should be the default.
- "Player.gd" lowercase like the new default convention.
- The "speed" export didn't show the control buttons for numbers.

could close #8078 (if the answer is positive)

### CODE REVIEW

**Review by skyace65 — COMMENTED** [review]
The export variable and player_signals changes are incredibly minor, almost couldn't tell with player signals. But I'd still be ok with changing them. What did you use to make the .webp files? The images are all noticeably a bit bigger, though maybe that's just because we're dealing with KB.

**Comment by Piralein** [comment]
Redid the images.
I guess I shouldn't convert .png to .webp and just remake them if I export them in the wrong format. :unamused:

**Comment by skyace65** [comment]
The person who opened the issue replied to you and suggested a change to the text, do you want to make it?

**Comment by mhilbrunner** [comment]
Gentle bump :)

**Review by skyace65 — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for the update! Merged.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
