### PR TITLE
reformatted how to config Xcode text and added supplementary images

### PR DESCRIPTION
**Pull request by IndicaInkwell**

### CODE REVIEW

**Comment by IndicaInkwell** [comment]
Aw, shucks. I forgot to add a simple, but crucial step. Which is setting the header search paths.

I don't know what's the best way to do this (I'm not super familiar with github and git) so I'm going to close this request and create a new one.

**Comment by akien-mga** [comment]
You could have also pushed changes to the `patch` branch of your fork (the PR page shows that it was made from `IndicaInkwell:patch`), it would have updated the PR automatically.

**Comment by IndicaInkwell** [comment]
Oh, cool, that's good to know. With that in mind should I reopen this pull request after I push some changes to the patch branch?

**Comment by akien-mga** [comment]
That should work yeah :)

**Comment by IndicaInkwell** [comment]
Awesome! Thanks :D

**Comment by IndicaInkwell** [comment]
Okay, I added the missing step. I tested it and it now does what it advertises :)  Let me know if there's anything that should be changed.

**Comment by akien-mga** [comment]
Sorry for the delay, I had forgotten about this PR :)

**Pull request merged**
