### PR TITLE
Fix incorrect YouTube video link in Godot's design philosophy

### LINKED ISSUE #4450: Godot's design philosophy: wrong url for "Godot explained in 5 minutes" link
**Your Godot version:**
latest documentation

**Issue description:**
On the above page is

> Please watch [Godot explained in 5 minutes](https://youtu.be/4v3qge-3CqQ) if you're looking for an overview of the engine's features.

Following the link leads to [Discover Godot 3, the Free game engine - Open Source presentation](https://youtu.be/4v3qge-3CqQ), not [The Godot Game Engine Explained in 5 Minutes](https://youtu.be/KjX5llYZ5eQ).

**URL to the documentation page:**
https://docs.godotengine.org/en/latest/getting_started/introduction/godot_design_philosophy.html

### PR DESCRIPTION
**Pull request by Calinou**
This closes #4450.

### CODE REVIEW

**Comment by Feniks-Gaming** [comment]
I personally would remove link to a video all together. Biggest issue with youtube videos is their permanent state each week this video will be more and more outdated. If we want to do overview of Godot features we should make a doc page titled "Godot features overview" that way it can be kept up to date. 

It also removes any potential allegations of conflicts of interests where someone could question why we link to this channel over other channels having similar videos etc. 

I feel that docs should not rely on 3rd party to provide information if we want to explain something we should do it and only link to external sources in one section of "other online tutorials" and nowhere else.

**Comment by Riteo** [comment]
> I personally would remove link to a video all together. Biggest issue with youtube videos is their permanent state each week this video will be more and more outdated. If we want to do overview of Godot features we should make a doc page titled "Godot features overview" that way it can be kept up to date.

IMO nothing hits more than a video. A big wall of text would just scare people away. A video's pretty static, yes, but so are stable versions. The video can be updated on the release of Godot 4.0

> It also removes any potential allegations of conflicts of interests where someone could question why we link to this channel over other channels having similar videos etc.

This could be said also for any showcased game.

> I feel that docs should not rely on 3rd party to provide information if we want to explain something we should do it and only link to external sources in one section of "other online tutorials" and nowhere else.

The concept of "3rd party" is IMO pretty blurry. What exactly is a 3rd party? This is a community member contributing to Godot Engine's documentation(and literally who's in charge of the whole rewrite); by this logic everybody could be a third party. As long as the community is fine with it and lets it through, it's a valid contribution.

**Comment by Feniks-Gaming** [comment]
>IMO nothing hits more than a video. A big wall of text would just scare people away. A video's pretty static, yes, but so are stable versions. The video can be updated on the release of Godot 4.0

Issues with video are that it's less accessible than text. Yes it may be easier to watch but requires significantly better internet connection. I can check docs over 3g or 4g network. Watching video in many places of a world is hard. 

Other much more significant problem is that it gates the content behind language barrier. This video is only accessible to english speakers there is no way to translate it to other languages which is something we can do with docs. 

3rd is a permanence any inaccuracy, clarification or update can't be quickly fixed with simple pull request. There will be much more resistance in updating this video than there will be in updating the docs. As results users will wait longer for update if they need to. 

>What exactly is a 3rd party? This is a community member contributing to Godot Engine documentation(and literally who's in charge of the whole rewrite)

And you don't see how person in charge of a whole rewrite having link to his own channel and a video that was raising money for kickstarter is a conflict of interest? This is still far lesser problems as my first points raised above. Video is more accessible to English speakers but significantly more accessible to anyone else. Once you learn English it's easy to forget that vast portion of people do not speak it. 

>As long as the community is fine with it and lets it through, it's a valid contribution.

I am confused am I not a part of the community?  You say "if community is fine with it" as a response to literally member of community not being fine with it?

**Comment by Riteo** [comment]
> Issues with video are that it's less accessible than text. Yes it may be easier to watch but requires significantly better internet connection. I can check docs over 3g or 4g network. Watching video in many places of a world is hard.

I see what you mean, but I still think that a video, although possibly slightly outdated, it's always gonna give a very quick overview in a nice digestible manner, which is gonna attract more people.
Remember, this is one of the first things people will watch about Godot. It has to be short and digestible.

> Issues with video are that it's less accessible than text. Yes it may be easier to watch but requires significantly better internet connection. I can check docs over 3g or 4g network. Watching video in many places of a world is hard.

You got a point there.

> Other much more significant problem is that it gates the content behind language barrier. This video is only accessible to english speakers there is no way to translate it to other languages which is something we can do with docs.

Closed captions exist. Also, I'm pretty sure that we can change the video link across languages.

> 3rd is a permanence any inaccuracy, clarification or update can't be quickly fixed with simple pull request. There will be much more resistance in updating this video than there will be in updating the docs. As results users will wait longer for update if they need to.

This video should be a quite generic and quick overview of Godot Engine. I can't see many ways where it can be inaccurate.

> And you don't see how person in charge of a whole rewrite having link to his own channel and a video that was raising money for kickstarter is a conflict of interest?

I didn't see any mention of the kickstarter in that video, but I must admit that I skimmed over it. If the video doesn't talk about it, I can assure you that 99% of people aren't going to click on the channel, let alone go watch the kickstarter video or even pledging to it.

> I am confused am I not a part of the community? You say "if community is fine with it" as a response to literally member of community not being fine with it?

You're just one voice. That link inclusion was almost certainly added by a PR which had to ve reviewed by at least a bunch of people, with anybody having the possibility of discussing right away.

Anyways, I can see your point. If it isn't already the case, I think that a good compromise would be to put at the start of the features doc the video, with further down all details, constantly updated and fully translated.

**Comment by Calinou** [comment]
I'll merge this now since this is more a bug fix than an enhancement :slightly_smiling_face:

**Pull request merged**
