### PR TITLE
Mention firewall issues causing long project startup times in Troubleshooting

### PR DESCRIPTION
**Pull request by Calinou**
- See https://github.com/godotengine/godot/issues/80853.

### CODE REVIEW

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Is this not cherrypickable for 4.0?

**Comment by Calinou** [comment]
> Is this not cherrypickable for 4.0?

It should be cherry-pickable to 4.0 and even 3.x (the editor setting exists in 3.x with the same name) :slightly_smiling_face:

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
