### PR TITLE
Fix scrolling outside of content area

### LINKED ISSUE #9484: When my mouse isn't over the main content I can't scroll
**Your Godot version:**
4.2 or something

**Issue description:**
When I put my mouse on the side and scroll with mouse scroll wheel it doesn't work

firefox_4MyW0TKvNC

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #9484

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I can confirm this seems to work for me, having built it locally. Maybe someone else wants to have a look at well, cc @Calinou @Piralein @skyace65 if anyone of you got time before we cherrypick this to all branches :)

**Review by skyace65 — APPROVED** [review]
Just built it locally, scrolling outside the context area works for me too.

**Review by Piralein — APPROVED** [review]
note for cherry-pick: The problem is a side effect of #9015.

**Comment by mhilbrunner** [comment]
Thank you! Merged.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Comment by mhilbrunner** [comment]
Cherry-picked to 3.6 in https://github.com/godotengine/godot-docs/pull/9936.

**Pull request merged**
