### PR TITLE
Add dependency section to gdextension file docs

### PR DESCRIPTION
**Pull request by paddy-exe**
Continuation of https://github.com/godotengine/godot-docs/pull/9383
Fixes https://github.com/godotengine/godot-docs/issues/9462

also removes a double word

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged! Feedback by @dsnopek still appreciated, saw the review request too late, oops.

**Comment by paddy-exe** [comment]
@mhilbrunner No worries. I can patch it up very quickly if there is any feedback 👍🏻

**Comment by dsnopek** [comment]
This looks good to me!

The only note that I would add, is that the most common way to use `[dependencies]` is with a path of `""`, which means to copy the dependency into the same folder as the Godot executable, and so it'd be good to have an example of that, ie:

```
windows.debug = {
    "res://bin/libdependency.windows.template_debug.x86_64.dll" : "",
    "res://bin/libdependency.windows.template_debug.x86_32.dll" : ""
}
```

On MacOS, I think using the path `"Contents/Resources"` or `"Content/Frameworks/"` is common, but I'm not 100% sure about those.

In any case, I think we should try to include some paths that are actually used in the wild, in order to help folks figure out how to use this.

**Comment by YuriSizov** [comment]
Hey, @paddy-exe and @dsnopek! Am I missing something about these dependencies? When I looked into Godot codebase, I only see `OS_Android` using this data. `GDExtension::open_library` takes the info and extracts paths from it, puts it into `OS::GDExtensionData::library_dependencies`, and then `library_dependencies` is only accessed in `OS_Android::open_dynamic_library`.

If this is only implemented on Android, then this must be reflected in the documentation in two ways: an explicit note and all examples for other platforms must be removed. Or am I missing some indirect use?

PS. Well, export plugins system also extracts this information for its own use via `GDExtension::find_extension_dependencies`, but that doesn't seem to be related to loading GDExtension libraries.

**Comment by paddy-exe** [comment]
@YuriSizov I haven't looked at the implementation for specific platforms but I assure you I have tested it both on Linux and even more extensively on Mac to make sure it works. I am not aware if there are more specific requirements for loading on mobile platforms though.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Pull request merged**
