### PR TITLE
Backport docs reorganization and section rewrites to 3.4 branch

### PR DESCRIPTION
**Pull request by NathanLovato**
Following a discussion on the Godot docs chat, this PR ports changes regarding the reorganization of the `master` branch of the docs and rewritten sections compatible with Godot 3.

I copy-pasted the following directories as it was simpler and more reliable than cherry-picking dozens of commits:

- Getting started
- Community

The new Getting Started series is for the current stable version of Godot so it'll work well. And the community section contains all the contributing guidelines, and the updated ones have important things for contributors.

The other commits were all cherry-picked and I tried to resolve all conflicts properly.

The PR also backports some new scripting guides about some fundamental Godot concepts: overridable built-in methods, idle vs physics processing, etc.

----------

I kept the commits separate in case it could help to check things are fine during review. Please let me know if or when I should squash them.

-------------

⚠ Upon merging and updating the docs, someone will have to create redirects with Read the Docs. My next task is to work on a script to automate that using their API. It's not available yet.

-----------

Lastly, this PR removes tutorials that were removed in the latest branch of the docs following our content guidelines.

### CODE REVIEW

**Comment by NathanLovato** [comment]
I just addressed all errors after doing a fresh rebuild. In some cases I removed the links (pages that exist in master but not in 3.4) and in others I added references.

**Comment by mhilbrunner** [comment]
This looks good and should be fine, I gave everything a first look & view.
I'm going to build it locally and test a bit, as its a large change set - but seems good.

**Comment by mhilbrunner** [comment]
@Calinou @akien-mga @pycbouh I'd like some of you to give this a glance as well

**Comment by Calinou** [comment]
I took a cursory look at some pages such as the backport of the Your first 3D game tutorial, and it seems good to me.

**Review by akien-mga — APPROVED** [review]
Looks good to me from a (*very*) cursory look. This seems to be a thorough backport so I prefer not to spend too long second guessing it as it's hard to review due to its very nature (1250 files changed). Best is probably to merge, and see if we find any issues in the live instance.

**Comment by akien-mga** [comment]
The tutorial links in the class reference changed here should also be changed in Godot's `3.x` branch (and this can be cherry-picked for `3.4`) after this is merged.

**Comment by mhilbrunner** [comment]
> I think it's fine to keep the detailed history here, unless someone feels very strongly about it.

No, I think we should keep the commits.

Alright, thanks everyone for reviewing. I'll do a final pass later today or tomorrow and then press the big green button. :)

**Comment by mhilbrunner** [comment]
Okay, lets gooo.
Everybody run :P

**Comment by mhilbrunner** [comment]
Thanks for working on this!

**Comment by NathanLovato** [comment]
You're welcome! Now there'll be this before putting the changes into stable/: https://github.com/godotengine/godot-docs/pull/5414

**Pull request merged**
