### PR TITLE
Update to reflect issue #25535 in godot

### PR DESCRIPTION
**Pull request by creikey**

### CODE REVIEW

**Comment by merumelu** [comment]
This should be in a `.. note::` block (or maybe `.. attention::`) for better visiblity. http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions

**Comment by clayjohn** [comment]
I dont think its a good idea to add a note to the docs highlighting a bug in the current branch... docs should reflect intended behaviour. Also there is already a PR fixing this bug waiting to be merged.

**Comment by creikey** [comment]
@clayjohn Why is it a bad idea to add a note of a bug? 3.1 is already in feature lock, and so the PR won't be able to be put into effect for some time.

**Comment by akien-mga** [comment]
godotengine/godot#25535 will be fixed eventually, and likely backported to the 3.1 branch, so I don't think it should be documented either.

**Comment by creikey** [comment]
@akien-mga If it will be fixed and then backported to 3.1, then I agree, it should not be documented. Closing the issue.

**Pull request closed without merging**
