### PR TITLE
Improve learning_new_features.rst

### LINKED ISSUE #4429: "Learning with the community" mention "Scene Tree screenshot", mention "short video recording of the issue", what software to use
**Your Godot version:** This is about the latest docs.

**Issue description:**
I spend a lot of time replying to beginner questions on Reddit, and I regularly have to ask the OP to provide code samples, a screenshot of their scene tree and preferably a short video screen recording of the issue. Often these are necessary because the OP does not know yet how to properly describe their issue. Which results in a lot of pointless guesswork by those willing to provide help and asking again and again for the same things. It would be nice if I could point to a place in the documentation where "how to ask for help" is described and explained. 

Right now this section [here ](https://docs.godotengine.org/en/latest/getting_started/introduction/learning_new_features.html#learning-with-the-community)talks about screenshots, but screenshots of the "scene". This could easily misunderstood as the running scene, of which having a screenshot is often pretty useless. A **video of the running scene** however would be very useful to troubleshoot, and a **screenshot of the Scene Tree** is pretty much always a _necessity_ to provide good help without too much guesswork. Make "Scene Tree" a link to [this](https://docs.godotengine.org/en/latest/_images/key_concepts_scene_tree.png), in case that person has missed that part of the documentation or has not looked at the documentation at all yet (happens a lot); so that person has a visual indicator what to look for.

I also feel like "If there is code involved, share a code sample." should not be a formulated as conditional. Code is pretty much always involved. As someone trying to help, I would much rather have the chance to glance over the a code excerpt and find out that it is not the problem when reading the post, than asking for the code again and again because most beginners don't seem to think their code plays a role, while it usually always does. So does their Scene Tree structure.

When mentioning the "provide a short screen recording of the issue if possible" There could also be a link to free screen recording software like [OBS ](https://obsproject.com/)and [ScreenToGif](https://www.screentogif.com/).

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/latest/getting_started/introduction/learning_new_features.html#learning-with-the-community

### PR DESCRIPTION
**Pull request by NathanLovato**
Added more guidelines for when asking for support.

Closes #4429

### CODE REVIEW

**Comment by NathanLovato** [comment]
@golddotasksquestions may I ask you to take a look, see if those are the changes address your issue?

**Comment by NathanLovato** [comment]
Done!

**Review by Feniks-Gaming — APPROVED** [review]

**Comment by NathanLovato** [comment]
Thanks, merging for now.

**Comment by golddotasksquestions** [comment]
Thank you!

**Pull request merged**
