### PR TITLE
Minor language fixes to Spatial Material documentation

### PR DESCRIPTION
**Pull request by eluadyl**
Made minor changes to spatial_material.rst to fix some errors in language. Not sure what 'microsurfacetting' is so left it as is. Please review.

### CODE REVIEW

**Comment by cbscribe** [comment]
Since the only google hit for "microsurfacetting" is that doc, I suspect it's not a word! :)
I suspect they meant "microsurfacing".

**Comment by eluadyl** [comment]
That's what I suspect too but maybe they are coining a new term ;).

**Comment by cbscribe** [comment]
<hint>
You know, the class ref for SpatialMaterial is very bare:
http://docs.godotengine.org/en/latest/classes/class_spatialmaterial.html
</hint>

**Comment by eluadyl** [comment]
Microsufracing (previously 'microsufacetting') is used in the doc to describe a physical property of real world objects, the very small surface features which affect how light reacts with the object's surface. It's not a reference to a function in the SpatialMaterial class. I don't understand how the <hint>...</hint> is supposed to help me.

**Comment by NathanLovato** [comment]
Microsurface is a cg term, but I'd definitely recommend roughness, which is a lot more descriptive and popular. In the meantime, thanks for the fixes! merging now

**Pull request merged**
