### PR TITLE
Add Navigation overview

### PR DESCRIPTION
**Pull request by smix8**
Adds overview of all the navigation related nodes and objects in Godot and what they are primarily used for.

### CODE REVIEW

**Review by skyace65 — COMMENTED** [review]
I have the same issue with this PR as #6044. Information that's already covered on the 3D navigation page is being duplicated instead of improved.

In addition to that on a page like this it doesn't make sense to have separate 2D and 3D sections. As an example, Astar3D and Astar2D have the same use case for cell based gameplay and roughly the same description. This could be just one part for both Astar classes, and doing that for everything would significantly reduce the size of the page.

**Comment by Brandon-M-Hartman** [comment]
It's been 10 days - when is this going to be merged?

**Comment by YuriSizov** [comment]
Please be patient. It will be merged once it's reviewed.

**Comment by mhilbrunner** [comment]
Closing as superseded by https://github.com/godotengine/godot-docs/pull/6169.

**Pull request closed without merging**
