### PR TITLE
FPS Tutorial Part02-04 general phrase corrections

### PR DESCRIPTION
**Pull request by Socterean**
I remade the correction on the up to date fork of godot-docs. Also I left the commas in the first two dictionaries so they remain the same in the docs and in the zip archive

### CODE REVIEW

**Comment by TwistedTwigleg** [comment]
Looks great! Thanks Scoterean!

**Comment by Socterean** [comment]
No problem, I am following this tutorial to get used with Godot for my projects, and I figured out that it is easy to make some modifications if they where needed so all the community would have a better experience learning from it.

**Comment by Socterean** [comment]
I have also finished Part03 with some minor fixes at the audio variable names to work properly.

**Comment by Socterean** [comment]
I have finished Part04 with some minor corrections. Although I not changed them because I didn't wanted to do such major changes, in the first script are some issues with the joypad mappings, I have used a Playstation controller in Linux and the mappings are the same as they are for windows, using the given Inputs for joypad_vec doesn't work if you are using a PS controller in Linux. I had no XBOX controller to test with it so I don't know if they work as they are in the instructions

**Comment by TwistedTwigleg** [comment]
It looks great Socterean! Thanks for doing this!

> Although I have not changed them because I didn't wanted to do such major changes, in the first script for handling joypad imput, there are some issues with the joypad mappings, I have used a Playstation controller in Linux and the mappings are the same as they are for Windows, using the given Inputs for joypad_vec doesn't work if you are using a PS controller in Linux. I had no XBOX controller to test with it so I don't know if they work as they are in the instructions

Well, when I wrote the tutorial I only made the inputs for a Xbox controller because that is the only game controller I have. If you want, you can add a section/note explaining what the bindings are for Playstation controllers. You could add something like this:

`
.. note:: If you are using a Playstation controller, you need to change the bindings to: <insert bindings here>
`

Or however you want to do it. As I said above, I only have a Xbox controller, so that's why the bindings are set up for a Xbox controller. Feel free to add a section for Playstation controllers if you want! (Or not if you do not want to! Either way is fine with me.)

Thanks again for these changes/corrections!

**Comment by Socterean** [comment]
I have made some changes so the tutorial works for both the Xbox controller and the Playstation controller. However I have not managed to find a solution to include them in the same script so for now it works just with one of them or the other.

**Comment by mhilbrunner** [comment]
Thanks for your contribution! (Un)fortunately, we also had another PR to fix some typos in the FPS tutorial, so there are now some conflicts with yours. Can you fix the conflicts? :)

**Comment by Socterean** [comment]
Thank you for your appreciation, I have resolved the pending conflicts and I believe now the pull request is ready. I still have to add part05 and part06 of the tutorial but it will take me 2 or 3 days more to look into them following the tutorial and based on what I saw in part 03 and 04 there should be just minor fixes with no real impact over this tutorial so I can add them in another Pull Request

**Comment by mhilbrunner** [comment]
Thanks again; merged. Looking forward to your next PR!

**Comment by Socterean** [comment]
Thank you! I will try to do my best contributing to this awesome project.

**Pull request merged**
