### PR TITLE
Update navigation different actor types

### PR DESCRIPTION
**Pull request by smix8**
Updates navigation different actor types.

Godot 4.0 version of https://github.com/godotengine/godot-docs/pull/7557.

### CODE REVIEW

**Comment by Piralein** [comment]
Is this supposed to target the master branch?

**Comment by smix8** [comment]
> Is this supposed to target the master branch?

No, the Godot 4.0 branch. The Godot 4.1 version is https://github.com/godotengine/godot-docs/pull/7557.

**Comment by Piralein** [comment]
#7557 is also targeting master.
The current master branch is the 4.1 (technically 4.2 at this point), a change only for  4.0 needs to target the `4.0` branch.

**Comment by skyace65** [comment]
Piralein is right. I've merged the 4.1 version into the master branch. This PR needs to be changed to target the 4.0 branch.

**Comment by smix8** [comment]
Na forget this pr, the amount of change git wants me to do is horrendous, I am making a new pr.

**Pull request closed without merging**
