### PR TITLE
Update gdnative-cpp-example.rst

### PR DESCRIPTION
**Pull request by m4gr3d**
Add note to specify when to expect Godot to auto-reload newly added/removed properties.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@m4gr3d cool! thanks :)

@karroffel , what is your current take on the reloadable property? I've always fought with it because memory is allocated based on the class definition when the object is instantiated. If you recompile the DLL and load the new version there is always a risk the memory currently allocated and the data held within does not agree with the new structure.

**Comment by karroffel** [comment]
@BastiaanOlij *in theory* it should not be a problem since no allocations should actually persist the reload.

This should only happen when tool classes are uses, as the editor might hold objects then that have script instances attached to them that are managed by a GDNative library.

So for non-tool usage this should be safe, for tool scripts it should not be used.

**Comment by BastiaanOlij** [comment]
Hmm, I always make that mistake because ProcMesh is a tool class :)  (and there are some other reasons this is dangerous with VR interfaces because they get loaded at boot up, also for the editor). 

@m4gr3d you might want to rewrite your paragraph slightly to indicate the reloadable property can lead to issues with "toolclasses" as karroffel says

**Comment by m4gr3d** [comment]
@BastiaanOlij @karroffel Thanks for the info, I've updated the description accordingly.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
