### PR TITLE
Write intro to UI system and 2 step by step UI tutorials

### PR DESCRIPTION
**Pull request by NathanLovato**
This is meant as a replacement for the old ui intro tutorial (the one that shows how to turn a blue rectangle red on click). This is the first batch of content that covers:

- The basics and terminology of the UI system
- how to build a main menu step by step
- how to create a more elaborate GUI and reusable UI components with scene inheritance

Questions:
1. Where should I put demo files? Still a ZIP in the files folder?
2. I added an img/ folder in step_by_step, as we discussed @akien-mga. Is it okay or should I still use the root img/ folder?
3. Should the introduction to the UI system move to the features/gui section or stay here? Imo Godot's ui system is essential info as you'll use it for games, plugins and the editor is made with it. But at the same time this is a manual page that the step by step tutorials can link to. In any case, I think the step tuts should stay in the step_by_step section as all users and beginners need to know how to do UI.

Upcoming content:
- start and end demo projects for both existing tutorials
- step by step GUI programming tutorial
- step by step GUI programming demo

You're welcome to critique the current work. You can read it on [this repo](https://github.com/GDquest/godot-3-guides/tree/master/design-user-interface) until it lands in the official docs. @cbscribe and @groud already proofed and reviewed some of the content (thanks again :))

### CODE REVIEW

**Comment by groud** [comment]
Few comments: 
- It has been merged recently, but the Anchor menu has just been replaced by a "Layout" menu, that changes both margins and anchors. You can use the "anchors only" submenu for anchors only. Thus the "Full Rect and Fit Parent" option is now just called "Fill" (or "Wide" maybe ?)
- Maybe that could be good to mention that two workflows now co-exist: you can build GUI using either 
containers or directly using the anchor/margin system. (Here the tutorial uses the first one :) )

This is a really cool tutorial. Definitely a great job ! :D
Thanks!

**Comment by NathanLovato** [comment]
Thanks for the heads up @groud. I got a build from yesterday, but it seems the change wasn't there yet. As soon as I can get my hands on it and the interactive anchor, I'll update the pages.
Same for the 2 workflows. It's really interesting! But gotta try it first.

**Comment by NathanLovato** [comment]
Updated the PR - it's now ready to merge. It's complete, with the godot projects. It will need some extra paragraphs and fixes to a few pics due to recent changes to the UI system (anchor -> layout), but all of the content is still valid.
Includes the demos

@cbscribe and others already proofed the text. There might be some more typos etc. But for this, can we merge, so other contributors can file PRs directly?

**Comment by NathanLovato** [comment]
Got a **lot** of warnings to fix. Doing this now

**Comment by NathanLovato** [comment]
Done, fixed all warnings and added 2 missing pics. Good to merge now.

**Pull request merged**
