### PR TITLE
iOS export: update required options

### PR DESCRIPTION
**Pull request by Oktosha**
The exporter was updated and the number of required options
decreased. This commit updates the docs accordingly.

### CODE REVIEW

**Comment by Calinou** [comment]
Is this also relevant for 3.5, or only for 4.0?

**Comment by Oktosha** [comment]
> Is this also relevant for 3.5, or only for 4.0?

It's relevant for both 3.5 and 4.0 but not earlier versions.

**Comment by mhilbrunner** [comment]
cc @bruvzg @naithar

**Review by bruvzg — APPROVED** [review]
In both 3.5 and 4.0 loading screens and icons are now generated automatically if not set.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you! 🎉 And thanks for the review :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.6 and 3.5.

**Pull request merged**
