### PR TITLE
remove duplicate keyboard shortcut

### PR DESCRIPTION
**Pull request by tanchar**
- Complete Symbol was present twice
- Tested on a mac, and the correct shortcut is Ctrl + Space ; Cmd + Space is typically used to open the mac spotlight search

### CODE REVIEW

**Comment by pycbouh** [comment]
Good catch, it's <kbd>Ctrl + Space</kbd> on all platforms. There is also a *Clone Down* line wrongfully duplicated right next to this one. Do you mind correcting it as well? Should be <kbd>Ctrl + D</kbd> for PC and Linux and <kbd>Cmd + Shift + C</kbd> on macOS.

**Comment by tanchar** [comment]
> 
> 
> Good catch, it's Ctrl + Space on all platforms. There is also a _Clone Down_ line wrongfully duplicated right next to this one. Do you mind correcting it as well? Should be Ctrl + D for PC and Linux and Cmd + Shift + C on macOS.

Good point! Done 🙂

**Comment by pycbouh** [comment]
@tanchar Thanks! Please, make sure that vertical pipes are aligned here:

**Comment by tanchar** [comment]
@pycbouh Voilà, a git clone later. I think I hit the limits of the github online editor.

**Comment by mhilbrunner** [comment]
Good work, thanks and congrats on your first docs contribution! :)

**Pull request merged**
