### PR TITLE
Add note on enabling driver input in recording_with_microphone.rst to allow mic recording

### PR DESCRIPTION
**Pull request by Skyvastern**
I've written a note that tells user to enable the option `Audio -> Driver -> Enable Input` in `Project Settings`. This is disabled by **default** (in the example project provided in doc its enabled). So without this enabled in new projects, microphone recording won't work.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by Skyvastern** [comment]
> Thank you for your contribution!
> 
> You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).
> 
> If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

Sure, making the same commit in 4.2 branch!

**Comment by AThousandShips** [comment]
Please rebase your branch as per the instructions, or I can do it if you like

**Comment by Skyvastern** [comment]
> Please rebase your branch as per the instructions, or I can do it if you like

Yes you can do it 👍

**Review by skyace65 — COMMENTED** [review]
I'm not sure that adding this is helpful. This page already tells you that audio input needs to be enabled in project settings on line 15.

**Comment by Skyvastern** [comment]
> I'm not sure that adding this is helpful. This page already tells you that audio input needs to be enabled in project settings on line 15.

Oh yes I missed that. Thanks for pointing that out!

Before making the PR, I was going through their docs to implement microphone recording in my project. Though I had followed the instructions properly, somehow I missed that line mentioning to enable input in Project Settings. Because of that recording wasn't working for me until I saw the warning message in Godot iself telling me to enable input option in Project Settings.

However, I think that the original mention of enabling audio input can be a bit more explicit. I will do some modifications to my changes to make the overall instructions short and clear.

**Comment by Skyvastern** [comment]
@skyace65 I removed my previous addition, and made the already existing instruction a bit more explicit and clear. I made the statement a little more emphasized as earlier going through the docs I missed this key detail.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! For future reference please keep PRs to 1 commit, I've done a squash and merge for this one so it's fine but keep that in mind for the future. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request). Also congrats on your first merged PR!

**Pull request merged**
