### PR TITLE
Update Game Development Center name and topics in Tutorials

### PR DESCRIPTION
**Pull request by Calinou**

### CODE REVIEW

**Review by Feniks-Gaming — APPROVED** [review]
Looks good

**Comment by NathanLovato** [comment]
Thanks!

**Comment by NoFr1ends** [comment]
@NathanLovato Shouldn't this get cherry picked into 3.x?

**Comment by NathanLovato** [comment]
Most commit could, but none gets ported due to the lack of an active maintainer on the docs.

**Comment by Calinou** [comment]
Cherry-picked to the `3.3` and `3.2` branches.

**Pull request merged**
