### PR TITLE
Document addition of METALLIC to light() built-ins (pending #42548)

### PR DESCRIPTION
**Pull request by pezcode**
This PR adds changes required after https://github.com/godotengine/godot/pull/42548. See https://github.com/godotengine/godot-proposals/issues/1604 for more info.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Could you please ping me to merge it once the PR on the godot repository got merged? I'll merge it then.

**Comment by akien-mga** [comment]
The godot PR is merged, this one needs to be rebased since the relevant page was moved.

**Comment by pezcode** [comment]
@NathanLovato Rebased on top of master and ready to merge.

**Comment by NathanLovato** [comment]
Thanks!

**Pull request merged**
