### PR TITLE
Add concatenation to shader preprocessor

### PR DESCRIPTION
**Pull request by JohanAR**

### CODE REVIEW

**Comment by JohanAR** [comment]
For https://github.com/godotengine/godot/pull/74737 (not merged yet)

**Comment by bitsawer** [comment]
Now that https://github.com/godotengine/godot/pull/74737 has been merged, this PR can be updated too.

Looks good, but I would tweak the shader code example a bit. First, we can change it into a fully functional shader snippet. It's only a few lines more and users can actually copy paste and see that it works. Another is to remove `;` from the SAMPLE macro content so that users must place it everywhere the macro is used for consistency with other code. So the new code snippet would be like this:

```glsl
uniform sampler2D material0;

#define SAMPLE(N) vec4 tex##N = texture(material##N, UV)

void fragment() {
    SAMPLE(0);
    ALBEDO = tex0.rgb;
}
```

**Comment by JohanAR** [comment]
Thanks! Updated as suggested and rebased.

**Review by bitsawer — APPROVED** [review]
Tested locally without any problems, looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
