### PR TITLE
Update getting started 2D to 4.3

### LINKED ISSUE #9802: First 2D game: acessing group produces error, no mention of scene/global groups
**Your Godot version: 4.3**

**Acessing group produces error, no mention of scene/global groups**

**URL to the documentation page: https://docs.godotengine.org/en/stable/getting_started/first_2d_game/06.heads_up_display.html**

For me the grouping of the mobs and removal does not work. Everything else did work perfectly so far.
First of all, there now are scene groups and global groups, which are not mentioned in the tutorial.

I did everything like described, but when I test the game it crashes and I get an error

    0:00:07:0613 main.gd:30 @ _on_score_timer_timeout(): Node not found: "HUD" (relative to "/root/Main").
    <C++ Error> Method/function failed. Returning: nullptr
    <C++ Source> scene/main/node.cpp:1792 @ get_node()
    main.gd:30 @ _on_score_timer_timeout()

Which is strange, because it seems unreleated to the removal of the creeps.

When I comment out the line

     get_tree().call_group("mobs", "queue_free")

in `new_game()`, everything else works fine (except the removal of the creeps of course).

Both scene group and global group produce the same error.

### LINKED ISSUE #9803: First 2D game, looping audio not up to date
**Your Godot version: 4.3**

**Looping audio not up to date**

**[URL to the documentation page:](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html)**

The following paragraph in the section "Sound effects" is not up to date:
"All audio is automatically imported with the Loop setting disabled. If you want the music to loop seamlessly, click on the Stream file arrow, select Make Unique, then click on the Stream file and check the Loop box."

I don't know what the "Stream file arrow" is, there is only a circular arrow next to stream, which resets the file to empty.

Looping is now a checkbox under parameters.

### PR DESCRIPTION
**Pull request by Piralein**
Images:
- Update Project Settings images, because of new tab order
- Update Input Map images, because of new icons and action name reference
- Update Add Script Dialog image, because of color change
- Update Group images, because it was split into scene and global groups
~~- Update Signal connect image, because it gets added with type hints~~
- Added image to visualize the "make unique" step for the music resource

Code:
~~- Added return type to all functions, because they are added by default~~

Groups:
- Explained new workflow

closes #9802
closes #9803

### CODE REVIEW

**Comment by skyace65** [comment]
@Piralein given the discussions in RocketChat could you please remove the return types from this PR so the other fixes can get merged?

**Review by skyace65 — CHANGES_REQUESTED** [review]
player_signal_connection.webp needs to be updated. it still has the `-> void` in it. Other than that this PR looks good!

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.

**Pull request merged**
