### PR TITLE
Mention `@GlobalScope` can be omitted in Class reference

### PR DESCRIPTION
**Pull request by Mickeon**
Dipping my toes into modifying this document. I wanted to say more but for now this is a pretty noteworthy thing to mention.

### CODE REVIEW

**Comment by YuriSizov** [comment]
I wouldn't do that to avoid potential conflicts.

**Comment by AThousandShips** [comment]
Was this intended to be specific to 4.2? Otherwise it's the wrong branch

**Comment by Mickeon** [comment]
Oops. Nope, it should be on master.

**Comment by Mickeon** [comment]
Either way, I thought about it and I believe it is still worth mentioning. I tested having `@GlobalScope` excluded from the text, and it does look very nice but there are too many occasions where it's ambiguous (all of the Variant's `is_equal_approx()` methods.).

So, having control over when it appears is nice, I wouldn't discourage mentioning it because it makes a lot of descriptions (such as ones that talk about error constants) much more readable.

**Comment by YuriSizov** [comment]
> I wouldn't discourage mentioning it

So we agree on that point and this PR should be archived?

**Comment by Mickeon** [comment]
Filtering both negatives in the sentence I meant "I would encourage mentioning it".
It should be archived regardless because it's targeting the wrong branch. I'll try again another time, sorry for the inconvenience.

**Comment by YuriSizov** [comment]
> Filtering both negatives in the sentence I meant "I would encourage mentioning it".

So, again, we agree then? 🙃 Current version of the PR suggests that not mentioning it is okay, which I disagree with. But if you want to change it to actively encourage mentioning the global scope, then I support that.

**Pull request closed without merging**
