### PR TITLE
Add documentation for render mode fog_disabled

### PR DESCRIPTION
**Pull request by lemilonkh**
Adds documentation for the `render_mode fog_disabled` and material setting `Disable Fog` added in godotengine/godot#81286.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by AThousandShips** [comment]
You need to drop the two first commits you have, they are not part of this

**Review by clayjohn — APPROVED** [review]
Should be good to merge once the related PR is merged

**Comment by AThousandShips** [comment]
Could you please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by lemilonkh** [comment]
Done :+1:

**Comment by lemilonkh** [comment]
godotengine/godot#81286 has been merged, so this can probably be merged as well

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for contributing to Godot's docs, and congrats on your first merged PR to this repository!

**Pull request merged**
