### PR TITLE
added a guide to configure kdevelop as an IDE

### PR DESCRIPTION
**Pull request by lordadamson**

### CODE REVIEW

**Comment by StraToN** [comment]
Seems almost perfect to me. 
I see one internal link that may not work correctly (line 5, `compiled <_compiling.rst>`_).
I merge though, we'll be able to correct easily with GH's interface :)

**Comment by lordadamson** [comment]
I found reST quite painful to deal with.

**Comment by akien-mga** [comment]
Yeah it takes some getting used to :)

**Comment by akien-mga** [comment]
I've done some proofreading and adjustments in 8f38813 and d509b37. (damn this referencing system is hard to get right without checking other files :P)

**Pull request merged**
