### PR TITLE
Clarifications and grammar fixes for scripting_continued tutorial

### PR DESCRIPTION
**Pull request by bitbutter**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
This looks good. I found nothing, but I'll leave it open for a few days longer in case @cbscribe or @NathanLovato want to chime in :)

Thanks for the ton of work you're doing!

**Comment by mhilbrunner** [comment]
Also, you can squash your commits into one: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by akien-mga** [comment]
Squashed it myself, wrapped long lines and fixed missing inline code formatting and style issues.

**Comment by akien-mga** [comment]
The PR is configured not to allow maintainer edits, so I'll push it directly to master. Thanks for the contribution, the changes are good :)

Merged manually as d2d51044.

**Pull request closed without merging**
