### PR TITLE
Update unity_to_godot.rst

### PR DESCRIPTION
**Pull request by aliakseikalosha**
change description to be more understandable by Unity Developers.

### CODE REVIEW

**Comment by pycbouh** [comment]
I think the idea was to remove the page completely as it is unfeasible to keep up with other engines, their changelogs and relevant features and terminology.

**Comment by aliakseikalosha** [comment]
For me as a Unity developer who don't know how to start with this game engine in was useful, but some parts was written more from perspective of Godot developer rather than a Unity one.  So I tried to make it more understandable for Unity developers.

Without such pages less people, coming from Unity, would know how to start or how to use Godot's Nodes.

**Comment by pycbouh** [comment]
> Without such pages less people, coming from Unity, would know how to start or how to use Godot's Nodes.

Up-to-date video tutorials are better for that purpose.

> I found it here on docs page clicked on edit button and tried to improve upon it.

Yes, I know. I'm just saying that we probably aren't looking into improving it right now as we likely won't have this page in the future. The fact that you had to come and edit it to address several changes in Unity's featureset and terminology is the exact reason why those pages are less useful than they appear to be at a first glance.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-docs/pull/3920 for context about removing the page.

**Comment by aliakseikalosha** [comment]
> Up-to-date video tutorials are better for that purpose.
I tried to watch tutorial but they are for complete beginners. They teach how to program and create very simple game/application with as low entry level as possible . And if you now such you could add a link to the page it would be very useful.

> The fact that you had to come and edit it to address several changes in Unity's featureset and terminology is the exact reason why such pages are less useful than they appear to be at a first glance.

Prefab is a word in unity  from a start, I specially didn't talk much about nested prefab because not so much people use it. So what terminology I used are new?

**Comment by aliakseikalosha** [comment]
> 
> 
> See #3920 for context about removing the page. The page was already removed in the `master` branch, but it was kept in the `stable` branch for posterity.

As I has answer before :
> I found it here  [on docs page](https://docs.godotengine.org/en/stable/getting_started/editor/unity_to_godot.html) clicked on edit button and tried to improve upon it.

**Comment by mhilbrunner** [comment]
Hey! Thanks for your work on this, and thanks for contributing to the docs.

As discussed above, the current/future docs don't keep this page around anymore and I don't see this PR adding enough actionable information for developers to cherrypick and update the old docs.

**Pull request closed without merging**
