### PR TITLE
Update docs regarding current Nuget workflow

### PR DESCRIPTION
**Pull request by jasonswearingen**
highlighting proper workflow as per my discovery here: https://github.com/godotengine/godot/issues/34803#issuecomment-570752688

basically it's super easy for c# devs to get the nuget workflow wrong.   this clarifies problems i ran into.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Pinging @neikeq

**Comment by Calinou** [comment]
@neikeq Is the workaround above still required in the current `master` branch? If so, I'll merge this.

**Comment by neikeq** [comment]
Yes, this is still requires. It will no longer be needed soon though (I expect to get this solved in no more than two months), so it won't be needed in the 4.0 docs. Older versions will still need it.

**Comment by Calinou** [comment]
Thanks! I applied some formatting changes manually as reStructuredText doesn't support nested formatting (i.e. `**some text ``and code`` and more text**` won't work).

**Pull request merged**
