### PR TITLE
Improve the Docs writing guidelines page

### PR DESCRIPTION
**Pull request by Calinou**
This also integrates keyboard shortcut recommendations as outlined in #3257.

cc @pycbouh

### CODE REVIEW

**Comment by clayjohn** [comment]
Looks good to me!

**Comment by pycbouh** [comment]
Looks good!

Should we mention, maybe, that for consistency you should not spell out "Control" and "Command"? Also, the formatting for the shortcut itself worth mentioning?

**Comment by Calinou** [comment]
@pycbouh Done.

**Comment by pycbouh** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
