### PR TITLE
Update some screenshots in the Scripting section for Godot 4

### PR DESCRIPTION
**Pull request by gomaproi**
Some of the screenshots were dated, so I decided to retake them for coherency with the latest Godot version.
All of the screenshots were taken on Windows 11 with a display scale of 125% for better readability. I also tweaked some node names (e.g. changed Tween to AnimationPlayer and Sprite to Sprite2D).

I only did a quick look at the edits, so let me know of any errors!
Edit: Made a build of the docs and it seems to be working properly.

Below are some articles that I had to adapt a bit to make it up-to-date:
<details>
<summary>Expand me (screenshot examples)</summary>

Because the Tween node no longer exists, I had to change the example below:

Added a note to explain where the GDScript section is:

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thanks for contributing, especially on something as time consuming as taking screenshots! If you can, would be helpful to convert these to WebP while you're at it, as we decided to move from PNG to WebP for new images.

**Comment by gomaproi** [comment]
Done! I hope I properly changed the file formats in the articles.

**Comment by gomaproi** [comment]
Just finished making some tweaks, I think that it's ready to go.
I found some outdated information in the articles (such as one of them affirming that typed GDScript has yet to be optimized), but that's something for another pull request.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
