### PR TITLE
Introduction - Wrong number

### PR DESCRIPTION
**Pull request by denicolas**
[About » Introduction](https://docs.godotengine.org/en/stable/about/introduction.html)

"This documentation is organized in five sections"
should be:
"This documentation is organized in six sections"

### CODE REVIEW

**Comment by mhilbrunner** [comment]
I'd maybe consider removing the number althogether, not sure it's that helpful and its easy to miss to update it if anything changes, what do you think?

**Comment by denicolas** [comment]
> I'd maybe consider removing the number althogether, not sure it's that helpful and its easy to miss to update it if anything changes, what do you think?

Yes, I agree. So maybe the number could be just replaced with "several":
"This documentation is organized in several sections"

**Comment by mhilbrunner** [comment]
That sounds good to me :)

**Comment by YuriSizov** [comment]
Bump :)

**Comment by YuriSizov** [comment]
Nevermind, superseded by https://github.com/godotengine/godot-docs/pull/6572 because I was editing that file anyway. Thanks for your contribution nonetheless :)

**Pull request closed without merging**
