### PR TITLE
Add a Tween cheatsheet image

### PR DESCRIPTION
**Pull request by Calinou**
Taken from https://github.com/wandomPewlin/godotTweeningCheatSheet with the author's permission. Lossless PNG optimization was applied as usual.

The image isn't referenced in this repository directly, but will be referenced in the Tween class reference.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Yay for having a visual!

But for me these are kind of hard to visualize, or is that just me? Hard to get a feel for the different behaviours if I'm looking for a certain bounce for my game.

**Comment by lentsius-bark** [comment]
I love these, they work very well for me actually. One thing I'd add to the visual is the enum value of the tween.

**Comment by mhilbrunner** [comment]
Probably just me then :) Do we want the Godot version embedded in the image? Seems like an unnecessary maintenance burden for an area where the content hopefully doesn't change as often as Godots version number.

**Comment by Calinou** [comment]
@mhilbrunner I think it's better to display the version number the cheatsheet was last updated at. Think more of it as "this cheatsheet is known to be good for Godot 3.2".

See #3390 where people have complained about outdated documentation not explicitly claiming it's outdated.

**Comment by mhilbrunner** [comment]
Sounds reasonable, yes. :)

**Comment by mhilbrunner** [comment]
Thank you!

**Pull request merged**
