### PR TITLE
Add a section to size_and_anchors for centering a control in its parent

### PR DESCRIPTION
**Pull request by mitchcurtis**
Perhaps the most common task possible has no documentation on this page.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
@mhilbrunner @clayjohn is there a way I can add you guys as reviewers?

By the way, not sure if the title syntax is correct, as https://docs.godotengine.org/en/3.1/community/contributing/documentation_guidelines.html#titles doesn't mention anything about sub-sections.

**Comment by clayjohn** [comment]
No need to be added as reviewers. Tagging is enough :)

**Comment by mhilbrunner** [comment]
Looks good! Can you change the underline of the main title (**Size and anchors**) to use `===`?

Then your added title should be recognized as a subtitle.

Compare: https://raw.githubusercontent.com/godotengine/godot-docs/32f64fff43b8b59bfb3b2cea9e18293e37c89b4d/tutorials/gui/custom_gui_controls.rst

**Comment by mhilbrunner** [comment]
@mitchcurtis Awesome, thanks! Merged.

Some notes just in case: when you update a PR, feel free to leave a comment like "Fixed" as that seems to trigger notifications for people watching the PR, whereas updating the commits does not :)

And if you get no response for a few days, feel free to ping the reviewers again with @ - sometimes a PR or issue slips trough the cracks.

Aaanyway, thanks for another contribution :)

**Comment by mitchcurtis** [comment]
> Some notes just in case: when you update a PR, feel free to leave a comment like "Fixed" as that seems to trigger notifications for people watching the PR, whereas updating the commits does not :)
> 
> And if you get no response for a few days, feel free to ping the reviewers again with @ - sometimes a PR or issue slips trough the cracks.

Thanks, will do.

**Pull request merged**
