### PR TITLE
Improve clarity of 2d tutorial section

### PR DESCRIPTION
**Pull request by jamesplease**
This moves the note about the unit of time closer to where they are actually used.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by AThousandShips** [comment]
Please see the instructions, you need to rebase your branch :)

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9647.

**Pull request merged**
