### PR TITLE
Step by Step - Instancing 4.1 update

### PR DESCRIPTION
**Pull request by MeLight**
I followed the Getting Started - Step by Step - Instancing tutorial with Godot v4.1 today, and it looks up to date, except for a minor issue with the viewport not switching to 2D automatically - added a note and an image for that,

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

Please convert the image to the `.webp` format.
you can read more about it in the [Doc image guidelines](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion)

**Comment by MeLight** [comment]
@AThousandShips done

**Review by skyace65 — APPROVED** [review]

**Comment by BrieYRen** [comment]
Also followed that chapter today. It seems up to date. The only thing is that when importing the zip file, a warning pop up saying it's for Godot 4.0, but if you ignore it and import it anyway, everything works fine.

**Comment by skyace65** [comment]
Thanks! Congrats on your first merged PR!

**Pull request merged**
