### PR TITLE
Replaced all instances of "hard drive" with "local storage"

### PR DESCRIPTION
**Pull request by AV77**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Whats the motivation for this? IMO, "Local Storage" is heavily associated with browser technology, compare:
- https://www.google.com/search?q=hard+drive
- https://www.google.com/search?q=local+storage

**Comment by AV77** [comment]
This was to be more inclusive of other storage devices like SSD. Although you'd be right in saying that I'm heavily biased, due to my years of web dev work...

**Comment by mhilbrunner** [comment]
No, I agree "HDD" / "hard drive" is a bit of an outdated term. I'd still want to avoid confusion with *Local Storage* as a specific technology.

What do you think about replacing it with *local drive*? :)

**Comment by AV77** [comment]
Thanks for the suggestion! 'Local drive' sounds like a great alternative. I'll make the appropriate changes.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for contributing! Merged.

**Pull request merged**
