### PR TITLE
Add script class docs

### PR DESCRIPTION
**Pull request by willnationsdev**
Pending godotengine/godot #20561.

This adds some minor docs to make clear how to use script classes in GDScript and NativeScript for Godot 3.1.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Good thanks! Some minor typos and diffs with the guidelines, merging and proofing for you

**Comment by willnationsdev** [comment]
Lol, wait, I'm confused. Was I supposed to update it with some feedback from you or something? My phone app (I'm traveling now) says you already merged it, haha.

**Comment by NathanLovato** [comment]
Just gimme a few more moments, I want to take a screenshot of a node type with its icon

**Comment by NathanLovato** [comment]
In short: you write mostly in passive voice, and you need to split and simplify your sentences. https://godot.readthedocs.io/en/latest/community/contributing/docs_writing_guidelines.html

**Comment by NathanLovato** [comment]
Another writing tip: when you use parens in the middle of a sentence, in tech writing, 99% of the time you should move it down as a separate note or make it its own sentence.
I'll link to the proof commit when it's done

**Comment by NathanLovato** [comment]
You can see the changes here. Also moved the image, it was in the wrong folder. Make sure you build the docs with the html target when you write on it, it'll print out errors if file paths are wrong

https://github.com/godotengine/godot-docs/commit/313b5becd29ca660768bf51a935e0afd9646b3a8

**Comment by willnationsdev** [comment]
lol, what's pathetic is I already was splitting up my statements into smaller sentences. I think I gotta use that Hamilton thing when writing any docs. XD Thanks for the feedback.

**Comment by willnationsdev** [comment]
@NathanLovato Oh, in the diff you made, in the "Load character.gd and create a new node instance from it" example, you load a Character script and then call `.instance()` on it. Should be `.new()`.

**Pull request merged**
