### PR TITLE
Begin to fix terminology and explanations

### PR DESCRIPTION
**Pull request by sobotka**
Fix some terminology and work towards a
more appropriate explanation of the process.

### CODE REVIEW

**Comment by clayjohn** [comment]
PRs should be made against the Master branch rather than the 3.1 branch unless they only apply to 3.1. 
Can you close and reopen this against the Master branch?

**Comment by sobotka** [comment]
Sort of did this on a whim. Is there a way to rebase via the UI against an alternative branch / commit?

**Comment by clayjohn** [comment]
You seem to have made your changes against master. You just need to open a new PR and select master as your base instead of 3.1.

**Comment by sobotka** [comment]
Updated against master. Changing via this PR resulted in conflicts, so
a new PR was made.

https://github.com/godotengine/godot-docs/pull/2682

**Pull request closed without merging**
