### PR TITLE
Added tabs for multiple programming languages

### PR DESCRIPTION
**Pull request by djrm**
allows this
screenshot from 2017-08-31 23-57-27

### CODE REVIEW

**Comment by akien-mga** [comment]
Awesome! For the reference, that's using this extension: https://github.com/djungelorm/sphinx-tabs

**Comment by akien-mga** [comment]
BTW, it looks like we might be able to rely on pip to install the extension, and thus not need to bundle it ourselves: http://docs.readthedocs.io/en/latest/faq.html?highlight=requirements.txt#my-project-isn-t-building-with-autodoc
But for that time being, what works works :)

**Comment by reduz** [comment]
This is great, did you check that we can use an image for visual script?

**Comment by akien-mga** [comment]
> This is great, did you check that we can use an image for visual script?

Yes, check the example here (scroll down): http://docs.godotengine.org/en/latest/learning/step_by_step/scripting.html#handling-a-signal

**Comment by neikeq** [comment]
Would be nice if we could have something like this for the class reference as well. Not idea what would be the best way to identify `[code]` blocks for translating them though.

**Comment by akien-mga** [comment]
We can easily parse the XML and output the correct reST markup to use that extension, but indeed we need to decide on how we want to implement code examples in the classref. The current `[codeblock]` is a hack and not very scalable.

**Comment by djrm** [comment]
@akien-mga i could not make it wotk with pip, maybe because im declaring ./extensions as extensions folder, in order to have the gdscript parser.

**Comment by hpvb** [comment]
I think you need [CDATA] blocks if you want to allow the forbidden characters in XML at all though...

**Pull request merged**
