### PR TITLE
"Scenes and nodes" clarification

### PR DESCRIPTION
**Pull request by brandondc741**
As a first time Godot user going through this tutorial, some sections were unclear. Added context and clarity to the slightly confusing sections

### CODE REVIEW

**Comment by pycbouh** [comment]
Note that the Step by step series is being completely rewritten in #4325. Your PR is likely to be closed, but you should review the changes in #4325 and give your feedback. 🙂

**Comment by brandondc741** [comment]
@pycbouh Thanks for the heads up! I'll take a look

**Review by Feniks-Gaming — CHANGES_REQUESTED** [review]
You are mixing 2nd and 1st person here. 

At times is "you click" then "we have" etc. Stick to one person 

"Now click button to create **your** first label" instead of "Now click button to create **our** first label"

Reading text like this is confusing especially for non native speakers.

**Comment by NathanLovato** [comment]
Yup, this page has gotten a rewrite in #4325 which supersedes this PR. Thanks for the contribution regardless, always appreciated.

**Pull request closed without merging**
