### PR TITLE
Fix typo (copy-paste) in gui_using_fonts.rst

### PR DESCRIPTION
**Pull request by The-oldone**
Edited the fourth option to accurately represent which option it is, it previously replicated the third option

### CODE REVIEW

**Review by tetrapod00 — APPROVED** [review]

**Comment by tetrapod00** [comment]
Thanks!

FYI you might want to start using branches for your PRs rather than your master branch

**Comment by The-oldone** [comment]
sure, I will try and do that, just to confirm however, do you mean making a branch of the master, making the changes, then merging it back to master and then opening a pull request or making the changes, and opening a pull request for that branch directly to this repository's master so that the master branch of my repository doesn't get outdated?

**Comment by tetrapod00** [comment]
The second option you mentioned. In your fork, make a new branch (from master) just for whatever change you're making. Then make the PR from that branch to this repository's master. The message shown at the top of the created pull request will look something like "The-oldone wants to merge 1 commit into `godotengine:master` from `The-oldone:branch-just-for-pr`" rather than "The-oldone wants to merge 1 commit into `godotengine:master` from `The-oldone:master`"

**Comment by The-oldone** [comment]
Aight thank you, will do

**Pull request merged**
