### PR TITLE
Install tools required by `format.sh` on GitHub Actions

### PR DESCRIPTION
**Pull request by Calinou**
The script would silently fail otherwise. Thanks to @aaronfranke for catching it :slightly_smiling_face:

### CODE REVIEW

**Comment by akien-mga** [comment]
`format.sh` should likely be made to error out properly if those tools are missing?

**Comment by aaronfranke** [comment]
Perhaps something like this, above the "Loops" comment:

```bash
if ! type dos2unix; then
    echo "Error: dos2unix is not installed."
    exit 2
fi
if ! type recode; then
    echo "Error: recode is not installed."
    exit 3
fi
```

**Comment by akien-mga** [comment]
But shouldn't the script already exit with a non-zero exit code when trying to run a command that doesn't exist in PATH?

**Comment by aaronfranke** [comment]
Just tested it, when running a command that doesn't exist, the script exits with `0`.

**Comment by akien-mga** [comment]
> Just tested it, when running a command that doesn't exist, the script doesn't error and proceeds to exit with `0`.

There's an issue with the way the script is called then. It should return non `0`:
```
$ cat test.sh 
#!/bin/sh

cmd_that_doesnt_exist

$ sh test.sh 
test.sh: line 3: cmd_that_doesnt_exist: command not found

$ echo $?
127
```

But this isn't blocking for merging this PR anyway.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
