### PR TITLE
Add xrandr to dependency list for x11 compilation

### PR DESCRIPTION
**Pull request by Hinsbart**
TODO: list package name for Mageia

### CODE REVIEW

**Comment by vnen** [comment]
Almost closes #174 😄.

I don't know Mageia but for the logic it might be `pkgconfig(xrandr)`.

**Comment by Hinsbart** [comment]
Might be, but I'm not sure either :D

**Comment by neikeq** [comment]
It's `libxrandr-dev` on Ubuntu, is it not?

**Comment by vnen** [comment]
@neikeq yes, it is.

**Comment by Hinsbart** [comment]
Right

**Comment by akien-mga** [comment]
Yeah `pkgconfig(xrandr)` would work for Mageia (like on any proper RPM-based distro: https://www.rpmfind.net/linux/rpm2html/search.php?query=pkgconfig%28xrandr%29)

**Comment by akien-mga** [comment]
Merged and added for Mageia too: 282b1b7

**Pull request merged**
