### PR TITLE
Update key_concepts_overview.rst

### PR DESCRIPTION
**Pull request by VictorDev200**
Changing 'Character' to 'Player'

### CODE REVIEW

**Comment by VictorDev200** [comment]
@AThousandShips, Hello. I found another "Character" word here https://github.com/godotengine/godot-docs/edit/master/getting_started/step_by_step/nodes_and_scenes.rst

But I got a question, in that scenario, they are using CharacterBody2D node, and talking multiple times about "characters", Is it not better to replace the image with Character? because a Player using CharacterBody2D, may be confusing? or is better to replace Character with Player

**Review by Piralein — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks and congrats on your first merged contribution to Godot's docs! 🎉

**Comment by VictorDev200** [comment]
@mhilbrunner Thanks! i will try to help the max i can 😃

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
