### PR TITLE
Add 'bitbrain' as a tutorial creator

### PR DESCRIPTION
**Pull request by bitbrain**
[thumbnail](https://www.youtube.com/watch?v=Ox1kMM0qcTk)

I recently started doing Youtube videos and launched a new tutorial series on Godot! I am still a small channel but hope that the quality of my videos speaks for itself.

### CODE REVIEW

**Comment by pycbouh** [comment]
I'm not sure if we have any strict rules about who to add to this list, but the list is big and you've also submitted your channel to a much more relaxed Awesome Godot repository (godotengine/awesome-godot#157). So maybe we should add it there instead.

**Comment by mhilbrunner** [comment]
I watched a few of the videos - good content, hope you continue :)

With that said, there are currently only 4 videos in your Godot tutorial playlist, with the latest one being 3 months old at this point. I'm going to close this for now - maybe we need to come up with guidelines for this page, or discuss whether it's still needed at this point at all.

**Comment by bitbrain** [comment]
@mhilbrunner @YuriSizov looks like all tutorial links were removed as part of https://github.com/godotengine/awesome-godot/commit/10b678e7d4cff51c14fc7746e2cc4e749e190a59 but mine was not included it seems: https://docs.godotengine.org/en/latest/community/tutorials.html

Can I re-open this PR then?

**Comment by YuriSizov** [comment]
I don't mind.

**Comment by bitbrain** [comment]
This is ready to go!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged, thanks!

**Pull request merged**
