### PR TITLE
Give input event flow graph a background to make it visible on dark theme

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Black text combined with dark background doesn't fit well, this change adds an outline so it becomes visible.

### CODE REVIEW

**Comment by DeeJayLSP** [comment]
Old and new images for comparison

Old image

New image

**Comment by Calinou** [comment]
I think it's better to add a white background to those images instead.

**Comment by DeeJayLSP** [comment]
Image with BG

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
