### PR TITLE
Fix incorrect explanation of successful evaluation in Evaluating expressions

### PR DESCRIPTION
**Pull request by itsadrago**
Fixed incorrect explanation of successful evaluation for a given example

### CODE REVIEW

**Comment by itsadrago** [comment]
Wasn't sure if I was supposed to change the PR title too. Let me know if that's desired

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by itsadrago** [comment]
> Thanks! Congratulations for your first merged pull request 🎉

Woohoo!

**Comment by Calinou** [comment]
This can't be cherry-picked as the Evaluating expressions page wasn't backported to 3.4 and 3.3. I'll create a pull request to backport the page to 3.4 at least (its information is valid for 3.3 too).

**Pull request merged**
