### PR TITLE
Clarify where sound files are

### LINKED ISSUE #8040: Missing download link for the sound files for the "Your first 2D game" tutorial.
**Your Godot version:**
Version 4.1

**Issue description:**
Missing download link for the sound files mentioned in: "Your first 2D game" -> "Finishing up" -> "Sound effects". The zip file with the art assets at the beginning of the tutorial does not include sound files.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html

### PR DESCRIPTION
**Pull request by skyace65**
Closes #8040. There isn't a folder named "assets" the sound clips are in one named "art."

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Should this not be `your game's art folder`? Maybe even highlighting the **art** so it is clear it is the directory name. Otherwise LGTM.

**Comment by skyace65** [comment]
Fixed, not sure what's going on with CI now though

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I think it was just a temporary hiccup, I've re-run CI and it succeeded now. Thanks, merged :)

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1.

**Pull request merged**
