### PR TITLE
Tileset custom metadata correction

### PR DESCRIPTION
**Pull request by EastToastLiving**
In summary, the tileset tutorial page indicates that custom metadata for the tiles does not show up in editor. On my local build of v4.3 this is not the case. 

More infomation can be foind in ticket:
[Improper Documentation for Custom Metadata on Tilesets #9857](https://github.com/godotengine/godot-docs/issues/9857)

Please let me know (through the ticket likely) if more information is needed or I am mistaken. Thank you!

### CODE REVIEW

**Comment by KoBeWi** [comment]
This was a bug fixed in https://github.com/godotengine/godot/pull/92322

**Comment by EastToastLiving** [comment]
> The commits needs to be [squashed together](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase). Also, I assume you removed the image because it's not used?
> 
> Besides that, the change looks good to me. Thanks for contributing!

I will work on squashing it now.

As for the image, I did not remove it but rather I replaced it with an alternate image under the same name properly showing the depiction of custom metadata in the inspector.

**Comment by EastToastLiving** [comment]
The squash should be complete, please let me know if I missed anything else.

Thank you all for the help and patience with this ticket!

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR! In the future you don't need to do lossy compression on webp images, lossless is fine. It's a bit noticeable on this one but not terrible so I've merged it.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.3 in https://github.com/godotengine/godot-docs/pull/10038.

**Pull request merged**
