### PR TITLE
added godot3 editor settings table

### PR DESCRIPTION
**Pull request by ZX-WT**
Table for the editor settings, updated from the file in #395. I am surprised that this one has no problem to preview it on github :). Next thing is to do is fill in the blanks.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
I'm not sure adding version information at the beginning is a good idea. Looks outdated quickly even if nothing changed, and has to be kept up to date while the information is there on GitHub anyway. IMO, this is what a VCS is for.

Opinions? Thanks for taking the time by the way!

**Comment by ZX-WT** [comment]
I agree with you, I just keep it because it was in the original file, :P,  I will go and delete it. It would be great if other people can fill in the table as well, there are quite a lot of info to input. :)

**Comment by pwab** [comment]
@mhilbrunner 
> I'm not sure adding version information at the beginning is a good idea. Looks outdated quickly even if nothing changed, and has to be kept up to date while the information is there on GitHub anyway. IMO, this is what a VCS is for.

As I was the original author of the file I can tell you why it was there in the first place:
I created a gist for these files (editor and project settings) and wanted to know when I touched the file last time. At that time I didn't know that gists could be updated  😄 

So you are totally right - this should not be included.

**Comment by mhilbrunner** [comment]
Closing this for now, as it was discussed and the only sane way to do this is by automatically parsing the data and adding descriptions to avoid having to keep the list up to date in multiple places; this would be too much of a burden for contributors. Thank you for taking the time and getting the ball rolling on this :)

We will probably use this as inspiration for the script. See discussion here: https://github.com/godotengine/godot-docs/issues/395.

**Pull request closed without merging**
