### PR TITLE
Renamed fixed_process with physics_process

### PR DESCRIPTION
**Pull request by AndreaCatania**
Related to this https://github.com/godotengine/godot/pull/11659

### CODE REVIEW

**Comment by NathanLovato** [comment]
Hey there. You shouldn't modify anything in the classes/ folder: it's generated from the godot engine master repo. Could you drop the changes, and rebase/fix merge conflicts? Just comment when you're done or @ mention me and I'll merge asap.

**Comment by AndreaCatania** [comment]
@NathanLovato Thanks for response! I've dropped all changes in the \classes directory and I'have fixed all conflict. I don't know if I need to sqash these commits together because if I execute `git rebase -i HEAD~2` it give me the list of all commits and not only the last two as I'm expecting.
So what I've to do?

**Comment by NathanLovato** [comment]
Did you rebase with this repo's master?
`git pull --rebase upstream master` (provided you defined the upstream repo)
Your commit should be the last 2 in this case. Worst case scenario, you can delete commit 
7f745f1 and modify 150d90a (see https://stackoverflow.com/questions/1186535/how-to-modify-a-specified-commit-in-git). There's also a trailing space in the second commit.

**Comment by AndreaCatania** [comment]
I didn't close it, what happen?

**Comment by NathanLovato** [comment]
No idea, did you modify the branch or the repo in any way?

**Comment by NathanLovato** [comment]
Go ahead and open a new PR then, as long as you didn't lose your work, it shouldn't take long.

**Comment by AndreaCatania** [comment]
it was what I did, check this please https://github.com/godotengine/godot-docs/pull/497 I don't know what happened to this branch it was brocked somewhere. Never mind I've opened new one and now it works!!!

**Pull request closed without merging**
