### PR TITLE
VR tutorial cleanup

### PR DESCRIPTION
**Pull request by cbscribe**
We received an HTC Vive at school, and I've had a few students go through this tutorial (which is fantastic, btw). 

This PR contains changes to clean up and simplify the VR tutorial code and improve consistency including:

* Correct inconsistent use of parentheses in conditionals
* Move node reference assignments to `onready` statements, simplifying code
* Remove redundant boolean comparisons
* Minor grammar fixes

DO NOT MERGE YET! I still need to test with the latest version of 3.1, which I have not yet been able to do on my Vive PC. I will update with whatever additional changes are required for compatibility with the new release.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Sweet! I need to find time to proof read this, great stuff man!

**Comment by cbscribe** [comment]
Update: testing on 3.1 today. Initial status: `ARVRServer.get_primary_interface()` returns `null`.

**Comment by cbscribe** [comment]
Update. Working successfully in 3.1, no code changes required. :)

**Comment by akien-mga** [comment]
Great! Just needs a rebase to fix conflicts and it can be merged.

**Comment by cbscribe** [comment]
Conflicts resolved, thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.

**Pull request merged**
