### PR TITLE
Add 'Learning new features' page.

### LINKED ISSUE #4169: Getting Started / Introduction / How to learn Godot most efficiently
A guide to using the built-in code reference, online documentation, and best practices to get help on available communities.

Part of the getting started session’s rewrite. See #4035 for more information.

### PR DESCRIPTION
**Pull request by willnationsdev**
Closes #4169 

Addresses critiques of #4251 (or at least, tries to). Can end up including both or just this one, either way.

cc @NathanLovato since it'll require your review.

### CODE REVIEW

**Comment by NathanLovato** [comment]
It's looking good! Do you mind if I edit directly and add a commit to your PR? I'd like to do some small stylistic changes, add one or two pictures... but it's great.

Regarding #4251, it's more that I don't know if it addresses a need as it stands so I'd like other people's feedback on it. I'd at least replace some descriptions by instructions and tips regarding search and navigation.

**Comment by willnationsdev** [comment]
@NathanLovato Yeah, feel free to do whatever you want. As long as what needs to get done gets done, I'm good with you doing whatever. :-)

**Comment by NathanLovato** [comment]
Leaving this here if you want to put it somewhere else. It's beyond the scope of a page about learning Godot efficiently:

```
Bug Reports
-----------

If you think you have found a bug but are unsure, then go ahead and open a bug report on `GitHub <https://github.com/godotengine/godot/issues>`. Be sure to check through previous issues to see if you can find a similar one.

If you do, please upvote the post to show that you too want to see the bug fixed. If you have more information or context to add to the bug report, please add a comment to it.

If you do not find any similar past issues, then please follow the template to submit a new bug report.

If you ask in a community platform and someone informs you that it is a bug, then please remember to submit the bug report. Without it, there is little chance the Godot contributors will fix it.
```

**Comment by NathanLovato** [comment]
Leaving you some general feedback as I'm editing the page. 

Here's a great resource until #4064 gets reviewed and merged: https://v3.vuejs.org/guide/contributing/writing-guide.html#principles

The principles they use to write Vuejs's docs. And I recommend looking at some pages too. I follow a similar mindset when writing or editing docs. For instance, in the Godot docs, titles can be vague, like `Manual`, `Feature X`. You'll see I'm rewriting them to state a problem: `Finding new information in the manual`, `Moving characters with feature X`.

**Comment by NathanLovato** [comment]
Just edited the page and moved it to a new getting_started/introduction section (following #4035, I want to remove or rename step_by_step that lead some contributors to write step-by-step instructions over explanations at times). Adding pics next.

**Comment by NathanLovato** [comment]
Done! It's ready for review I guess.

**Review by willnationsdev — COMMENTED** [review]
Great edits! Thanks.

**Review by willnationsdev — COMMENTED** [review]
Looks good to me! Ready to merge I think.

**Comment by NathanLovato** [comment]
Thanks!

**Pull request merged**
