### PR TITLE
Add note about target=release_debug

### PR DESCRIPTION
**Pull request by FeralBytes**
To help out future users adding extensions like:
https://www.reddit.com/r/godot/comments/94qyc3/a_note_about_building_from_source_from_a/

### CODE REVIEW

**Comment by neikeq** [comment]
I thinks this would be misleading. There is not much point in building templates with `release_debug`, it's meant for the editor. In fact, there is no option for `release_debug` templates in the editor. You want either `debug` or `release`.

**Comment by neikeq** [comment]
The only reason to have `release_build` templates is if you want an optimized build but with better errors.

**Comment by Calinou** [comment]
@neikeq I think the notice is about building the editor with `release_debug`, not the export templates, which is why I suggested moving it.

**Comment by FeralBytes** [comment]
Good catch @neikeq and @Calinou, sorry, I should have quality checked my work.

**Pull request closed without merging**
