### PR TITLE
Document installation of requirements.txt with pip

### PR DESCRIPTION
**Pull request by akien-mga**
Follow-up to #3276.

### CODE REVIEW

**Comment by Calinou** [comment]
Shouldn't we pin the versions in `requirements.txt`? This way, all contributors will have the same version installed locally.

**Comment by akien-mga** [comment]
> Shouldn't we pin the versions in `requirements.txt`? This way, all contributors will have the same version installed locally.

We could, but I figured that it would force us to bump version every time there's a new sphinx, sphinx_rtd_theme, etc., while in general we should be fine with the latest. The main thing for which pinning the versions might make sense would be for CSS/template contributors I guess.

**Comment by akien-mga** [comment]
Actually RTD doesn't support Sphinx 2 yet so we should probably pin that at least.

**Comment by akien-mga** [comment]
Updated with versions pinned.

**Pull request merged**
