### PR TITLE
Add a scrollbar to the navigation bar

### LINKED ISSUE #1745: Enhancement suggestion: scrollbar in left side navigation of the docs website.
Is it possible to show the scrollbar for the left navigation menu? I sometimes find the mouse wheel is unsatisfactory for navigating up and down.

I'd also keep the logo and search input fixed at the top for convenience, but meh.

### PR DESCRIPTION
**Pull request by xelivous**
Fixes #1745
Also gives the scrollbar a basic style

*Bugsquad edit (keywords for easier searching): scroll*

### CODE REVIEW

**Comment by Spartan322** [comment]
Since 2018, (version 64 of) Firefox (Gecko) has also been capable of basic (as in width and color control) of the scrollbar through the CSS Scrollbars Module 1. Its still not supported in Chromium yet. No other browser engines I'm aware of are capable of scrollbar styling. (excluding old Internet Explorer)

https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

**Comment by xelivous** [comment]
Yea i included the firefox variant first but went back and added chromium to match the firefox variant since unfortunately people actually use chrome.

**Comment by Calinou** [comment]
@xelivous Could you look into solving conflicts, please? :slightly_smiling_face:

**Comment by Calinou** [comment]
Superseded by #3237. Thanks for your contribution anyway :slightly_smiling_face:

**Pull request closed without merging**
