### PR TITLE
Mention buffer size and Windows 11 mouse polling in Fixing jitter, stutter and input lag

### PR DESCRIPTION
**Pull request by Calinou**
This also documents command line arguments that may be of interest when running Godot projects.

- See https://github.com/godotengine/godot/pull/80566. Do not merge before that PR is merged.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Put a safety on the big green button for now, seeing the discussion in the PR and that it seems dicey whether it'll be merged for 4.2 for now.

**Comment by Calinou** [comment]
> Put a safety on the big green button for now, seeing the discussion in the PR and that it seems dicey whether it'll be merged for 4.2 for now. Once its merged, this can be too, the docs PR LGTM.

The original PR was closed, but https://github.com/godotengine/godot/pull/87340 integrates most of its functionality (except it doesn't allow decreasing frame queue size to `1` like https://github.com/godotengine/godot/pull/80566 did).

**Review by mhilbrunner — APPROVED** [review]
@Calinou I guess this can then be merged now? :)

**Comment by mhilbrunner** [comment]
...merged. Thanks :)

**Pull request merged**
