### PR TITLE
Update 09.adding_animations.rst

### PR DESCRIPTION
**Pull request by nathanjwtx**
I am not sure if `translation` is the correct term for what we are changing but in the editor itself it is called `position` and I found this a bit confusing to begin with. I replaced the `translation` with `position` in the 3 places I found.

If `translation` is the correct term, could an explanation be added to the top of the page?

### CODE REVIEW

**Comment by YuriSizov** [comment]
Yes, translation is a correct term for 3D transformations, but indeed we renamed the property to position in 3D to match 2D, so your change here is correct.

**Comment by nathanjwtx** [comment]
> Yes, translation is a correct term for 3D transformations, but indeed we renamed the property to position in 3D to match 2D, so your change here is correct.

Thank you for the clarification. It did seem more than a simple typo but I wasn't sure.

**Comment by Piralein** [comment]
This change was already done by #6811.

current file:

- [line 80](https://github.com/godotengine/godot-docs/blame/master/getting_started/first_3d_game/09.adding_animations.rst#L80)
- [line 96](https://github.com/godotengine/godot-docs/blame/master/getting_started/first_3d_game/09.adding_animations.rst#L96)
- [line 166](https://github.com/godotengine/godot-docs/blame/master/getting_started/first_3d_game/09.adding_animations.rst#L166)

**Comment by YuriSizov** [comment]
Ah, indeed. Sorry for the wait, but this was indeed fixed about the same time you made your PR :)

**Pull request closed without merging**
