### PR TITLE
Update Singleton Autoload Tutorial

### PR DESCRIPTION
**Pull request by Ceryni**
Remedies Issue #902 by updating the Singleton Autoload tutorial in 'Step by Step' using Godot 3.0 Beta1. I've updated the project templates as well as the screenshots and instructions where needed. I tested the site build locally and everything _seemed_ fine.

Let me know if I've done something incorrect here or I can improve upon things. This is the first time for me interacting with the Godot Docs.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Hey @Ceryni thanks much! There's just one thing I'd recommend: it seems you captured the first two pictures on a 4k screen: they're over 2k wide. Could you make it smaller, and ideally run your images through pngquant or a similar compression tool?

**Comment by mhilbrunner** [comment]
@Ceryni Thanks for your first contribution! Do you have time to make the changes requested by Nathan? If you need help, just ask here or on Godot Discord/IRC.

**Comment by Ceryni** [comment]
@NathanLovato @mhilbrunner Apologies for my delayed response. Holidays and what not :) 

Absolutely, I can downsize the image quality as well as compressing them. Could I ask what the recommended resolution for a screenshot is? I'm happy to update the contributors section in the read-me to show this.

**Comment by mhilbrunner** [comment]
Depends on the screenshot, really; it should be clear and readable on a 1080p screen. So half your resolution at most. However, I'd avoid showing unnecessary large empty windows if possible, like here:

https://raw.githubusercontent.com/godotengine/godot-docs/aeddf3179f85104af2270ed71ec0bb86856d7a47/learning/step_by_step/img/newscript.png

You could reduce the height of that window or even simply leave of the bottom half.

**Comment by NathanLovato** [comment]
@Ceryni, like @mhilbrunner said. HD screencaps are best. The docs website is less than 1000px wide IIRC anyway.

**Comment by mhilbrunner** [comment]
@Ceryni Hi! Do you think yo have time in the next few days to update your changes? If not, don't fret, in that case I'll see if I can take some time to merge your changes and resize the screenshots you provided.

**Comment by ThibaultLemaire** [comment]
I'd say this fixes #1328 as well

**Comment by mhilbrunner** [comment]
Supersed by https://github.com/godotengine/godot-docs/pull/1481

**Pull request closed without merging**
