### PR TITLE
Update instancing tutorial

### LINKED ISSUE #6793: Use instancing example from godot-projects for the "Step by step: Instancing" page
As discussed in PRs #6187 and #5374 the instancing demo from the "Step by step" tutorials could be moved to the godot-demo-projects repository for v4.

But I think it would make more sense to reuse the already existing (and nearly identical) instancing project:
https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/2d/instancing

I would be up for a PR to rewrite the necessary parts of the docs and add new screenshots, but I'm not sure how we would handle this going forward. E.g. how can we link to a specific version of a demo-project?

### PR DESCRIPTION
**Pull request by rm-code**
Removed the instancing.zip as discussed in #6793 and replaced it with text and image references to the godot-projects instancing demo: https://github.com/godotengine/godot-demo-projects/tree/4.0/2d/instancing

Added a small section about instancing via code.

Closes #6793

Supersedes #6187 and #5374

### CODE REVIEW

**Comment by rm-code** [comment]
@Calinou This is my draft for the changes discussed in #6856. Let me know if I should change anything. The instancing demo hasn't been updated yet so I think it would make sense to wait for that.

**Comment by rm-code** [comment]
Added a note about how to download the demo directly from github:
Bildschirmfoto 2023-03-04 um 20 13 01

**Comment by rm-code** [comment]
As suggested by @YuriSizov in #5121 I removed the `:article_outdated: True` Tag with the latest update to this PR.

**Comment by skyace65** [comment]
Superseded by #7222

**Comment by YuriSizov** [comment]
Actually, this one is probably fine, as it updates more than just the file. Changes to the ZIP file need to be removed from this PR though, and images need to be converted to WebP.

**Comment by skyace65** [comment]
Closing due to a lack of activity from the PR author

**Pull request closed without merging**
