### PR TITLE
CSS: Remove error higlight

### PR DESCRIPTION
**Pull request by mhilbrunner**
Fixes https://github.com/godotengine/godot-docs/issues/5032

### CODE REVIEW

**Comment by pycbouh** [comment]
Please amend the typo in the commit before a kitten dies 👀😺

**Comment by mhilbrunner** [comment]
Oooh noo, shame, shame :D

**Comment by mhilbrunner** [comment]
There, typo's fixed, kittens happy :P

**Comment by mhilbrunner** [comment]
It was, in fact, possible to disable this locally. 🎉

**Comment by akien-mga** [comment]
Cherry-picked for 3.3 and 3.2.

**Pull request merged**
