### PR TITLE
fix comment

### PR DESCRIPTION
**Pull request by akpath**
Comment was inaccurate in its conversion of radians to degrees

### CODE REVIEW

**Review by skyace65 — CHANGES_REQUESTED** [review]
Please also fix this in the comment for the C# code. And please keep this PR to one commit. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request).

**Comment by akpath** [comment]
Oops. Fixed.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
