### PR TITLE
Document that `light()` functions aren't run if vertex shading is forced

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot/issues/39513.

### CODE REVIEW

**Comment by mbrlabs** [comment]
This should probably also mention that the same limitation applies if `vertex_lighting` is used as `render_mode` directly in the shader.

**Comment by Calinou** [comment]
@mbrlabs It probably will. Thanks for reminding me about it :slightly_smiling_face:

**Comment by mbrlabs** [comment]
No problem ;)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
