### PR TITLE
Update Instantiate menu in 03.player_movement_code.rst

### PR DESCRIPTION
**Pull request by manik1235**
This commit updates the instructions for instantiating a new child scene in the getting started first 3d game tutorial so that the menu option matches the language used in version 4.1.1.

The associated image is updated to match too.

The "Instance Child Scene" menu now reads "Instantiate Child Scene".

### CODE REVIEW

**Comment by skyace65** [comment]
Thanks for the PR! Please convert the png to a .webp file. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion).

**Comment by manik1235** [comment]
> Thanks for the PR! Please convert the png to a .webp file. If you don't know how to do that we have a guide [here](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion).

All set, thanks for the feedback!

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! in the future please try and keep your PR to 1 commit, we have a guide on how to do that [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request). It looked like there were a few compression artifacts but they're not terrible so I merged as is, I'll have to look into what Sqoosh is doing with that.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
