### PR TITLE
Clarify boolean assignment in "Your First Game"

### LINKED ISSUE #1559: Dodge the creeps, explain `flip_h = velocity.x < 0` for beginners
See https://steamcommunity.com/app/404790/discussions/0/1729828401680097511/

One user on Steam was confused about this code chunk in the Dodge the creeps tutorial:
```gdscript
if velocity.x != 0:
    $AnimatedSprite.animation = "right"
    $AnimatedSprite.flip_v = false
    $AnimatedSprite.flip_h = velocity.x < 0
elif velocity.y != 0:
    $AnimatedSprite.animation = "up"
    $AnimatedSprite.flip_v = velocity.y > 0
```
and especially the part assigning `velocity.x < 0` to `flip_h`.

I think it's good to show this construct as it's quite idiomatic in most programming languages, but it might be worth explaining a bit more for beginners.

Personally I would start by putting parentheses to make the operator precedence clear `flip_h = (velocity.x < 0)`, which is also quite idiomatic when return/assigning the result of a condition test to a variable.

Then if need be, adding a comment to make this more explicit might be good too.

### PR DESCRIPTION
**Pull request by FeralBytes**
Let me know if this meets the intent of and
fixes #1559

### CODE REVIEW

**Comment by FeralBytes** [comment]
@cbscribe OK thanks. I will think more on this one and modify once I have a better plan.

**Comment by FeralBytes** [comment]
@cbscribe please let me know if this is more acceptable? Thank you again for the feedback.

**Comment by FeralBytes** [comment]
@cbscribe fixed.

**Comment by cbscribe** [comment]
Thanks, can you merge the commits?

**Comment by FeralBytes** [comment]
If you mean merge them down to a single commit? Yes I can but it will be done in a few days. Otherwise I don't know what you mean.

**Comment by cbscribe** [comment]
Yes, that's what I mean - it helps keep the commit history clean.

**Comment by FeralBytes** [comment]
Is [this now possible](https://blog.github.com/2016-04-01-squash-your-commits/) via github, or is that only for paid version? Otherwise I will [use this link for my own reference](https://stackoverflow.com/questions/35703556/what-is-squashing-commits-in-git).

**Comment by cbscribe** [comment]
Actually, I can do that, yes. But keep it in mind for future PRs. The rule of thumb is "one commit per substantive change".

**Comment by FeralBytes** [comment]
OK I will thanks.

**Pull request merged**
