### PR TITLE
Update compute_shaders.rst

### PR DESCRIPTION
**Pull request by jgonz-hub**
_Bugsquad edit:_ Fixes https://github.com/godotengine/godot/issues/70772

### CODE REVIEW

**Comment by Calinou** [comment]
Can you describe why this change is needed?

**Review by clayjohn — APPROVED** [review]
Changes make sense, Metal doesn't support doubles in shaders so this would have failed on MacOS devices

**Comment by Calinou** [comment]
> Changes make sense, Metal doesn't support doubles in shaders so this would have failed on MacOS devices

It's probably a good idea to add a warning in the documentation for this :slightly_smiling_face:

**Comment by clayjohn** [comment]
Merging now as this is a good change

**Pull request merged**
