### PR TITLE
Add images for Vector2's angle methods

### PR DESCRIPTION
**Pull request by mechPenSketch**
The image is to be added under [Vector2's angle_to()](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-angle-to) method description to illustrate the angle being returned.

As adviced in https://github.com/godotengine/godot-docs/issues/4676#issuecomment-784288436, this is where I'm adding the image.

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
Images that aren't referenced anywhere in the manual should be added to the top-level [`img/` folder](https://github.com/godotengine/godot-docs/tree/master/img).

Don't add images to `classes/` as the contents of that folder may be wiped and regenerated in the future.

**Review by Calinou — APPROVED** [review]
Thanks!

Remember to open a pull request against the *main Godot repository* to reference those images in the `doc/classes/Vector2.xml` class reference.

**Comment by aaronfranke** [comment]
For [`vector2_angle_to.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to.png) isn't confusing but it could be more clear if the ends were arrows.

For [`vector2_angle.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle.png) why was the same red color used for both the vector line, and the X axis, and where it connects to the X axis? It's not immediately clear that the vector is the diagonal line. An arrow would be good here too.

For [`vector2_angle_to_point.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to_point.png), similar to the above. The points and labels are good, but the coloring is misleading. For this one, we should showcase them as points, not arrows, it's only the coloring that could be improved.

**Comment by mechPenSketch** [comment]
> For [`vector2_angle_to.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to.png) it isn't confusing but it could be more clear if the ends were arrows.
> 
> For [`vector2_angle.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle.png) why was the same red color used for both the vector line, and the X axis, and where it connects to the X axis? It's not immediately clear that the vector is the diagonal line. An arrow would be good here too.
> 
> For [`vector2_angle_to_point.png`](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to_point.png), similar to the above. The points and labels are good, but the coloring is misleading. For this one, we should showcase them as points, not arrows, it's only the coloring that could be improved.

Will these do?

`Vector2.angle()`:
vector2_angle_original

`Vector2.angle_to(to)`:
vector2_angle_to_original

`Vector2.angle_to_point(to)`:
vector2_angle_to_point_original

**Comment by aaronfranke** [comment]
@mechPenSketch Those are great, much better! One more thing: For `Vector2.angle_to_point(to)`, we want to showcase that the points don't have to be on the axes, so ideally nether of the points will be on the dark lines. We can show the line extending back to the X axis line to form the angle though (again though, we should show that it doesn't need to be the origin, so we can maybe move/rotate the line so that the extending backwards part only touches the X axis dark line and not the Y axis).

**Comment by mechPenSketch** [comment]
Will this do?
vector2_angle_to_point_original
The line is still darker, but not at that level so that it instead represents a major grid rather than a minor grid or axis.

**Comment by aaronfranke** [comment]
@mechPenSketch It's not what I would do, but this is still better, and it looks good to me. You can submit a PR with these improved images and ping me for review and I'll give it a :heavy_check_mark: .

**Pull request merged**
