### PR TITLE
init commit custom godot servers, new file

### PR DESCRIPTION
**Pull request by hungrymonkey**
this doc is made to elaborate on how to create a background thread with godot facilities,
this server would all the engine programmer extend functionality without hindering the main thread
I hope the code is correct but the emit signal binding is kinda hacky

please review

index.rst

updated the side bar

### CODE REVIEW

**Comment by hungrymonkey** [comment]
A few things, my binding signal code might be terrible.

Please review the multi threaded code if possible

**Comment by hungrymonkey** [comment]
@mhilbrunner  should i squash my commits?

**Comment by mhilbrunner** [comment]
Yeah, but we can also wait and see if anybody else has any suggestions, I just had a brief look. :) Thanks for the work! :tada:

**Comment by hungrymonkey** [comment]
@mhilbrunner  some of these guides are desperately needed for any c++ dev.

the emit signals is quite terrible since i dont bind it to the singleton. I guess I have to wait until somebody else understand the class facilities to fix my examples code

here is my code for the example

https://github.com/hungrymonkey/godot/tree/hilbert_doc/modules/hilbert_hotel

**Pull request merged**
