### PR TITLE
missing @ hint on export (typo?)

### PR DESCRIPTION
**Pull request by ego-edesse**
Updating to GDScript 2.0 syntax

### CODE REVIEW

**Comment by YuriSizov** [comment]
It would be good to do a pass on the docs and update all cases where annotations should be used now, or at least do it in bulk.

**Comment by Calinou** [comment]
This is not a typo – it's outdated Godot 3.x code. `@export` is an annotation in 4.0, while it was a keyword in 3.X.

**Comment by ego-edesse** [comment]
I thought it was a typo because further in the tutorial it has been updated to GDScript 2.
It was my first PR on Godot project, thats why I didn't make anything big. I'll try to change more then

**Comment by YuriSizov** [comment]
> I thought it was a typo because further in the tutorial it has been updated to GDScript 2.

Well, that's why it would be nice to do a proper pass 🙃 As you can see, if someone changes only some of the outdated syntax, it gets confusing and harder to track afterwards. If you want to take time and look through other related articles, that would be amazing and a great way to contribute!

**Comment by ego-edesse** [comment]
> 

Without being a complete beginner, my knowledge of GDScript is not enough to be able to check pages and be sure I am not leaving anything out. I may come back later when I feel more comfortable but I guess we can already accept these two small commits

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you! Sorry this took a bit to get merged :)

**Pull request merged**
