### PR TITLE
General fixes for the new "Legal" page

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Fixed title underlines.
- Fixed typos.
- Correctly place it in its own "Legal" section instead of "VR".
- Removed extraneous spaces.

### CODE REVIEW

**Comment by clayjohn** [comment]
Maybe put this under "Misc"? I dont think we will have more than one "legal" tutorial and i dont think we should have a full section for one tutorial.

**Comment by YeldhamDev** [comment]
@akien-mga What do you think, stay on its own section, or put it on "Misc"?

**Comment by fire** [comment]
Would like a link to a press kit section. https://github.com/godotengine/godot/issues/8514

**Comment by mhilbrunner** [comment]
I'll just merge these fixes for now, adding a Press Kit section or moving the link may still be good ideas however! :)

**Pull request merged**
