### PR TITLE
Added C# code to Part 1 of the FPS tutorial

### PR DESCRIPTION
**Pull request by Xylord**

### CODE REVIEW

**Comment by Xylord** [comment]
Rémi suggested I make a PR with only Part 1 to receive feedback on style and any other issues there might be before forging on with the other parts. Pretty much everything in this part's GDScripts exists 1:1 in C#, so this was not too difficult. The main thing I'm wondering about is whether anything should be added/modified in the body of the text. All the variables have the same name, except they now use PascalCase/CamelCase as required, so it shouldn't be too confusing, but someone else will know better.

**Comment by exts** [comment]
Update all private fields to start with an underscore per the style guide http://docs.godotengine.org/en/latest/getting_started/scripting/c_sharp/c_sharp_style_guide.html#naming-conventions

**Comment by mhilbrunner** [comment]
Thank you and welcome! Congrats on your first PR :)

I found nothing besides what @exts mentioned above.

**Comment by Xylord** [comment]
@exts Got it, I'll correct this, thank you. Thanks @mhilbrunner, looking forward to this being the first of many.
How do we feel about [Export]ing all the public properties? I believe this replicates the behaviour of the GDScript version better, but I was wondering if that might be unnecessary clutter.

**Comment by mhilbrunner** [comment]
I think thats fine :) Thank you!

**Comment by mhilbrunner** [comment]
Merged. Thanks again!

**Comment by Xylord** [comment]
@mhilbrunner Cool! Then I'll start putting up the other parts. I'm guessing a single PR for all the parts would be better?

**Comment by mhilbrunner** [comment]
Whatever suits you, I don't think it makes much difference :)

**Pull request merged**
