### PR TITLE
Fix non-unique Sphinx name in Getting Started

### LINKED ISSUE #5596: <toc-learn-introduction> is a non-unique Sphinx reference and misdirects links
**Your Godot version:**

**Issue description:**
The section https://docs.godotengine.org/en/latest/getting_started/step_by_step/index.html#toc-learn-step-by-step contains a link :ref: toc-learn-introduction, which was intended to lead to https://docs.godotengine.org/en/latest/getting_started/introduction/index.html#toc-learn-introduction, but leads to https://docs.godotengine.org/en/latest/getting_started/first_2d_game/index.html#toc-learn-introduction, because the Sphinx reference name is not unique (and may have been copied over for each section).

My proposed fix is to change the name in each index page to resemble its page title and update the refs. I'll add a PR
**URL to the documentation page:**
https://github.com/godotengine/godot-docs/search?q=toc-learn-introduction

### PR DESCRIPTION
**Pull request by leogott**
Fix #5596

### CODE REVIEW

**Comment by leogott** [comment]
Actually … @mhilbrunner,
where is
https://github.com/godotengine/godot-docs/blob/9a05eef561cba5f6c9eabbb59d2823daa88298bb/getting_started/step_by_step/scripting_first_script.rst#L23
supposed to point to? The only mention I found of "us" assuming the reader has the programming basics down is in [/getting_started/introduction/learning_new_features](https://docs.godotengine.org/en/stable/getting_started/introduction/learning_new_features.html#learning-to-think-like-a-programmer), which is probably a good resource to point to, but seems unlikely to be the intended one?
I don't think /getting_started/step_by_step/index is correct, and the current /getting_started/introduction/index would make little sense either, as the relevant content starts only at sub-chapter 4 (out of 5), and even there it's half way down the page.

My intuition is to open a separate issue. Input?

**Comment by leogott** [comment]
bump

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
