### PR TITLE
Update textureQueryLevels to mention it returns 1 when the texture is unassigned

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes  https://github.com/godotengine/godot/issues/86402

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by jsjtxietian** [comment]
> If wanted I can fix the branch for you.

Yes please! 




> You should target `master` not `4.2`

It wasn't intentional, I opend the doc page on 4.2 by mistake and started editting it. Thanks, I will be more careful next time.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2.

**Pull request merged**
