### PR TITLE
Fix GDScript code sample in Matrices and transforms

### PR DESCRIPTION
**Pull request by samlaf**

### CODE REVIEW

**Comment by Calinou** [comment]
@samlaf Out of curiosity, what does this change bring to the table?

**Comment by samlaf** [comment]
Ah, sorry should have mentioned more. I thought this would be obvious to main/core developers.
The code as was didn't run for me. I needed to change it to use Vectors.
I was guessing either the API changed, or that was a mistake made from copying the C# call (which doesn't use vectors it seems).

**Review by Calinou — APPROVED** [review]
> Ah, sorry should have mentioned more. I thought this would be obvious to main/core developers.
The code as was didn't run for me. I needed to change it to use Vectors.
I was guessing either the API changed, or that was a mistake made from copying the C# call (which doesn't use vectors it seems).

Indeed, I forgot that there's no GDScript constructor for `Transform2D()` that takes 6 floats.

Thanks!

**Comment by Calinou** [comment]
Cherry-picked to the `3.2` branch.

**Pull request merged**
