### PR TITLE
Updated networking docs

### PR DESCRIPTION
**Pull request by Tilican**
Update binary serialization for godot 3

### CODE REVIEW

**Comment by Keplar1995** [comment]
Not a big issue at all, voting to close this.

**Comment by mhilbrunner** [comment]
So I tested this, builds the doc page without warnings and looks fine.

If someone wants to compare:
https://imgur.com/a/OwXlH

**Comment by mhilbrunner** [comment]
Thanks for your first contribution!

**Comment by LinuxUserGD** [comment]
Please update the Multiplayer Bomber
https://github.com/godotengine/godot-demo-projects/issues/189

**Pull request merged**
