### PR TITLE
Added a FPS (First person shooter) game tutorial.

### LINKED ISSUE #538: Tutorial: 1st Person Shooter
From the Aug Patreon poll.

Ideally, these tutorials should have written and video versions.

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
I made a FPS tutorial in three parts:
* The first part covers making a first person character.
* The second part covers adding weapons/guns to the character built in part one.
* The third part adds ammo to the guns, and sounds for when the player fires.

Hopefully the tutorial is both friendly to beginners without being overly simplified.

I'm open to any suggestions. This is the first tutorial I've made in awhile, so I am a little rusty.

I planning on making a video version as well. For now I'm waiting, just to make sure the tutorial is good before I spend the time making a video tutorial. After the video tutorial I'll start working on adding the things I listed at the end of part 3.
(The IK stuff will come after that... Probably. I'm kinda swarmed with work right now, so no promises :sweat_smile: )

Closes #538

### CODE REVIEW

**Comment by TwistedTwigleg** [comment]
Thanks!

I’m afraid I am not Jeremy Bullock. I only recently discovered his channel about a week ago. I didn’t know he was making a FPS tutorial until a couple days ago, at which point I already had 95% of the written tutorial done (and the Godot project was already done a week or so before that). It would be cool to compare our FPS’ to see the differences in implementation.

We can link to his tutorials if you want. I still plan on making a video tutorial because I want to use it as practice making video tutorials, but I have no problem linking to Jeremy’s tutorials.

**Comment by RiverMesa** [comment]
Honestly, when it comes to tutorials or learning resources in general, the more the merrier - especially with first person shooters, which are both relatively complex (compared to, say, a 2D platformer) and in high demand (because *everyone wants to make the next big FPS that brings Godot to the mainstream*, clearly), so it'll be interesting to see how the two compare.

Great work either way!

**Comment by NathanLovato** [comment]
No worries, sent this to Jeremy so he doesn't write everything for nothing. I wouldn't link to a different series and project from a docs page. Yeah great work anyway. I'll merge it now so people can start reading it, and pushing fixes if need be.

**Comment by NathanLovato** [comment]
If you need a hand with videos don't hesitate to ask! And if you haven't picked an editor yet you could try out blender with the plugins daniel oakey and I are working on ;)

**Comment by TwistedTwigleg** [comment]
Thanks RiverMesa!

I totally agree. More tutorials help show the many different ways to go about making games, especially for complex projects, which can be done in many different ways (generally) due to their complexity. The more tutorials we have the better!

_______

Thanks NathanLovato!

I do have some questions about making videos, many of them relating with audio (thankfully I've figured out most of the image related stuff). Where should I ask? Should I ask here?

I have a editor on Windows (Cyberlink Powerdirector 14 Ultra), but I haven't ever used it beyond some basic tinkering. I mainly work on Linux and use Blender extensively, so I'll definitely have to try blender with the plugins you guys are working on! They look awesome!

Thanks again!

**Pull request merged**
