### PR TITLE
Add note on using the MODE_KINEMATIC of RigidBody2D

### PR DESCRIPTION
**Pull request by Flonka**
It was hard to understand how to properly use a RigidBody2D in kinematic mode, after some experimentation i figured out what was happening. 

I believe this note should assist anyone with using the kinematic mode.

### CODE REVIEW

**Comment by cbscribe** [comment]
I'm not sure this is the right place for this. This article is an introduction to physics nodes, covering all the different types. More in-depth details of working with rigid body nodes  and their modes would be better covered in the rigid body tutorial.

**Comment by mhilbrunner** [comment]
Actually, maybe this should be in the class ref for RigidBody2D?

**Comment by akien-mga** [comment]
> Actually, maybe this should be in the class ref for RigidBody2D?

I agree, this should go directly in the class reference.

**Comment by Flonka** [comment]
Alright, I will take the notes over there at some point : ) I haven't looked at all on how to contribute there. Thanks for the feedback!

**Pull request closed without merging**
