### PR TITLE
Purge channels that haven't made tutorials for Godot 4

### PR DESCRIPTION
**Pull request by RadiantUwU**
This pull request is meant to warn new users about the old tutorials and purge channels that haven't made tutorials for Godot 3.x.

### CODE REVIEW

**Comment by Noobidoo** [comment]
Would not straight up remove them but move them to different section. There is still good information in some of them.

**Review by skyace65 — CHANGES_REQUESTED** [review]
I've reviewed everyone removed from the list and a few changes should be made.
- Pigdev has several Godot 4 videos, just change the link to their channel (Pigdev https://www.youtube.com/@pigdev/videos)
- BornCG also has several Godot 4 videos, same thing just change the link to their channel (https://www.youtube.com/@BornCG/videos)
- Bitbrain only has 1 godot 4 tutorial, however the game in his devlog upgraded to Godot 4, it's only 1 devlog right now but I'd say move him to the devlog section

These ones I think still should be removed but wanted to note some things other reviewers may care about:
- TheBuffED has two Godot 4 videos, not sure if it's enough to justify keeping him on the list but I'd be okay with it if others want that
- Code with Tom only has 1 Godot 4 video and it's a Unity to Godot guide
- GDScript Dude has only 1 Godot 4 video

**Comment by skyace65** [comment]
> Would not straight up remove them but move them to different section. There is still good information in some of them.

I don't think it makes sense to keep them given the amount of breaking changes between Godot 3.x and 4.x. And if people still want to see them because they're using Godot 3 there's still the 3.x version of the docs.

**Comment by mhilbrunner** [comment]
I've gone ahead and incorporated Sky's suggestions into these changes in https://github.com/godotengine/godot-docs/pull/8825, while also removing the notes at the top, ordering the list and making some other minor changes, while giving you credit on the PR and commit. Thanks for contributing!

**Pull request closed without merging**
