### PR TITLE
Update gdscript_basics.rst

### PR DESCRIPTION
**Pull request by Vikram1323**
arr[0] = "Hi!" # Replacing value 1 with "Hi".
arr.append(4) # Array is now ["Hi", 2, 3, 4].

arr[0] = "Hi!" # Replacing value 1 with "Hi!".
arr.append(4) # Array is now ["Hi!", 2, 3, 4].

### CODE REVIEW

**Comment by aBARICHELLO** [comment]
You can close the other two and include all changes in this PR.

**Comment by Vikram1323** [comment]
So, one pull request will change documentation of all versions(2.1, 3.0, master)

**Comment by aBARICHELLO** [comment]
Yes, the maintainers will handle the necessary cherry picking to other branches. Commit to the version branches(2.0, 3.0, etc) only if the change is specific to that version.

**Comment by Vikram1323** [comment]
Ok.
I closed other two PR.

**Pull request merged**
