### PR TITLE
Update PR Workflow documentation to include updated information about GitHub's account verification via HTTPS

### PR DESCRIPTION
**Pull request by damdalf**
Resolves: https://github.com/godotengine/godot-docs/issues/7273

To preface, I am not sure that I have edited the correct file to resolve the issue. While I found that most of the RST files in Godot's documentation are automatically generated, this seems to only occur within the class reference documentation. Furthermore, this file did not have a warning comment at its beginning. Thus, I have gone ahead and attempted to resolve the issue by directly editing the RST file.

These changes simply update the [documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html) that currently exists for the PR Workflow to include up-to-date information about GitHub's account verification over HTTPS. This change should remove some possible confusion for new contributors of Godot, which in-turn will promote more community development. If I have made in a mistake in editing this file to resolve this issue, please let me know and I will happily edit the correct file. Thank you!

### CODE REVIEW

**Comment by Calinou** [comment]
> While I found that most of the RST files in Godot's documentation are automatically generated

This is only the case for files in the `_classes` folder. All other files are manually written.

**Comment by mhilbrunner** [comment]
There is a '.' missing after the Github link. Otherwise looks good to me.

**Comment by damdalf** [comment]
> There is a '.' missing after the Github link. Otherwise looks good to me.

Fixed! Appreciate the feedback.

**Review by Piralein — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks a ton for contributing! Merged.

**Comment by mhilbrunner** [comment]
Pushed to `4.0` and `stable`.

**Comment by mhilbrunner** [comment]
Cherry-picked to 3.6 in https://github.com/godotengine/godot-docs/pull/9936.

**Pull request merged**
