### PR TITLE
Fix incorrect export template path in Compiling for macOS

### PR DESCRIPTION
**Pull request by dploeger**
I saw that the given path was wrong

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by dploeger** [comment]
Yay! 😊

**Comment by dploeger** [comment]
But actually, I already have two merged PRs. 😊

**Comment by Calinou** [comment]
Cherry-picked to the `3.4` and `3.3` branches.

**Pull request merged**
