### PR TITLE
Update immediategeometry.rst

### PR DESCRIPTION
**Pull request by jbvovau**

### CODE REVIEW

**Comment by Calinou** [comment]
Contributions to the class reference should be sent on the main Godot repository, not here. See [Contribute to the class reference](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html) in the documentation :slightly_smiling_face:

**Comment by clayjohn** [comment]
@Calinou false positive. This is in a tutorial. This isn't the class reference.

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
Removing cherrypick tag since master was merged into 3.2.

**Pull request merged**
