### PR TITLE
Add useful tip in first 2d-game tutorial

### PR DESCRIPTION
**Pull request by kvisle**
Went through a tutorial, hit a problem that I had to look up myself, added it to the tutorial, sending pull request.

### CODE REVIEW

**Comment by Calinou** [comment]
Since Godot 3.3, there is a faster way to set the main scene from the FileSystem dock. Right-click the scene in the FileSystem dock then choose **Set as Main Scene**.

**Comment by cbscribe** [comment]
I'd go with the selecting the file from the FileSystem..

In any event, if referring to the Project Settings, we should stick to the same style as in the rest of the doc, eg " Project -> Project Settings -> Display -> Window"

**Comment by gerep** [comment]
@kvisle maybe you can add the suggestion from @Calinou to your change.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
