### PR TITLE
Document missing macOS/iOS support for HTML5 due to upstream bugs

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot-docs/issues/7054.

### CODE REVIEW

**Comment by clayjohn** [comment]
I'm not sure this is correct. There are many users facing issues with macOS web export. But I don't think we should say it isn't supported. For many users web exports will work fine on Macs once safari merges their change to use ANGLE over Metal instead of ANGLE over GL

**Comment by Calinou** [comment]
> I'm not sure this is correct. There are many users facing issues with macOS web export. But I don't think we should say it isn't supported. For many users web exports will work fine on Macs once safari merges their change to use ANGLE over Metal instead of ANGLE over GL

The PR isn't saying that it's not supported – just that in practice, HTML5 exports currently won't run on macOS and iOS.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
> For many users web exports will work fine on Macs once safari merges their change to use ANGLE over Metal instead of ANGLE over GL

I think pointing out that people shoukd not expect it to work _currently_ (and then removing this note once change is merged and widely deployed) is fine.

**Review by skyace65 — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged for now. Thanks!

**Pull request merged**
