### PR TITLE
There is no 4D noise in base Noise

### PR DESCRIPTION
**Pull request by clemens-tolboom**

### CODE REVIEW

**Comment by Calinou** [comment]
For future reference: this is a leftover from 3.x, as OpenSimplexNoise supports 4D noise but FastNoiseLite doesn't.

**Comment by clemens-tolboom** [comment]
And done in [4-0-alpha-6](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6/).

> Noise: Add more noise types, noise color ramp, replace OpenSimplexNoise with FastNoiseLite ([GH-56718](https://github.com/godotengine/godot/pull/56718)).

**Comment by skyace65** [comment]
Does FastNoiseLite also support 1D noise? There's no mention of it on its github page.

**Comment by clemens-tolboom** [comment]
Its parent class does https://docs.godotengine.org/en/latest/classes/class_noise.html#class-noise

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Pull request merged**
