### PR TITLE
Document onion skinning, autoplay on load and remove a reference to Godot 3

### LINKED ISSUE #9000: Add Information About the "AutoPlay on Load" Button to the AnimationPlayer Node's Documentation
**Your Godot version:**
v4.2.1.stable.official [b09f793f5]

**Issue description:**
I was trying to play an animation for a node on ready, to avoid playing the animation in a script. I couldn't find the button for this, so I checked the docs. I didn't know the right wording to search (autoplay on load) so I didn't find what I was looking for. A user in the Godot community Discord was kindly able to explain where the button is: in the animation window, to the right of the clip. I hadn't ever interacted with this button, so I kept looking right past it.

I was able to find references to "autoplay on load" [here](https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html#state-machine-travel) and [here](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/09.adding_animations.html#animating-the-mobs), but none exist within the docs page for the AnimationPlayer itself. It mentions the autoplay property, but not how to autoplay an animation.

I propose one of these two solutions:
1.) Add a blurb underneath the AutoPlay property mentioning the "autoplay on load" button. Explain that you can accomplish autoplaying an animation without a script utilizing this button. Provide a picture, mention that it is in the animation window.
2.) Create a relevant entry for this feature, perhaps somewhere in [this section](https://docs.godotengine.org/en/stable/tutorials/animation/animation_track_types.html), and link to it underneath the AnimationPlayer node's autoplay property.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_animationplayer.html#class-animationplayer-property-autoplay

### PR DESCRIPTION
**Pull request by skyace65**
Documents onion skinning and autoplay on load in the introduction to the animation features page. Also removes a reference to Godot 3 in the RESET animation tracks section, rewords it a bit as well for clarity. Closes #9000.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by amarraff** [comment]
Thank you for adding this information to the docs! One of my main points from #9000 was to have a reference to the auto play on load functionality somewhere in the AnimationPlayer node’s doc page, so that users reading it could find the info more intuitively. But, I don’t see this in your changes. Is this not typically something that’s done? Apologies if I’m missing something in the changes.

**Comment by skyace65** [comment]
> Thank you for adding this information to the docs! One of my main points from #9000 was to have a reference to the auto play on load functionality somewhere in the AnimationPlayer node’s doc page, so that users reading it could find the info more intuitively. But, I don’t see this in your changes. Is this not typically something that’s done? Apologies if I’m missing something in the changes.

Typically we don't document the editor interface in the class reference. Additionally that class reference page does link to the animation section of the manual which this page is a part of.

**Comment by amarraff** [comment]
> > Thank you for adding this information to the docs! One of my main points from #9000 was to have a reference to the auto play on load functionality somewhere in the AnimationPlayer node’s doc page, so that users reading it could find the info more intuitively. But, I don’t see this in your changes. Is this not typically something that’s done? Apologies if I’m missing something in the changes.
> 
> Typically we don't document the editor interface in the class reference. Additionally that class reference page does link to the animation section of the manual which this page is a part of.

Ah okay, thanks for clarifying. I can imagine trying to decide what to link and what not to link inside every class reference would get too confusing.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9647.

**Pull request merged**
