### PR TITLE
Fix multiple typos related to Particle Systems

### PR DESCRIPTION
**Pull request by AnOpenSauceDev**
Fixes multiple cases where "Amount" was incorrectly spelled as **"Ammount"**, also fixes a typo where "Ratio" was spelled as **"Radio"**.

### CODE REVIEW

**Comment by Mickeon** [comment]
Very nice, could you [rebase those those commits](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase)?

**Comment by Mickeon** [comment]
You merged 2 out of 3, it would be nice to have just one commit with both.

**Review by Mickeon — APPROVED** [review]
That aside, this is nice.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! Since this is your first PR I've done a squash and merge but in the future we need you to keep everything to 1 commit. If you don't know how to do that when editing a PR there's another section on the page Mickeon linked to that goes over that ([this section](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request)). Also congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Pull request merged**
