### PR TITLE
use `await ToSignal()` for game over timing

### PR DESCRIPTION
**Pull request by KellyThomas**
@exts I saw @Chaosus documenting this method in https://github.com/godotengine/godot-docs/pull/1441 and thought it should be used here.

### CODE REVIEW

**Comment by Chaosus** [comment]
Note you should also mark method `async` in order to correct work

**Comment by cbscribe** [comment]
I don't have Mono set up atm. Can someone confirm this works as expected?

**Comment by paulloz** [comment]
Works for me in 3.0.2

**Comment by exts** [comment]
Works, maybe add a comment explaining what ToSignal does for the reader.

**Comment by exts** [comment]
> However there is no equivalent explanation of yield for GDScript users, so I question if this is the right place.

I kind of disagree with that mentality personally, but the change works and it can be merged

**Pull request merged**
