### PR TITLE
Fix description of adding class icon in 3.4

### PR DESCRIPTION
**Pull request by timothyqiu**
`@icon` annotation is a 4.0 feature.

### CODE REVIEW

**Comment by timothyqiu** [comment]
CI complains about `getting_started/scripting/c_sharp/index` invalid in `classes/class_csharpscript.rst` :(

**Comment by raulsntos** [comment]
Seems 0c0e652bd77ed0b90bbdda6ac08228ccd9264e96 broke it, the referenced file does not exist it should be `tutorials/scripting/c_sharp/index` but completely unrelated to this PR

**Comment by skyace65** [comment]
> Seems [0c0e652](https://github.com/godotengine/godot-docs/commit/0c0e652bd77ed0b90bbdda6ac08228ccd9264e96) broke it, the referenced file does not exist it should be `tutorials/scripting/c_sharp/index` but completely unrelated to this PR

@akien-mga. Not sure how this happened. That classref page in the master, 3.4 and 3.x branch of the godot repository have the right links

**Comment by mhilbrunner** [comment]
cc @akien-mga :P

**Comment by mhilbrunner** [comment]
Hey, our CI is fixed now for the 3.4 branch - could you please rebase/push to get a new build? Thanks :)

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Pull request merged**
