### PR TITLE
Update GDScript warning system to use `@warning_ignore`

### PR DESCRIPTION
**Pull request by rarysson**
Fix https://github.com/godotengine/godot-docs/issues/8145. 

Update the GDScript warning system doc to use annotation to ignore a warning instead of a comment.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Looks good to me, please resolve merge conflicts so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

PS: In the future, please use the Default theme for screenshots (the one with a dark blue background instead of a gray background). This is to ensure visual consistency across screenshots in the official documentation.

**Comment by mhilbrunner** [comment]
@rarysson Could I bother you to re-take those screenshots with the default theme, and also to convert the PNG files to WebP while you're at it (we're in the process of moving the docs repository over to WebP, see [image creation guidelines](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html))?

Otherwise this looks good to go for me, thanks for contributing! And if you don't have time for further work that is fine too, just let me know :)

**Comment by rarysson** [comment]
@mhilbrunner done!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
@rarysson Amazing first contribution, helping out with outdated images is always welcome as its so much work :) Thanks for taking the time to contribute and make those changes too. 🎉Merged.

**Pull request merged**
