### PR TITLE
Update exporting for android images

### PR DESCRIPTION
**Pull request by skyace65**
Updates the images in the exporting for android and custom builds for android page. All images have gone through png compression. Also updated an instruction to be more clear.

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
The Editor Settings screenshot should be made with a *fresh* [`editor_settings-3.tres` file](https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html) to prevent the obsolete Adb and Jarsigner settings from showing up. See https://github.com/godotengine/godot/issues/22099.

Other than that, this looks good to merge.

**Comment by skyace65** [comment]
Fixed. Since adb and jarsigner were removed and it's just the android sdk now, can #3373 be closed now?

**Comment by skyace65** [comment]
Replaced another android image.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Pull request merged**
