### PR TITLE
Autoload style fix

### PR DESCRIPTION
**Pull request by bfedie518**
**Version**
3.4 and later

**Issue**
The example scripts on the [Singletons (AutoLoad)](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html) page used pascal case instead of snake case as recommended by the [style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html).

**Fix**
Rename scripts to snake case in text, images, and the included project file.

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
`Global.tscn` should also become `global.tscn`.

**Comment by bfedie518** [comment]
Changed Global.tscn to global.tscn.  I also changed the scenes in the example file.

**Review by mhilbrunner — APPROVED** [review]

**Comment by Vennnot** [comment]
This can be merged now, no?

**Comment by Piralein** [comment]
This PR was superseded by #6851 and some others. All images were updated, the zip file removed and the page changed to use snake_case.

Sorry for this :/
Thank you for your contribution nevertheless!

**Pull request closed without merging**
