### PR TITLE
Add a page on making a UI controller/keyboard navigable (3.4)

### PR DESCRIPTION
**Pull request by skyace65**
PR #5345 for the 3.4 branch.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
You missed to include the ` tutorials/ui/img/focus_settings.png` image.
I'm checking the CI error, seems to be an issue somewhere. Will investigate :)

**Comment by mhilbrunner** [comment]
CI should be fixed, this needs a rebase for it to include the fix and to re-run :) see https://github.com/godotengine/godot-docs/pull/5362

**Comment by skyace65** [comment]
Fixed.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Pull request merged**
