### PR TITLE
fix an error about alpha value

### PR DESCRIPTION
**Pull request by guohongci**

### CODE REVIEW

**Comment by Calinou** [comment]
The current text is already correct: `Color(1.0, 1.0, 1.0, 1.0)` is a fully opaque white, not black.

**Comment by guohongci** [comment]
Oh, I thought it's about the alpha color, like in Photoshop's alpha channel view. Cuz from white to white is a little bit confusing.

**Comment by akien-mga** [comment]
It's like in Photoshop or any image editing software, alpha is not a color but the opacity channel. This examples goes from full opacity white to transparent white (opacity 0).

**Comment by guohongci** [comment]
For a coder that makes perfect sense, but for an artist who paints on the alpha channel a lot, it's also a greyscale map.

What bothers me was the wording made me focused on the difference between color WHITE and color PURE WHITE which also fully transparent. Again, I know it all makes sense for coders, I just feel it would be better if it could make sense to everyone including people just started to try coding.

**Comment by akien-mga** [comment]
The "pure" word is superfluous yes, both are "pure" white (1, 1, 1) with different opacity.

**Pull request closed without merging**
