### PR TITLE
Add Martin Donald to tutorials.rst

### PR DESCRIPTION
**Pull request by JamesC01**
He has very high-quality godot shader tutorials.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by AThousandShips** [comment]
You need to remove the commits from the wrong branch by rebasing onto `master`

**Comment by JamesC01** [comment]
I'm using the github website, would it just be easier for me to delete the pull request and redo it correctly?

**Comment by AThousandShips** [comment]
Probably yes if you aren't using the desktop tools

**Pull request closed without merging**
