### PR TITLE
Angular and Linear Damp 

### PR DESCRIPTION
**Pull request by thygrrr**
The values are explained in more detail, with correct maths and important caveats highlighted.
The ranges are corrected, as 0..1 was not a good range at all. (in fact, 1 is already the default for 2D). The values are changed as "suggested" instead of "good", because they are very subjective.

Resolves https://github.com/godotengine/godot-docs/issues/8163

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

These changes needs to be done over [here](https://github.com/godotengine/godot), changing the generated files is not allowed, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html)

**Comment by thygrrr** [comment]
Oh crap sorry about that.

**Comment by thygrrr** [comment]
```xml
		<member name="physics/2d/default_angular_damp" type="float" setter="" getter="" default="1.0">
			The default angular damp in 2D.
			[b]Note:[/b] Good values are in the range [code]0[/code] to [code]1[/code]. At value [code]0[/code] objects will keep moving with the same velocity. Values greater than [code]1[/code] will aim to reduce the velocity to [code]0[/code] in less than a second e.g. a value of [code]2[/code] will aim to reduce the velocity to [code]0[/code] in half a second. A value equal to or greater than the physics frame rate ([member ProjectSettings.physics/common/physics_ticks_per_second], [code]60[/code] by default) will bring the object to a stop in one iteration.
		</member>
```

How do I use proper sphinx admonishments from here?

**Comment by AThousandShips** [comment]
It says it is generated at the very top of the document :)

See the instructions [here](https://docs.godotengine.org/en/latest/contributing/documentation/class_reference_primer.html)

**Comment by thygrrr** [comment]
Thank you for your kind advice, I've submitted PR https://github.com/godotengine/godot/pull/82950 instead. :)

**Pull request closed without merging**
