### PR TITLE
Deduplicates some text in fps_tutorial part 2

### PR DESCRIPTION
**Pull request by GrooveStomp**
There is some duplicated text in this section.
I opted for the text that more clearly explained the code in my mind.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thank you!

cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
Looks good to me. Thanks @GrooveStomp! 🙂

**Comment by mhilbrunner** [comment]
That was fast. Thanks, and thanks @GrooveStomp :) Congrats to your first Godot contribution!

**Comment by GrooveStomp** [comment]
Thanks!
Hopefully the first of many. :-)

**Pull request merged**
