### PR TITLE
Add C# Export page for 3.4 branch

### PR DESCRIPTION
**Pull request by skyace65**
3.4 branch version of #5219. Everything is exactly the same.

### CODE REVIEW

**Comment by skyace65** [comment]
The build issue isn't from this PR. It's from #5196 getting cherry picked

**Comment by Calinou** [comment]
> The build issue isn't from this PR. It's from #5196 getting cherry picked

I opened a PR to fix it: https://github.com/godotengine/godot-docs/pull/5244

**Comment by skyace65** [comment]
> 
> 
> > The build issue isn't from this PR. It's from #5196 getting cherry picked
> 
> I opened a PR to fix it: #5244

I think you submitted your PR to fix it the second after I submitted mine xD

**Comment by mhilbrunner** [comment]
Thanks for doing the work of porting this to 3.4 :)

**Pull request merged**
