### PR TITLE
Fix Orientation on Android

### PR DESCRIPTION
**Pull request by flofriday**
Following the Android instructions for exporting, results in an rotated
build. By specifying the Orientation option in the "Project Settings"
solves this bug.

Here is a example of the bug:
Bug

### CODE REVIEW

**Comment by Calinou** [comment]
There are merge conflicts, could you look into solving them, please? Thanks in advance :slightly_smiling_face:

**Comment by flofriday** [comment]
> There are now merge conflicts. Could you look into solving them, please? Thanks in advance 

Sorry for that inconvenience, while a worked on this PR another PR #3011 got merged, which resulted in a conflict. 
The conflict should now be resolved 🙂.

**Comment by Calinou** [comment]
Thanks! Congratulations for your first contribution :tada:

**Comment by flofriday** [comment]
Thank you, I am so happy to finally being able to contribute to a bigger project.

🎊☺️🎉

**Pull request merged**
