### PR TITLE
Added line about android studio

### PR DESCRIPTION
**Pull request by melvyniandrag**
I was confused by what SDK meant. The link takes  you to a page offering Android Studio or SDK platform tools and it wasn't immediately clear to me what needed to be downloaded.

### CODE REVIEW

**Comment by Calinou** [comment]
The full Android Studio IDE is unnecessary for compiling Godot; the command-line tools are enough. The Gradle build system will automatically download missing SDK components, so you only need to download the SDK and NDK after accepting the license by creating a file. See [this script](https://github.com/Calinou/godot-builds-ci/blob/master/scripts/gitlab-ci/build/android.sh) for an example of automating Android builds.

**Comment by melvyniandrag** [comment]
So maybe the doc should recommend just installing the command line tools then. As it's currently worded, it wasn't immediately clear to me what to install. The doc says to download the sdk, but the download page says "android studio" and "sdk command line tools". Either way, I just figured and extra sentence with more specificity was better.

**Comment by akien-mga** [comment]
@Calinou Would you have a proposal for clearer instructions regarding what needs to be downloaded and installed exactly? Getting the Android buildsystem setup seems to be a major pain point for many users.

**Comment by akien-mga** [comment]
Superseded by #1994.

**Pull request closed without merging**
