### PR TITLE
Add Windows PowerShell example in Compiling with PCK encryption key

### PR DESCRIPTION
**Pull request by Calinou**
This can be cherry-picked to `3.3` without conflicts.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by pycbouh** [comment]
To my understanding this will override system or user defined environmental variable. Therefore this can be destructive.

**Comment by akien-mga** [comment]
Does it override for the whole system, or just for the current shell? If it's just the current shell then it's the expected behavior, `export` on Unix and `set` on cmd do the same.

**Comment by Calinou** [comment]
> To my understanding this will override system or user defined environmental variable. Therefore this can be destructive.

In cmd, `setx` must be used to set the environment variable in a persistent manner. I'm not sure what's the powershell equivalent, but I doubt it's `$env`.

**Comment by pycbouh** [comment]
Yep, okay, sorry. Some wording on the usage of `$env` was confusing me, but the official docs are pretty clear that this is not a persistent change:

> When you change environment variables in PowerShell, the change affects only the current session. This behavior resembles the behavior of the `Set` command in the Windows Command Shell and the `Setenv` command in UNIX-based environments. To change values in the Machine or User scopes, you must use the methods of the **System.Environment** class.

I've experimented to make sure and it didn't seem to do anything destructive to the user or machine scope.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2 and 3.3.

**Pull request merged**
