### PR TITLE
Wrong word in documentation, key concepts overview. Godot 4.1

### PR DESCRIPTION
**Pull request by VictorDev200**

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for contributing 

You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by VictorDev200** [comment]
> Thank you for contributing
> 
> You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes), you've correctly targeted `master` but your branch is based on 4.1 instead, incorrectly

I didn't realize that i choose 4.1, what should i do now?

**Comment by AThousandShips** [comment]
If you can use the command line you can [rebase it](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), otherwise you can just open a new one and close this one

**Comment by AThousandShips** [comment]
Superseded by: #7806

**Pull request closed without merging**
