### PR TITLE
Update import hints documentation

### PR DESCRIPTION
**Pull request by Shatur**
* Add 4 new import hints for shapes from the https://github.com/godotengine/godot/pull/39105.
* Add mising material hints.

Can be merged only after https://github.com/godotengine/godot/pull/39105.

### CODE REVIEW

**Comment by balloonpopper** [comment]
Can you please resolve the merge conflict @Shatur95 ?
I haven't looked at the code to check that the options you've documented are correct, however this sentence
"Node names that have this suffix and its children will be removed at import time"
doesn't make sense grammatically. 
I would suggest
"Node names that have this suffix, and any child nodes they have, will be removed at import time"

**Comment by Shatur95** [comment]
Thank you, I'll fix and resolve conflicts in the evening!

**Comment by Shatur95** [comment]
Done!

**Comment by balloonpopper** [comment]
@Shatur95 It reads fine to me from an English perspective. Note it's now failing the Sphinx build so you might need to take a look at that, and it's pending godotengine/godot#39105.

**Comment by Shatur95** [comment]
How can I fix [this](https://github.com/godotengine/godot-docs/runs/1393145894?check_suite_focus=true#step:5:2013) warning? I'm new to Sphinx :)

**Comment by Shatur95** [comment]
Oh, got it. It was because `SpatialMaterial` was renamed to `BaseMaterial3D` in 4.0.

**Review by balloonpopper — APPROVED** [review]

**Comment by Shatur95** [comment]
While resolving recent conflicts with master, I accidentally pushed the branch without changes and GitHub automatically closed my PR. Reopened #4507.

**Pull request closed without merging**
