### PR TITLE
Update using_tilemaps.rst

### PR DESCRIPTION
**Pull request by bitbutter**
Many changes.

### CODE REVIEW

**Comment by clayjohn** [comment]
Not sure this information is relevant in 3.1 anymore. There is an entirely new tileset editor.

**Comment by bitbutter** [comment]
Ah I see. I suppose it should be removed for the 3.1+ versions. But I'm not sure how to do that.

**Comment by akien-mga** [comment]
For future commits, please use a more descriptive commit title which explains (briefly) what the commit changes. The default "Update filename" proposed by the GitHub editor doesn't say anything useful.

**Comment by akien-mga** [comment]
This page should indeed be completely rewritten for the new 3.1+ workflow. The old workflow is still valid though, so I guess it doesn't hurt to merge this cleanup in the meantime.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
