### PR TITLE
Add code examples for sound playing in the "first 2d game" tutorial

### LINKED ISSUE #8003: CS code missing for adding music
**Your Godot version:**
4.1.1
**Issue description:**
The tutorial is overall very beginner friendly, but on the last bit it uses $Music.play() and while I've been trying to compare the GDScript to C# to try to understand how to translate it into C# I'm not quite proficient enough in both to do that yet. (My goal with this was to get practice using C#). 
**URL to the documentation page:**
https://docs.godotengine.org/en/stable/getting_started/first_2d_game/07.finishing-up.html
If you know how to fix the issue you are reporting please
consider opening a pull request. We provide a tutorial on
using git here: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html,
writing documentation at https://docs.godotengine.org/en/stable/community/contributing/docs_writing_guidelines.html
and contributing to the class reference here: https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html

### PR DESCRIPTION
**Pull request by jynus**
The last step in "Your first 2D game" (Finishing up) lacks code or directions in general for C#. Add a short snippet that can be used for reference and for copy and paste.

Fixes #8003

### CODE REVIEW

**Comment by jynus** [comment]
Let me amend with the C++ version, too.

**Review by raulsntos — APPROVED** [review]
Looks good to me, thanks.

Note that there's another PR about this: https://github.com/godotengine/godot-docs/pull/7923. My personal preference is this PR (#8017) because I feel like the code snippets give more context since they also contain the method declaration. Also, this PR includes C++.

**Comment by jynus** [comment]
Thanks, no issue on which is merged- I can also rebase on top of that if it gets merged. As long as #8003 is fixed no matter which one is chosen :-D.

**Review by skyace65 — APPROVED** [review]
I agree with Raul, just want to get a third opinion before merging one of these.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I agree with the above. :) Merged. Thanks for contributing!

**Pull request merged**
