### PR TITLE
Update Android compiling documentation

### PR DESCRIPTION
**Pull request by m4gr3d**
Updates the `compiling for Android` documentation to reflect the build changes added by [PR #32269](https://github.com/godotengine/godot/pull/32269).

### CODE REVIEW

**Comment by m4gr3d** [comment]
Fixes issue #2773

**Comment by skyace65** [comment]
Do you think it's worth including the information you have under notes in the engine PR in the documentation?

**Comment by clayjohn** [comment]
My hero!

**Comment by akien-mga** [comment]
Looks like nobody is merging PRs if I'm not looking... :D

Sorry for the delay. Changes look good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
