### PR TITLE
Update 2D animation tutorial to show how to use a sprite sheet with AnimatedSprite

### PR DESCRIPTION
**Pull request by robinlamb**
I have updated the 2D animation tutorial to include how to animate from a sprite sheet with Animated Sprite.  I have included screen shots to show how to do this, and have changed the old wording in the tutorial that makes it sound as if you can only animate with a sprite sheet using the AnimationPlayer.  I have also clarified that you can use an AnimationPlayer together with an AnimatedSprite.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks!

**Comment by robinlamb** [comment]
Thank you!  It is nice to see my update to the tutorial used.

**Comment by nikhilCad** [comment]
@Calinou can it be added to 3.2 docs as well, not just latest?

**Comment by Calinou** [comment]
@nikhilCad Akien is usually the one who cherry-picks relevant commits to the `3.2` branch.

**Pull request merged**
