### PR TITLE
Fix inline code going out of bounds

### PR DESCRIPTION
**Pull request by hpnrep6**
Fixes godotengine/godot-docs#4981. Puts the inline code block in a table so that it stays within the page in [Creating iOS plugins](https://docs.godotengine.org/en/stable/tutorials/platform/ios/ios_plugin.html).

## Before
Screenshot from 2021-06-17 08-39-19

## After
Screenshot from 2021-06-17 08-39-51

### CODE REVIEW

**Comment by pycbouh** [comment]
Why a table? If this to be a solution, we have a way to define code blocks.

**Comment by hpnrep6** [comment]
> Why a table? If this to be a solution, we have a way to define code blocks.

Wasn't sure if the original format of the line was to be kept. Yes, a code block will also work.

**Comment by hpnrep6** [comment]
> Why a table? If this to be a solution, we have a way to define code blocks.

With code blocks, it looks like:
Screenshot from 2021-06-17 09-37-34
or
Screenshot from 2021-06-17 09-39-13

In my opinion, it might cause some confusion by being inconsistent with the other flags listed in the section. (but it may be a solution if we're staying consistent with the other documentation?)

**Comment by pycbouh** [comment]
Well using a table there looks weird and is a straight up hack, so I wouldn't go that direction either way.

An ideal look would be to wrap the line on whitespace but not on punctuation (so that `[DeviceLibrary].a` doesn't break up, for example). But I'm not sure this is achievable as it would be mostly up to the browser if we allow any sort of wrapping.

**Comment by mhilbrunner** [comment]
Agree a table is not the way to go for this. Code blocks may not be optimal for this, but IMO still better than a table.

**Comment by hpnrep6** [comment]
I have made it so that it uses a code block instead.

**After**
Screenshot from 2021-07-07 23-39-49

**Comment by mhilbrunner** [comment]
Merged, and thank you!

**Comment by pycbouh** [comment]
From your screenshot the list formatting is now a bit broken. Points 3 and 5 have different indent than 4.

**Comment by hpnrep6** [comment]
Sorry, I think I included the wrong screenshot (that was for when there wasn't an empty line between :: and "For instance:". This is what it should look like.

Screenshot from 2021-07-08 11-24-10

**Comment by pycbouh** [comment]
Ah, great! Thank you.

**Comment by Calinou** [comment]
This can't be cherry-picked trivially to the `3.3` branch. Please open a separate PR against the `3.3` branch :slightly_smiling_face:

**Pull request merged**
