### PR TITLE
Update android SDK platform requirement

### LINKED ISSUE #6024: Update Android SDK platform and build tools version requirements
### Godot version

3.4.5-stable

### System information

Windows 11

### Issue description

On https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#doc-exporting-for-android, it says that for Android plugins, we should install Android SDK Platform 29.

Now that Godot 3.4.5 targets Android 31, should the documentation be updated to say Android SDK Platform 31, or is this not necessary?

Thanks 🙂  (Sorry, still trying to get my plugin working)

### Steps to reproduce

See above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by skyace65**
Updates the required version to 31. I believe this should be cherry pickable. Closes #6024.

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by neoncube2** [comment]
@skyace65 Thanks for the quick fix! :)  I think this change should also be applied to the 3.5 branch.

For the 3.4 branch, not sure if `Android SDK Platform` should be 29 or 30.

**Comment by neoncube2** [comment]
@skyace65 The `sdkmanager` command on the same page should probably also be updated to use `Android SDK Platform` 31 🙂

Currently:
```c#
sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"
```

Modified:
```c#
sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;30.0.3" "platforms;android-31" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"
```

**Comment by mhilbrunner** [comment]
Note for cherry-picking: if this is picked, https://github.com/godotengine/godot-docs/pull/6035 needs to be as well.

**Comment by Calinou** [comment]
Cherry-picked to the `3.5` and `stable` branches.

**Pull request merged**
