### PR TITLE
Fixed qa link

### LINKED ISSUE #8155: Link to the official Questions & Answers site is outdated
Godot 4.1 Docs

Link to the official [Questions & Answers](https://godotengine.org/qa/) site is outdated. it displays a 404 error when entered.

[**URL to the documentation page:**](https://docs.godotengine.org/en/stable/getting_started/introduction/learning_new_features.html#learning-with-the-community)

### PR DESCRIPTION
**Pull request by ShatReal**
Closes #8155

Since the url changed from qa to ask

### CODE REVIEW

**Comment by skyace65** [comment]
Thanks!

**Comment by YuriSizov** [comment]
We should update all occurrences.

```
5 results - 5 files

about/introduction.rst:
  30  especially the Godot `Discord`_ community and
  31: `Q&A <https://godotengine.org/qa/>`_.
  32  

community/channels.rst:
  14  
  15: - `Official Godot Questions & Answers <https://godotengine.org/qa/>`_
  16  

contributing/documentation/updating_the_class_reference.rst:
  74  You can still look at the methods' implementation in Godot's source code on GitHub.
  75: If you have doubts, feel free to ask on the `Q&A website <https://godotengine.org/qa/>`_
  76  and `Godot Contributors Chat <https://chat.godotengine.org/>`_.

getting_started/introduction/learning_new_features.rst:
  87  The best place to ask questions and find already answered ones is the
  88: official `Questions & Answers <https://godotengine.org/qa/>`_ site. These
  89  responses show up in search engine results and get saved, allowing other users

tutorials/export/exporting_for_android.rst:
  69  
  70: This will create a ``debug.keystore`` file in your current directory. You should move it to a memorable location such as ``%USERPROFILE%\.android\``, because you will need its location in a later step. For more information on ``keytool`` usage, see `this Q&A article <https://godotengine.org/qa/21349/jdk-android-file-missing>`__.
  71  
```

In general when such fixes are made it's worth checking if there is more to be fixed than just the highlighted example.

**Comment by ShatReal** [comment]
Oh okay i'll keep that in mind

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1

**Pull request merged**
