### PR TITLE
Update instancing.rst

### PR DESCRIPTION
**Pull request by pathunstrom**
The bounce attribute has a range of 0.0 to 1.0 as of at least 3.2 (there's no range mentioned in 3.1)

0.5 is arbitrarily selected, but performs does increase the bounce significantly.

Example rendering:

image

### CODE REVIEW

**Review by Piralein — APPROVED** [review]
If you like you can also update the image `instancing_property_bounce_updated.png` beneath the text with the new value. (as .webp file, see [docs_image_guidelines)](https://docs.godotengine.org/en/stable/contributing/documentation/docs_image_guidelines.html#format-conversion)

**Comment by pathunstrom** [comment]
Will get that screen shot in today.

**Comment by pathunstrom** [comment]
Screenshots updated. Included a screenshot of a locally rendered copy of the docs.

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

I've squashed and merged this one, but in the future we like to keep things to 1 commit. If you don't know how to do that we have information [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request).

**Comment by mhilbrunner** [comment]
Cherry-picked to 3.6 in https://github.com/godotengine/godot-docs/pull/9936.

**Pull request merged**
