### PR TITLE
[3.3] Update instructions for compiling for Android

### PR DESCRIPTION
**Pull request by m4gr3d**
This follows the updates to the Android buildsystem in https://github.com/godotengine/godot/pull/44949

### CODE REVIEW

**Comment by Ansraer** [comment]
We should probably mention the minimum required API level somewhere.

**Comment by m4gr3d** [comment]
@Ansraer Did you run into issues related to the minimum API level?

**Comment by m4gr3d** [comment]
@Calinou @akien-mga This PR was updated as well, but we need to wait until `3.2.4` is stable before merging it.

**Comment by akien-mga** [comment]
Note to self: Should be changed to target `3.3` branch once created.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
