### PR TITLE
Spelling corrections.

### PR DESCRIPTION
**Pull request by growingbrain**
Spelling correction for the 2d navigation overview page.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
It looks like there are 15 more uses in the navigation docs, while everywhere else in the docs is already using `synchroni**z**e`. Would you be willing to edit the other occurences as well for consistency? Thanks for contributing!

sync

**Comment by growingbrain** [comment]
My changes were not case-sensitive, I will fix them.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
@growingbrain Is the second author on that commit intended? If so, I'm happy to merge this, looks good, thanks for fixing the other occurences!

**Comment by growingbrain** [comment]
> @growingbrain Is the second author on that commit intended? If so, I'm happy to merge this, looks good, thanks for fixing the other occurences!

No issue at all.  I accidently mixed up my git users.

**Comment by mhilbrunner** [comment]
Alright, merged! Thanks for taking the time to contribute :)

**Pull request merged**
