### PR TITLE
Android in app purchase tutorial

### PR DESCRIPTION
**Pull request by vinod8990**
Tutorial on using the provided android in app purchase module with the demo interface iap.gd

### CODE REVIEW

**Comment by ScotFlux** [comment]
You buddy have just got Godot 🏅 and 🏆 as well. Congratulations!

**Comment by henriquelalves** [comment]
This is a very important piece of information that the docs are really lacking, it should be there as soon as possible. Monetization is a very big deal, people that come looking for it on Godot could be very upset if they don't find anything related for Android.

**Comment by her001** [comment]
@vinod8990 Before this is merged, could you please fix the consistency issues mentioned by @StraToN?

**Comment by vinod8990** [comment]
OK. I'll check it in a couple of days

On 21-Feb-2017 8:58 AM, "Andrew Conrad" <notifications@github.com> wrote:

@vinod8990 <https://github.com/vinod8990> Before this is merged, could you
please fix the consistency issues mentioned by @StraToN
<https://github.com/StraToN>?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot-docs/pull/302#issuecomment-281235567>,
or mute the thread

**Comment by vinod8990** [comment]
Updated all "iap" to "IAP".
As I am not familiar with this git markdown, I don't know what @StraToN meant by "missing semi-colons before urls".

**Comment by StraToN** [comment]
@vinod8990 I think I explained the problem wrongly.
IIRC, Sphinx won't automatically convert URLs to links, that is: 
```rst
This is my link to Godot : http://www.godotengine.org/ 
```
will appear as plain text 
```rst
This is my link to Godot : http://www.godotengine.org/ 
```

What we want here is an external link, which has to be defined with references:
```rst
This is my link to Godot_.
...
...

.. _Godot: http://www.godotengine.org/
```

**Pull request merged**
