### PR TITLE
Fix bad indentation in some GDScript examples

### PR DESCRIPTION
**Pull request by antoniotorresm**

### CODE REVIEW

**Comment by NathanLovato** [comment]
You don't want mixed tabs and spaces. Please use the script editor's option to convert everything to spaces

**Comment by Calinou** [comment]
> You don't want mixed tabs and spaces. Please use the script editor's option to convert everything to spaces

The [GDScript style guide](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) recommends using tabs, so these should be used in all demo projects.

**Comment by antoniotorresm** [comment]
Changed spaces for tabs on all examples. For some reason tab width is 8 spaces in some parts (see `match` examples).

**Comment by Calinou** [comment]
I just realized this is the documentation repository, not the demo projects repository… I apologize for the confusion.

If I'm not mistaken, spaces should be used since they're used for indenting stuff other than code in rST (otherwise, we would end up with tab and space indentation in the same file).

**Comment by akien-mga** [comment]
Indeed, this is a Python-based documentation generator and uses space for indentation by convention. Tabs are also valid, but we chose spaces to be consistent.

Sorry about the confusion leading to extra work.

**Comment by akien-mga** [comment]
Fixed on the whole repo with a0e32ac0.

**Pull request closed without merging**
