### PR TITLE
Improve physics doc

### PR DESCRIPTION
**Pull request by ombre5733**
- Fixed some typos.
- Added some additional text.
- Reordered sections: StaticBody2D, KinematicBody2D and RigidBody2D belong together as well as CollisionShape2D and CollisionPolygon2D.

### CODE REVIEW

**Comment by akien-mga** [comment]
Same here, you should remove commits 94c5166 and 4dd735d from this branch using `git rebase -i HEAD~3`.

**Comment by ombre5733** [comment]
Done.

**Comment by akien-mga** [comment]
The reordering is a good idea, but I'd go a step further, as it's still somewhat unclear. Adding another level of heading would likely make things clearer:
```
Collision objects
-----------------

// intro, present the typical outline for collision objects with:
- Any CollisionObject2D
  * CollisionShape2D or CollisionPolygon2D

Collision shapes
~~~~~~~~~~~~~

CollisionShape2D
^^^^^^^^^^^^^^

CollisionPolygon2D
^^^^^^^^^^^^^^

Triggers
^^^^^^^^

CollisionObject2D
~~~~~~~~~~~~

StaticBody2D
^^^^^^^^^^^^^^

KinematicBody2D
^^^^^^^^^^^^^^^

RigidBody2D
^^^^^^^^^^^^^
```

Though in a second step it might be worth moving all this + the collision reporting section to its own tutorial page, to make that "introduction" clearer.

**Comment by ombre5733** [comment]
@akien-mga Ok, this change will need some more time. 

When we are at it, I would like to clarify more things in the documentation:

- Why is there `StaticBody2D` and `KinematicBody2D`, when the same functionality can be achieved with the `Mode` flag of `KinematicBody2D`? Reading just the docs, having just a `KinematicBody2D` with appropriate mode would be sufficient.
- Why is there no `CharacterBody2D` but a flag for it in `KinematicBody2D`? The table near the end shows a `CharacterBody` but Godot has none, so this needs to be fixed as well.
- Does it make sense that `Trigger` is a flag of shapes rather than the `CollisionObject2D`? I always look at the object first to set this flag only to remember later on that I have to change the shape/polygon.

**Comment by akien-mga** [comment]
Let's merge this one as is and maybe move the discussion to a separate issue, @StraToN is working on a refactoring of the way the docs are organized, so files will be moved around a bit, which would introduce conflicts in pending PRs.

Regarding your questions, I will answer soon-ish :)

**Pull request merged**
