### PR TITLE
Changes to tutorials/scripting/gdnative/gdnative_cpp_example.rst

### PR DESCRIPTION
**Pull request by Karmavil**
Hi, no native English speaker here, I followed the guidelines after a quick review feel free to improve what you see.
I placed a WARNING at the 3rd commit please pay attention.
Thanks, nice work with the docs ;)

### CODE REVIEW

**Comment by Karmavil** [comment]
Consider adding the folder name `src` at line 400 in the second commit before approve

**Comment by Calinou** [comment]
Sprite was renamed to Sprite2D in Godot 4.0, so the new node name shouldn't be reverted back.

**Comment by Karmavil** [comment]
> Sprite was renamed to Sprite2D in Godot 4.0, so the new node name shouldn't be reverted back.

I know but we are talking about godot 3.x

**Comment by Calinou** [comment]
> I know but we are talking about godot 3.x

This pull request targets the `master` branch, which documents the upcoming Godot 4.0. Documentation for the stable `3.x` branch should be opened against this repository's `3.4` branch instead.

**Comment by Karmavil** [comment]
> > I know but we are talking about godot 3.x
> 
> This pull request targets the `master` branch, which documents the upcoming Godot 4.0. Documentation for the stable `3.x` branch should be opened against this repository's `3.4` branch instead.

Roger that. Thank you for the link and review

**Pull request closed without merging**
