### PR TITLE
Update docs on input right -> ui_right

### PR DESCRIPTION
**Pull request by Murtagy**

### CODE REVIEW

**Comment by Calinou** [comment]
You need to set up input actions as described in that tutorial. [Someone already opened a pull request to change the actions to the default hardcoded ones](https://github.com/godotengine/godot-docs/pull/3465), but we'd prefer not encouraging it as it's considered bad practice to use "reserved" inputs for gameplay purposes.

**Comment by ulvido** [comment]
this is confusing for the newcomers. I was in the [2D movement overview](https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html) part and I thought the code was not working.

**Comment by cbscribe** [comment]
How is it confusing? If you follow the directions at the beginning of the tutorial, which *tell* you to set up the inputs, then the rest of the tutorial works fine.

**Comment by ulvido** [comment]
great docs btw. you can just understant the document is not working properly at that part if there is this issue on github. You can assume some people searched the problem and saw this topic and sad "ah I found the solution" and leaved.

image

it is not clear which refers which.  this "left" or that "left" or something else?
or can I write Input.is_action_pressed('a'):
how can a newbea bind that information together. the "note" explains some but it's placed at the bottom of the topic. it should be uppper so people can understand before strugle. also according to note check my setup actions and do what? note should be more explaining. my setup actions are correct. the "code" should be fixed acording to actions. 

and a reminder doc picture is outdated for v3.2.3. it is not people see. this is the picture at docs:
image

**Pull request closed without merging**
