### PR TITLE
Add note around mob velocity to direct users to next section

### PR DESCRIPTION
**Pull request by Starkandco**
The idea of mob completion often creates an expectation of movement. Note added to encourage users to test and move on to next section.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by Starkandco** [comment]
> Thank you for your contribution!
> 
> You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).
> 
> If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

Apologies I was away, thank you for updating the branch!

**Comment by AThousandShips** [comment]
I haven't fixed it for you yet, if you want I can when I have the time later today :)

**Comment by Starkandco** [comment]
> I haven't fixed it for you yet, if you want I can when I have the time later today :)

I will do my best to do it on my lonesome but I might need that help, thank you :$

**Comment by AThousandShips** [comment]
Good luck, see the second link above, it's not very complicated

**Pull request closed without merging**
