### PR TITLE
Simplify the first 2 sections of the class reference contribution guide

### PR DESCRIPTION
**Pull request by NathanLovato**
- rewrite and simplify the first paragraphs
- merge split lines back into paragraphs

### CODE REVIEW

**Comment by akien-mga** [comment]
Please use a more meaningful commit log, "Update $filename" is what GitHub's editor suggests, but that's a pointless log message. What I want to know is what changed, not that stuff changed :)

It would also be good if you could rebase to get rid of the "Merge pull request" commit, which looks like PR-ception ;)

See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by NathanLovato** [comment]
Just gimme a moment, I didn't know this would create 2 commits. Just tried to rebase and I managed to mess up the local repo. Trying again now ;)

**Comment by NathanLovato** [comment]
When I try to rebase, I can see `0f69cb3` but `3dbb4a1` (pull request from the branch on the forked repo) is nowhere to be found. I can't fixup this one it seems. Do you know how to fix it? Worst case scenario I'll close, branch again and do a single, clean commit.

**Comment by akien-mga** [comment]
Well it's good, when you rebase the merge commit should go away automatically as it's no longer necessary.

**Comment by NathanLovato** [comment]
Good to know, learned something! Anything else to do?

**Comment by NathanLovato** [comment]
Closing this PR.
Did a complete rewrite, and a cleaner PR with a single commit. Not sure why this one won't update - same repo, same branch: https://github.com/godotengine/godot-docs/pull/460

**Pull request closed without merging**
