### PR TITLE
Removed "Constants" paragraph from migrating-to shader page

### PR DESCRIPTION
**Pull request by Chaosus**
Since there is no difference from GLSL already.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
For the `3.2` branch, I guess we should not remove it but maybe edit the text a bit to mention which types of constants are supported (IIRC we support some but not all)?

**Comment by Anutrix** [comment]
There is also a mention about using uniforms instead of constants in Macros Section below this. Maybe that needs to be changed too.

**Comment by Chaosus** [comment]
In 3.2 branch arrays constants are not supported + I also detected that constants are not supported as function parameters like:
```
void test(const int t) {
}
```
I want to work on this soon...

**Pull request merged**
