### PR TITLE
Update changed signals

### PR DESCRIPTION
**Pull request by flametime**
Old signals in doc does not exist

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by flametime** [comment]
Its my first pull request ever, am i do everything correct?

**Comment by AThousandShips** [comment]
No you need to fix your branch, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch), it still contains a commit from the wrong branch

**Comment by AThousandShips** [comment]
Fixed the branch for you 🙂

**Review by mhilbrunner — APPROVED** [review]
For reference, it seems these were changed in https://github.com/godotengine/godot-google-play-billing/pull/36.

**Comment by mhilbrunner** [comment]
Merged. Thanks and congrats on your first merged contribution! Also thanks to ATS for the branch fix. 🙏

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2.

**Pull request merged**
