### PR TITLE
Update gui_using_fonts.rst

### PR DESCRIPTION
**Pull request by dustdfg**
Add link to *open-source* web based alternative of BMFont editor

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by AThousandShips** [comment]
Also BMFont is open source

**Comment by dustdfg** [comment]
> Also BMFont is open source, do you mean _another_ open source one?

Yeah bad wording... I would say a very bad wording because I meant that BMFont is for windows only (as I know) and to run it on the linux you need something like wine... But this is a web tool which is run in browser

**Comment by AThousandShips** [comment]
Would you like me to fix your branch for you?

**Comment by dustdfg** [comment]
> Would you like me to fix your branch for you?

Are you about redirecting from 4.2 branch into master? I though I did it. If you are about something another my answer is yes because I even don't know what you are about

**Comment by AThousandShips** [comment]
I'm about the thing I explained above 🙂 see all the commits that aren't yours, you didn't make those 96 commits

**Comment by dustdfg** [comment]
> I'm about the thing I explained above 🙂 see all the commits that aren't yours, you didn't make those 96 commits

Ahh... Ok. I opened the link from your comment. I think I can do myself at least to try

**Comment by AThousandShips** [comment]
I'd remove the "open-source" part, unless you also add it to the main part, as BMFont is open-source, it's only BMGlyph that isn't, and I don't think it matters to specify the difference here

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Pull request merged**
