### PR TITLE
5373 - Step by step instancing example in zip file updated to new annotation style

### PR DESCRIPTION
**Pull request by ueco-jb**
closes https://github.com/godotengine/godot-docs/issues/5373

It changes line in:
`getting_started/step_by_step/files/instanting.zip/Main.gd`
```gdscript
- export (PackedScene) var Ball
+ @export var Ball: PackedScene
```

### CODE REVIEW

**Comment by Calinou** [comment]
I think we should remove this ZIP file and point to the demo project in https://github.com/godotengine/godot-demo-projects instead. This would avoid storing ZIP files within the documentation, which should be avoided for various reasons.

**Comment by ueco-jb** [comment]
@Calinou I agree in general. 
Although in `godot-demo-projects` there is a similar `instacing` project: [Instancing Demo](https://github.com/godotengine/godot-demo-projects/tree/master/2d/instancing)
Should:
- this step by step instansing page reflect (in code snippets, for example) already existing example,
- `Instancing Demo` be replaced by content of this `instanting.zip`
- new directory in `godot-demo-projects` be created, which would point to all `.zip` files from `getting_started`?

Honestly I'd prefer 3rd option, because first option is kind of more complicated then `instancing.zip`, and it'd be a shame to just remove `Instancing Demo` as well.

**Comment by ueco-jb** [comment]
@Calinou ?

**Comment by Calinou** [comment]
@ueco-jb Since demos haven't been updated for Godot 4.0 yet, I would prefer we wait for 4.0 to be more stable to start upgrading all demos to Godot 4.0.

**Comment by skyace65** [comment]
Superseded by #7222

**Pull request closed without merging**
