### PR TITLE
First 3D Game update input-action screenshot to 4.2

### PR DESCRIPTION
**Pull request by Bamarin**
The [guide](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/02.player_input.html) mentions
> To add an action, write its name in the bar at the top and press Enter.

In the latest version there are multiple bars at the top, making it ambiguous to which bar it is referring to.
The updated image helps making it more obvious where to type the name of the action

### CODE REVIEW

**Comment by AThousandShips** [comment]
You need to change the reference to it where it's used, replacing the old file with the new ending

**Comment by Bamarin** [comment]
Thanks for the heads-up, I also adjusted the outline according to the guideline you linked :)

**Review by AThousandShips — APPROVED** [review]

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks! And congrats on your first merged PR!

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2 in https://github.com/godotengine/godot-docs/pull/9648.

**Pull request merged**
