### PR TITLE
Update RichTextEffect tutorial

### PR DESCRIPTION
**Pull request by RedMser**
- The code examples have been updated for 4.0 syntax (`@tool` and other API changes)
- The documentation now mentions that `class_name` is a required part for custom effects to show up in the inspector

I am not sure how the Matrix effect is supposed to work, so I simply made it compile by fixing up the API, but it looks wrong. It should probably be properly fixed [by its original creator](https://github.com/Eoin-ONeill-Yokai/Godot-RichTextEffect-SampleProject/blob/master/richtexteffects/matrix.gd).

Please check whether my reference to `install_effects` is correct, I don't have a set up where I can try how the rst looks like in the end.

_Bugsquad edit: closes https://github.com/godotengine/godot-docs/issues/3291_

### CODE REVIEW

**Review by skyace65 — COMMENTED** [review]
Ghost works, and Matrix works the same way it did in 3.x so I'd say it's fine. I can't get pulse to do anything though, your version or the 3.x version in 3.4.

**Comment by RedMser** [comment]
@skyace65 Pulse needs a color parameter, otherwise it does not do anything. Try the example usage in the code comment, it should work.

**Review by skyace65 — APPROVED** [review]
My bad, it's working perfectly. Also I checked and the reference to install effect should be correct, it's the same way other pages reference methods. Thanks for the PR!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Looks good, thanks for this! Maybe https://github.com/Eoin-ONeill-Yokai can have a look at it too just in case, but I'm going to merge it.

**Pull request merged**
