### PR TITLE
Moved certain tutorials to better-named subfolders from 'Misc'

### PR DESCRIPTION
**Pull request by Dar13**
Moved the tutorials as described in #1023, though I left the 'Misc' folder named as such.

Suggestions welcome, as always.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
This likely requires HTTP redirects @NathanLovato

**Comment by NathanLovato** [comment]
Just saw it, sorry for the delay. All good. Can you just fix the conflicts? Not sure where they came from. I can merge and add the redirects tomorrow.

**Comment by Dar13** [comment]
I'm not sure where the conflicts came from either, there weren't any conflicts when I merged master into my branch. Should be good to go now @NathanLovato

**Comment by NathanLovato** [comment]
Redirects added, thanks!
@akien-mga in these cases should I cherry pick straight to 3.0? Redirects affect all versions of the docs, right?

**Comment by akien-mga** [comment]
@NathanLovato Redirects affect all versions yeah, so cherry-picking sounds good.

**Comment by mhilbrunner** [comment]
Cherrypicked in https://github.com/godotengine/godot-docs/commit/203bcd1650f9e2020fdf8ef4b38f8e68e190b07d

**Pull request merged**
