### PR TITLE
Remove usages of "LTS"

### PR DESCRIPTION
**Pull request by tetrapod00**

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Very nice!

**Comment by tetrapod00** [comment]
Pushed a fix for a minor grammar mistake

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you!

**Comment by mhilbrunner** [comment]
Cherrypicked to 4.3 in https://github.com/godotengine/godot-docs/pull/10346.

**Pull request merged**
