### PR TITLE
Update Keywords to include class_name

### PR DESCRIPTION
**Pull request by arccoza**
Includes `class_name` in the keywords list, and updates the definition of `class`.

### CODE REVIEW

**Comment by Calinou** [comment]
@vnen Is this still relevant for Godot 4.0, or should this pull request's base branch be changed to `3.2`?

**Comment by vnen** [comment]
I added it in my PR: #3623 so this is only relevant for 3.2

**Comment by arccoza** [comment]
Would you like me to resubmit against 3.2?

**Comment by akien-mga** [comment]
Yeah that would be great :)

**Comment by arccoza** [comment]
Done in #4016.

**Pull request closed without merging**
