### PR TITLE
Add cubemap template images to Importing images

### PR DESCRIPTION
**Pull request by Calinou**
Images were generated using <https://github.com/Calinou/godot-cubemap-generator>.

I have two questions though:

- The X axis seems to be inverted when I display the cubemap using a sky shader. In the project linked above, I've had to swap the X+ and X- images' positions for the cubemap display to look correct in `example_cubemap_display.tscn` (the image is included in the repository).

- The whole cubemap texture is also flipped (for the X and Z axes) when displayed as a sky shader. You can notice this if you set the shader parameter in the sky shader of `example_cubemap_display.tscn` to display one of the cubemap template images; letters will appear flipped.

Once I figure out these issues, I can look into adding more documentation and templates for cubemap arrays. (I've already started by mentioning that they only work with Forward+/Mobile, not Compatibility, due to OpenGL not supporting cubemap arrays until OpenGL 4.x.)

### CODE REVIEW

**Comment by skyace65** [comment]
How standardized are cubemaps across engines/3D software? If they are standardized it seems odd to add templates.

**Comment by Calinou** [comment]
> How standardized are cubemaps across engines/3D software? If they are standardized it seems odd to add templates.

They aren't really standardized as far as I can tell. It was common for engines to use 6 separate images back in the day (Quake 2/3 with its `_lf`, `_rt`, `_bk`, `_ft`, `_up` and `_dn` suffixes).

**Review by skyace65 — APPROVED** [review]

**Review by paddy-exe — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
cc @clayjohn :)

**Review by clayjohn — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged. Thanks! 🎉

**Pull request merged**
