### PR TITLE
Fix collision layer math formula in Physics introduction

### PR DESCRIPTION
**Pull request by Guang1234567**

### CODE REVIEW

**Comment by Calinou** [comment]
@Guang1234567 Out of curiosity, why did you make this change? Is the previous code incorrect?

**Comment by pycbouh** [comment]
The commented lines above seem to suggest this formula.

**Comment by Guang1234567** [comment]
@Calinou 

Q:
> @Guang1234567 Out of curiosity, why did you make this change? Is the previous code incorrect?

A:
> The commented lines above seem to suggest this formula.
> by @pyacier 

Thanks.

**Comment by pyacier** [comment]
Maybe there is an error, as far as I know I'm not the author of this part, at most I translated it English to French.

**Pull request merged**
