### PR TITLE
[contributing/development/compiling/compiling_for_linuxbsd] update style; use directives

### PR DESCRIPTION
**Pull request by umarcor**
This PR updates the style of compiling guidelines for Linux. A clarification is moved to an admonition and tabs are used to show distro-specific one-liners.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Any specific reason you changed the format of the first list? Does the dashed list break when you add a note?

**Comment by umarcor** [comment]
@YuriSizov it's the recommended syntax for unordered/bulleted lists in Sphinx: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks.

**Comment by YuriSizov** [comment]
Be that as it may, the existing syntax here is also valid. RST has a problem with competing/conflicting syntaxes for a few things, but unless we plan to enforce some specific style across the board (and we don't, as far as I can tell), I would prefer we kept changes in PRs to the minimum and avoid those which are unnecessary. Without a style guide adopted by the project this is just arbitrary, even if otherwise justified.

**Comment by umarcor** [comment]
@YuriSizov now changed to use `-` instead of `*`.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for cleaning this page up, and congrats on your first merged contribution to Godot's docs! 🎉

**Pull request merged**
