### PR TITLE
Update "Static typing in GDScript" page

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes godotengine/godot#82572.
* Partially resolves (no GitHub magic) godotengine/godot#82587.
* Removes references to the "new" feature (3.1 was released a long time ago), as well as unnecessary exclamations inherent in the old style of our documentation.
* Adds a warning about pitfalls of the ``as`` keyword.
* Adds mentions of new features:
  * godotengine/godot#81355.
  * godotengine/godot#82139.
  * godotengine/godot#82477.
  * godotengine/godot#80964

### CODE REVIEW

**Comment by ryanabx** [comment]
Oops, I should have checked the pull requests before making one of my own, haha

**Comment by allenwp** [comment]
> If you prefer static typing, we recommend enabling the Text Editor > Completion > Add Type Hints editor setting. Also consider enabling [some warnings](https://github.com/godotengine/godot-docs/blob/f581734f47c652f0659e0c4b502b2d80d3b1a2ef/tutorials/scripting/gdscript/static_typing.rst#warning-system) that are disabled by default.

I really like this addition! Thanks for this :)

> [:ref:`Clobal classes <doc_gdscript_basics_class_name>`](https://github.com/godotengine/godot-docs/blob/f581734f47c652f0659e0c4b502b2d80d3b1a2ef/tutorials/scripting/gdscript/static_typing.rst#id5).

I think this is supposed to be "**G**lobal classes" (under the "[What can be a type hint](https://github.com/godotengine/godot-docs/blob/f581734f47c652f0659e0c4b502b2d80d3b1a2ef/tutorials/scripting/gdscript/static_typing.rst#what-can-be-a-type-hint)" heading)

**Comment by allenwp** [comment]
As you were working on this pull request, I was also working on a blog post that was intended to be a supplemental document to the Static typing in GDScript page. Your proposed changes in this PR helped me improve my blog post! Thanks!

In case my blog post helps inform this docs update, [here it is](https://allenwp.com/blog/2023/10/03/how-to-enforce-static-typing-in-gdscript/).

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks! Merged. 🎉 Also closed the other PR as superseded.

**Pull request merged**
