### PR TITLE
Removed irrelevant Note

### PR DESCRIPTION
**Pull request by OS-of-S**
Remove forgoted "Note", that is not actual anymore.

image
image

### CODE REVIEW

**Comment by tetrapod00** [comment]
Can you elaborate more on the reasoning for the removal of this note?

**Comment by skyace65** [comment]
In addition to what tetrapod said, the note you have a screenshot of here is not the one that you removed.

**Comment by tetrapod00** [comment]
I think I can follow the logic - since the command line examples were changed in https://github.com/godotengine/godot-docs/pull/9956 to no longer use a `$` (as demonstrated by the screenshotted note and the comments on a docs page), now we no longer need to recommend specifically Git Bash on Windows (which also uses a `$` for the command line prompt).

But the reasoning for this change needs to be clearly stated by the PR author in the description itself, not inferred from a chain of logic.

**Comment by OS-of-S** [comment]
> In addition to what tetrapod said, the note you have a screenshot of here is not the one that you removed.

Oh, yes... It was mistake. I planned to remove only one note. Should I return the other one by myself to fix it?

**Comment by tetrapod00** [comment]
The note in your screenshot was removed in https://github.com/godotengine/godot-docs/pull/10126 already. I'm not sure if you meant this, but please do not add the removed note back to the codebase.

Your PR currently removes another note. Can you please explain why you want to remove it?

**Comment by OS-of-S** [comment]
> The note in your screenshot was removed in #10126 already.

Ah... I see... Probably the documentation had not been updated at that time, and I deleted the wrong note becouse due to my mistake. I beg your pardon, request should be closed.

**Comment by OS-of-S** [comment]
1) A mistake was made
2) The need has disappeared

**Comment by tetrapod00** [comment]
Yeah, mistakes happen, and our docs versioning can be a bit confusing at times. Thanks for contributing nonetheless.

**Pull request closed without merging**
