### PR TITLE
Updated grammar in instancing_continued.rst

### PR DESCRIPTION
**Pull request by natehitchcock**
There was no need for that hyphen

### CODE REVIEW

**Comment by NathanLovato** [comment]
It's not a grammar error. You may also want to check the ongoing discussion on a docs styleguide: https://github.com/godotengine/godot-docs/issues/1084#issuecomment-362859836.

**Comment by natehitchcock** [comment]
Sorry, are you saying that 'design-based' is a [phrasal-adjective](https://practicaltypography.com/hyphens-and-dashes.html) in this case? I would dispute that. In the phrase 'using a design-based on scene instantiation...', 'on' is not a noun, and can't be described with an adjective. Maybe the phrase was supposed to be 'using a design-based scene instantiation'? Or maybe we should just remove this whole fragment, making the final sentence 'Because most game components map directly to a scene, little other architectural code is needed.'

**Comment by NathanLovato** [comment]
My bad, I read too quickly and saw it as a `design-based project`

**Comment by NathanLovato** [comment]
Thanks for the heads up, merging now

**Comment by NathanLovato** [comment]
Ah it's in the 3.0 branch, crap. Right now to fix the docs redirecting you to the wrong version it's forced to go to the 3.0 version, but all fixes should go to the master one, named `latest` on the docs: http://docs.godotengine.org/en/latest/

**Comment by natehitchcock** [comment]
Ah, I was using the 'Edit on GitHub' link in the docs, I'll just make my changes directly from GitHub in the future. Sorry about that.

Additionally, maybe the 'Edit on GitHub' link could point to the master branch? There would be minor discrepancies, but the flow for correcting typos or misinformation would be smoother.

**Comment by NathanLovato** [comment]
> I didn't even realize I was on v3.0.
Don't worry, I didn't either ^^

**Pull request merged**
