### PR TITLE
MSYS2 Note

### PR DESCRIPTION
**Pull request by YRTV**
By magic of copy pasting scoop note, MSYS2 compilation note for docs.
Hope it's correct I am too lazy for learning rst syntax.
See https://github.com/godotengine/godot/issues/26032

### CODE REVIEW

**Comment by YRTV** [comment]
I forgot to copy paste `For each MSYS2 MinGW subsystem in it's own shell pip install scons`

**Comment by YRTV** [comment]
Ok years of using sourcetree with bitbucket free account, dosn't help much with github web ui.
You may want to check formating. I wasn't building docs with sphinx, and used web ui editor for commits .

**Comment by YRTV** [comment]
Also MinGW is heavily and they may come and annoy you if you wiil not change all reference in docs to mingw-w64 
See:
https://stackoverflow.com/questions/31803627/how-do-i-refer-to-the-family-of-mingw-forks
https://www.spi-inc.org/corporate/trademarks/

**Comment by akien-mga** [comment]
Can't you install `scons` directly with pacman instead of using pip? https://packages.msys2.org/base/scons

**Comment by YRTV** [comment]
msys/scons package will run on msys/python which returns `os.name : posix, platform.system() :MSYS_NT-10.0`.

**Comment by YRTV** [comment]
Even on your page `Repo(s): msys ` There is no scons package in MinGW Subsystem repos.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
