### PR TITLE
Fix punctuation in list_of_features.rst

### PR DESCRIPTION
**Pull request by JohnVeness**
Just a tiny punctuation change!

### CODE REVIEW

**Comment by YuriSizov** [comment]
When the change is this specific, it would be nice for the commit message to also be more specific. Though this is true in general, even if you do a pass on the entire page. I.e. the title and the commit message should point at what kind of improvement it is, not just to the fact that it has been improved.

**Comment by JohnVeness** [comment]
> When the change is this specific, it would be nice for the commit message to also be more specific. Though this is true in general, even if you do a pass on the entire page. I.e. the title and the commit message should point at what kind of improvement it is, not just to the fact that it has been improved.

You're right, sorry about that. I admit I find it hard to think of commit titles for general proof-reading type stuff, but I will try harder.

**Comment by YuriSizov** [comment]
You can amend the message and force push to this same PR. Just stating that you improve punctuation in such and such article would be enough.

**Comment by JohnVeness** [comment]
I think I have updated (i.e. force pushed) this correctly. Thanks for the help.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you! Merged. (It still contained a stray merge commit though :))

**Pull request merged**
