### PR TITLE
Release policy: Mark 3.5 stable release

### PR DESCRIPTION
**Pull request by mhilbrunner**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Should we mention 3.6. as in development?

**Comment by Calinou** [comment]
> Should we mention 3.6 as in development?

Yes, as there's a 3.6 release planned.

**Comment by akien-mga** [comment]
I pushed an update to add 3.6 and update the outdated last section.

**Comment by mhilbrunner** [comment]
Cherry-picked to 3.4 and 3.5.

**Pull request merged**
