### PR TITLE
Added part 4 of the FPS tutorial

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
Added part 4 of the FPS tutorial.

This part is dedicated to refactoring `Player.gd` so it has a more modular setup. It also shows how to add joypad support and the ability to change weapons by scrolling the mouse wheel.

This is the first draft, and likely needs editing. I plan on editing soon, but I thought it was better to make the PR for now. I will do a editing pass soon, fix any errors, and squish the commit(s) into one.

By the way, there is a link to a branch in the finished FPS repository that does not exist right now (`part_4`). I will add it soon, I just want to quickly edit before adding it to the repository.

I decided not to link a .zip file this time (so I don't accidentally have giant file issues again 😨), but instead encouraged readers to download a .zip file from the repository. I can add a zip file if you guys want, but I figured it wouldn't be a bad idea to introduce the idea of downloading from a Github repository to the tutorial instead. 

_____

I'm not sure how many parts this series will end up being. I have lots of ideas on stuff to add, but I don't want to bloat the documentation with my FPS tutorial. What do you guys think?

(Unrelated to this PR, but I do plan on making the video tutorial version soon, I just have to get over my stage fright when it comes to recording my voice 😅 )

### CODE REVIEW

**Comment by mhilbrunner** [comment]
I edite the PR title to have [WIP], feel free to remove that once you did your edit pass and feel this is fine for merging :)

I had a first glance, looks good! In my opinion the tutorial section isn't large enough to worry about "bloat" yet. If (hopefully, when) that happens we can talk about trimming stuff down a little or moving things either to a demo/genre-specific-tutorial section or just moving this elsewhere and linking it in the community section.

But I don't think that is necessary, I'd be happy to have this. Let's see if someone else chimes in. :)

Thanks for your work!

**Comment by pwab** [comment]
>  I figured it wouldn't be a bad idea to introduce the idea of downloading from a Github repository to the tutorial instead.

I think this is an interesting idea which could be considered for bigger project sample / demo files. You only should be careful to keep both the repository and the tutorial in sync. It's frustrating walking through a tutorial project and couldn't get it running because in the base repository a bug was fixed which was once used in the tutorial.

> I'm not sure how many parts this series will end up being. I have lots of ideas on stuff to add, but I don't want to bloat the documentation with my FPS tutorial. What do you guys think?

Bloat it. Blow it up, please! 🙃

**Comment by TwistedTwigleg** [comment]
Phew, edited the entire part!

> mhilbrunner:
> I edited the PR title to have [WIP], feel free to remove that once you did your edit pass and feel this is fine for merging :)

Thanks! Now that I've given it a editing pass, I think it's good to go (and likely after it's pulled in I'll find a bunch of mistakes I missed 😉 )

> mhilbrunner:
> I had a first glance, looks good! In my opinion the tutorial section isn't large enough to worry about "bloat" yet. Once that happens we can talk about trimming stuff down a little or moving things either to a demo/genre-specific-tutorial section or just moving this elsewhere and linking it in the community section.
>
> But I don't think that is necessary, I'd be happy to have this. Let's see if someone else chimes in. :)

Cool, in that case I will not worry too much about adding additional parts!
(And thanks! 😄 )

> pwab:
> I think this is an interesting idea which could be considered for bigger project sample / demo files. You only should be careful to keep both the repository and the tutorial in sync. It's frustrating walking through a tutorial project and couldn't get it running because in the base repository a bug was fixed which was once used in the tutorial.

I totally agree! I've had to change a bunch of things in tutorials I've gone through because the tutorial and the repository have been out of sync.

The problem I'm facing is I don't want to keep adding a bunch of zip files where the only change was in a few files. I'll do my best to keep the tutorial and documentation in sync, but it is likely they will eventually fall out of sync.

I have commented out all of the code in the Github repository, which *may* help if they fall out of sync. One advantage of using the Github is the project *should* always work as long as I keep it updated.

That said, I can add some zip files. What do you guys think?

> pwab:
> Bloat it. Blow it up, please! 🙃

😁

**Comment by mhilbrunner** [comment]
Merged. Thanks again!

**Pull request merged**
