### PR TITLE
Update signals.rst

### PR DESCRIPTION
**Pull request by Alex2782**
MacOS Shortcut for "Open 2D Editor" is `Ctrl + Command + 1`

Bildschirmfoto 2023-08-06 um 16 50 01

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by AThousandShips** [comment]
Superseded by: #7792

**Comment by Alex2782** [comment]
@AThousandShips 

4 days ago I adjusted the file via the link in the documentation.
Does it make sense to link directly to "master"?

Bildschirmfoto 2023-08-10 um 16 03 14

**Comment by AThousandShips** [comment]
No, because you're on the 4.1 documentation, it should link to the appropriate one

**Comment by Alex2782** [comment]
ok

**Comment by AThousandShips** [comment]
If you look at `latest` you'll see that it points to the right version, and the instructions are very clear about where to contribute

**Pull request closed without merging**
