### PR TITLE
[DOCS] Remove semi-obsolete slide code

### PR DESCRIPTION
**Pull request by speakk**
Remove semi-obsolete custom move and slide code, and replace it with the modern in-built move_and_slide function.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thanks for pointing this out, looks fine, although maybe we should add a short note explaining:
>const NORMAL_UP = Vector2(0, -1)
What do you think?

**Comment by akien-mga** [comment]
> const NORMAL_UP = Vector2(0, -1)

I wouldn't introduce a constant for that. Just use it directly, but add a comment before `move_and_slide` explaining what the second argument means.

**Comment by speakk** [comment]
Okay, I added a comment instead of a CONST, how about now? Thanks for the suggestions.

**Comment by mhilbrunner** [comment]
Thanks for your contribution!

**Pull request merged**
