### PR TITLE
Links for everything that needs to be installed

### PR DESCRIPTION
**Pull request by StJohn3D**
I really appreciate the android sdk link, and honestly had never heard of Open JDK or Oracle JDK before today. So a quick google search brought me to the link I've put in this proposed change. If it's correct, and the placement is good then please accept this PR.

### CODE REVIEW

**Comment by akien-mga** [comment]
Would be better to put the link under `OpenJDK`, and add a similar link under `Oracle JDK`, to clear the confusion as you mentioned.

**Comment by StJohn3D** [comment]
Do you have those links then? Like I said this is all new to me. I thought I found a link to a page with links to both the Open and the Oracle versions. From that page it sounds like you download either `Open` or `Oracle` depending on your OS. Is that right?

**Comment by StJohn3D** [comment]
So for windows it looks like I have to go here. https://github.com/ojdkbuild/ojdkbuild
Because I'd like to stay as far away from Oracle and Java as I can.

**Comment by mhilbrunner** [comment]
Added links in https://github.com/godotengine/godot-docs/commit/8d879a8a45c5c6c923ed064ebec953bdea8444a1. Thank you!

**Pull request closed without merging**
