### PR TITLE
Recommend adding Godot folder to AV exceptions in Compiling for Windows

### PR DESCRIPTION
**Pull request by Calinou**
Antivirus programs will spend precious CPU time scanning the Godot source folder as files are added to it by the compiler.

### CODE REVIEW

**Comment by Calinou** [comment]
Cherry-picked to the `3.2` branch.

**Comment by LikeLakers2** [comment]
I wouldn't actually recommend this. While it does slowdown the compilation process, that's offset massively by the AV being able to protect the user from infections.

And I know that Godot does not contain malicious code, but I still really wouldn't recommend this.

**Comment by Calinou** [comment]
> I wouldn't actually recommend this. While it does slowdown the compilation process, that's offset massively by the AV being able to protect the user from infections.

The Godot source repository isn't something that arbitrary users can write into without requiring permission from anyone. Also, [antivirus programs are becoming less and less effective by the day](disable-windows-defender.github.io/).

**Comment by LikeLakers2** [comment]
My concern is less about Godot's code (or it's compilation) having some malicious thing, and more about an actual virus or malicious program sitting in the excluded directory, undetected, because the user opted to exclude the folder. That's why I don't think it's worth making the compilation process a tiny bit faster.

**Pull request merged**
