### PR TITLE
Update part_two.rst

### PR DESCRIPTION
**Pull request by starrydigits**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thanks for these small fixes to @TwistedTwigleg's awesome tutorial!

**Comment by mhilbrunner** [comment]
Note for future PRs: Please open PRs against the `master` branch.

I'll merge this one into master manually. Thanks again!

**Comment by TwistedTwigleg** [comment]
Thanks @starrydigits! 👍 

(Thanks @mhilbrunner for the ping, for merging, and for the compliment 🙂)

**Comment by starrydigits** [comment]
Thanks for merging that properly for me. I'm still getting the hang of git.

And thank you @TwistedTwigleg for the tutorial! I've learned some
interesting techniques from it.

**Pull request merged**
