### PR TITLE
a batch of typo fixes

### PR DESCRIPTION
**Pull request by wass3r**
Just went through most the docs and fixed various typos/grammar.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks a lot! Note however that your changes to everything in ``classes/`` will be discarded next time we update the class reference, as it's synced with the Godot source code as described:
- in the README: https://github.com/godotengine/godot-docs/blob/master/README.md#editing-existing-pages
- and each page header: https://raw.githubusercontent.com/wass3r/godot-docs/c116ad34ce7cf784327f6f2818fe20df14fcd212/classes/class_hseparator.rst

Could you redo the same changes on classes.xml here? https://github.com/godotengine/godot/tree/master/doc/base
Thanks in advance!

**Comment by wass3r** [comment]
Sorry for the commit mess. I forgot to pull in upstream changes first.

Thanks for the note and sorry for missing that. I can definitely go through the XML files. Do you prefer if I undo my changes to the classes files?

**Comment by akien-mga** [comment]
It's fine to keep the changes to the XML, they'll be lost but it's probably simpler than having to undo them in the git history :)

Could you try to rebase your branch to remove the extraneous commits? ``git rebase`` should do the trick, then you can force push with ``git push -f`` (check that the log is good with ``git log`` maybe first)

**Comment by wass3r** [comment]
Done. Sorry about that.

**Comment by akien-mga** [comment]
Awesome, thanks a lot!

**Pull request merged**
