### PR TITLE
Using RigidBody Tutorial Fix

### PR DESCRIPTION
**Pull request by GeneralProtectionFault**
The code examples for creating the equivalent of "LookAt" for a RigidBody3D don't appear to work.  Tested the proposed code as a replacement.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should base your branch on `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [PR Workflow - Updating your branch](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch).

**Comment by GeneralProtectionFault** [comment]
Sorry about that, I thought I did, but I was wondering why it registered so many changes, since I only changed 1 file.
For the record, I followed the editing steps here:
https://docs.godotengine.org/en/stable/contributing/documentation/contributing_to_the_documentation.html#editing-pages-online

...which appear to be exactly what is not recommended in the PR workflow LOL.
Anyway, I am not sure if I did everything right, but I rebased on master, shoved those changes to my fork, and already I see a workflow awaiting approval here and now it says no conflicts.

From what I see, the change I made to tutorials/physics/rigid_body.rst are there on my fork, so I guess just let me know if it's kosher.

**Comment by AThousandShips** [comment]
Need to rebase it further, I can help you when I'm back at my computer

The tutorial need a bit of a clarification, you need to be on the "latest" branch down on the left of the docs page, where it says "stable (4.1)" it should say "latest"

**Comment by AThousandShips** [comment]
There, the rebase process is complicated so helped you fix it, someone else will come around to review the changes

**Comment by skyace65** [comment]
This specific example code was already updated last month by PR #8179. It just hasn't been cherry picked to the 4.1 branch. This is why it's important to always work off of the master branch so you can see the latest changes. I'm closing this PR, if you have any issues with the updated code from #8179 feel free to open a PR that modifies that.

**Pull request closed without merging**
