### PR TITLE
Update high_level_multiplayer.rst

### PR DESCRIPTION
**Pull request by FrederickKDP**
Update documentation to reflect the newest multiplayer API changes. In specific, multiplayer methods from get_tree() were moved to get_multiplayer(). It is possible to use get_tree().get_multiplayer(), but I find that would be overly verbose. In addition, not all code updates here were tested. Feedback appreciated.

### CODE REVIEW

**Comment by AThousandShips** [comment]
This is unfortunately already tracked in #7675, also you should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes)

**Comment by FrederickKDP** [comment]
Thank you! I will do! Glad it was already reported.

**Comment by AThousandShips** [comment]
What I mean is that there is already a PR open for this, this is a duplicate

**Comment by FrederickKDP** [comment]
Closed. Sorry for the confusion.

**Pull request closed without merging**
