### PR TITLE
Gwizz YT Channel Added

### PR DESCRIPTION
**Pull request by Brex1477**
Hello! I make high quality Godot 4 Tutorials, I have linked my channel, please consider making it part of the main branch

### CODE REVIEW

**Comment by Brex1477** [comment]
My first ever pull request!

**Review by mhilbrunner — APPROVED** [review]

**Comment by Brex1477** [comment]
What failed? I only changed the one line on the document?

**Comment by mhilbrunner** [comment]
It's a download failure somewhere on an Ubuntu dependency. Will probably clear up in a bit and I will then restart the build, no worries. :)

> Run # Install tools used by `_tools/format.sh`.
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/r/recode/librecode0_3.6-24_amd64.deb  Connection failed 
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Brex1477** [comment]
oh ok great! just making sure I didn't accidentally mess something up haha

**Comment by mhilbrunner** [comment]
No, you didn't :) Congrats on your first merged PR then, and thanks for creating content for the Godot community 🎉

**Pull request merged**
