### PR TITLE
Add the 'sphinx-copybutton' Sphinx extension.

### PR DESCRIPTION
**Pull request by jwmcgettigan**
Adds the [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) extension to provide a better option/experience for copying code blocks.

chrome_2023-03-07_00-48-53

### CODE REVIEW

**Comment by YuriSizov** [comment]
I looked at it recently, but I think there were some issues with it. So leaving this comment to keep a note of that.

**Comment by jwmcgettigan** [comment]
> I looked at it recently, but I think there were some issues with it. So leaving this comment to keep a note of that.
> 
> Also, if we are going to add it, it needs to be styled appropriately.

1. What issues are you aware of?
2. Is there a style guide I can follow in order to style it appropriately?

**Comment by YuriSizov** [comment]
> Is there a style guide I can follow in order to style it appropriately?

No, but it should at least match the color scheme (so use darker colors in the dark mode, and lighter colors in the light mode).

**Comment by jwmcgettigan** [comment]
### Reference: GitHub Copy Button
Dark Theme             |  Light Theme
:-------------------------:|:-------------------------:
chrome_2023-03-09_00-42-26  |  chrome_2023-03-09_00-43-15

---

### Summary of Changes

1. Styled the colors appropriately according to the light/dark theme.

Dark Theme             |  Light Theme
:-------------------------:|:-------------------------:
chrome_2023-03-09_01-23-23  |  chrome_2023-03-09_01-24-18
2. Increased the spacing between the button and the border so that it is centered on single-line code-blocks.
image
3. Disabled the SVG `title` tooltip with `pointer-events: none` since there is already the hover tooltip that you can see in change 1.

### Notes
* I think a thicker border may be appropriate since the code block also has a thick border.
* If you hover over the button without clicking it, you will see a 'Copy' tooltip.

Dark Theme             |  Light Theme
:-------------------------:|:-------------------------:
chrome_2023-03-09_01-27-08  |  chrome_2023-03-09_01-26-44
* I was not confident in using non-neutral colors to tie into the color scheme so I stuck to neutrals.  But now that the framework is in place, it should be easy to update the colors to ones that conform more to the color scheme if that is deemed necessary.

**Comment by jwmcgettigan** [comment]
Made a few more tweaks, particularly in regards to the `.copybtn.success` styling for the dark/light themes.

Dark Theme             |  Light Theme
:-------------------------:|:-------------------------:
chrome_2023-03-09_14-49-13  |  chrome_2023-03-09_14-49-38

The green box-shadow may be a bit much with godot-docs less neutral colors.  What do you think?

**Comment by mhilbrunner** [comment]
Nifty! Looks quite good IMO. Need to check it out lcoally. @YuriSizov might want to take another look too :)

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Finally found some time to test this, seems to work well in both Firefox and Chrome. Good work @jwmcgettigan!

Any specific issues you are aware off @YuriSizov? Otherwise, we might try to merge this and see if anything crops up.

**Comment by mhilbrunner** [comment]
Merged :) Thanks for contributing!

**Pull request merged**
