### PR TITLE
Correcting link to class Reference

### PR DESCRIPTION
**Pull request by scotmcp**
line 2016 references Class, should reference Resource

### CODE REVIEW

**Comment by scotmcp** [comment]
I meant to say, "line 2016 references GDScript, should reference Resource"

**Comment by AThousandShips** [comment]
You should target `master` not `4.2`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#rebasing-onto-another-branch). If wanted I can fix the branch for you.

**Comment by AThousandShips** [comment]
Also this is false, try this:
```gdscript
print(preload("res://some_script.gd"))
```
And you will see it prints `<GDScript#...>`, not `<Resource#...>`

**Comment by AThousandShips** [comment]
Well then that wasn't clear from your description 🙂, the link text should be changed instead as it's more correct to point to the actual type that will be returned

**Comment by scotmcp** [comment]
That's what my patch does...

**Comment by AThousandShips** [comment]
Should probably say "GDScripts" as the previous said "resources", in either case the current wording isn't correct grammar

**Comment by AThousandShips** [comment]
I rebased your branch for you

**Review by skyace65 — APPROVED** [review]

**Comment by skyace65** [comment]
Thanks!

**Pull request merged**
