### PR TITLE
Updated Mono supported export projects

### PR DESCRIPTION
**Pull request by G-Fuchter**
Added Android and HTML to the list

### CODE REVIEW

**Comment by Calinou** [comment]
I think HTML5 support was temporarily pulled due to lack of AOT compilaton support on Godot's side, but I may be mistaken.

**Comment by neikeq** [comment]
WebAssembly support was not disabled. It only uses the interpreter for now which is pretty slow, but it's supported.
BTW, iOS is supported now as well.

**Comment by G-Fuchter** [comment]
I've been reading the releases and I wasn't able to find any reference to the iOS support except for this small paragraph on the 3.2 release blog post:

> To give a few examples, features such as AOT compilation and iOS support for C# projects, ARCore support, or DTLS support, will likely be integrated in future 3.2.x maintenance releases, once they are ready.

The GitHub issue page for the [C# iOS support](https://github.com/godotengine/godot/issues/20268) is still open and has a reference to the 4.0 milestone, so that leads me to believe that the support for iOS will be live in the next release. Having this in mind, should I modify my pull request in order to add iOS as a supported platform?

**Comment by Calinou** [comment]
@G-Fuchter iOS support was [merged very recently](https://github.com/godotengine/godot/pull/36979). It will be available in Godot 3.2.2.

**Comment by Calinou** [comment]
Thanks!

**Pull request merged**
