### PR TITLE
Update gdscript_advanced.rst

### PR DESCRIPTION
**Pull request by libre8bit**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Hey, thanks for your contribution! Can you please open this as a pull request for the `master` branch on this repo? (`godot-docs` - The `3.0` branch is synced manually from master.

**Comment by mhilbrunner** [comment]
Edit: Looks like you should be able to change the branch without having to create a new PR:
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by libre8bit** [comment]
OK, I just opened a new pull request for the master branch. Thanks!

**Comment by mhilbrunner** [comment]
Merged in https://github.com/godotengine/godot-docs/pull/1082

**Pull request closed without merging**
