### PR TITLE
Fix a typo in Compiling with Mono

### PR DESCRIPTION
**Pull request by HarmvandenBrand**
Autorities -> Authorities

### CODE REVIEW

**Comment by pycbouh** [comment]
Hey, thanks for the contribution! You need to use more descriptive commit messages. Something like "Fix a typo in Compiling with Mono" would suffice. Can you please update your PR?

**Comment by HarmvandenBrand** [comment]
Sorry, I thought such a small commit wouldn't necessitate a more descriptive commit message. But I guess it would look rather ugly when only seeing the message, haha.

I think I fixed it? Never did an amend of a commit message in a pull request before so maybe not.

**Review by pycbouh — APPROVED** [review]
Yes, it's all good now. Maybe even a little too descriptive 🙂 

Nice commit history is important and non-descriptive messages often require to check each such commit to see what's going on and if it's the culprit for whatever you're investigating.

**Comment by mhilbrunner** [comment]
All good :) Thank you!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3 and 3.2.

**Pull request merged**
