### PR TITLE
Add info reg. universal binaries to article on exporting for macOS

### PR DESCRIPTION
**Pull request by Daniel-The-Fox**
Hey there, this solves issue https://github.com/godotengine/godot-docs/issues/8745. 😄

* *Bugsquad edit, closes: https://github.com/godotengine/godot-docs/issues/8745*

### CODE REVIEW

**Comment by AThousandShips** [comment]
I think this needs to be specific about the official templates, as it's not true if compiled without that

**Comment by Daniel-The-Fox** [comment]
> I think this needs to be specific about the official templates, as it's not true if compiled without that

Better?

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged. Thanks for contributing! 🎉

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.2.

**Pull request merged**
