### PR TITLE
Update requirements to include JDK

### PR DESCRIPTION
**Pull request by vsrinu26f**

### CODE REVIEW

**Comment by akien-mga** [comment]
Does it work with OpenJDK 8? I wouldn't want to specify the old JDK 6 explicitly if newer versions work too, users tend to take it to the letter and try to install JDK 6 even if it's not available anymore on their recent distro.

**Comment by vsrinu26f** [comment]
Yes it is working with OpenJDK 8

**Comment by akien-mga** [comment]
Well then it would be better to say "OpenJDK 6 or later" :)

**Comment by akien-mga** [comment]
I've cherry-picked your commits, squashed them and improve them in c6b2e38.

**Pull request closed without merging**
