### PR TITLE
remove rant

### PR DESCRIPTION
**Pull request by Grinshpon**
Remove the `Why` section in the "Encrypting save games" page. It's a politically loaded cringey rant that is completely out of place in the documentation for a game engine.

### CODE REVIEW

**Comment by clayjohn** [comment]
Hi! Thank you for your interest in contributing to the Godot documentation. 

Inside the section you deleted was a note that I guess you missed:

> .. This introduction is an Easter egg and is not intended to be taken seriously.	
.. Please don't remove it :)

Periodically people have submitted PRs removing this section of the doc ([here for example](https://github.com/godotengine/godot-docs/pull/2512)), however, the consensus always is that users like having a funny joke buried in the middle of the docs. Its a fun thing to have and it highlights how Godot users and contributors are free to have fun.

While a small minority of users express offense to the section, it truly does no one any harm and it doesn't disparage any groups, so overall, we prefer to leave it in. 

Again, thanks for your interest in helping out! But this particular change has been discussed many times and we prefer to leave it as it is.

**Comment by Grinshpon** [comment]
@clayjohn easter eggs are typically hidden. This is propaganda sitting in plain sight.

**Comment by Calinou** [comment]
> This is propaganda sitting in plain sight.

I'd like to remind that we don't have a requirement to be truly neutral. The Godot documentation isn't Wikipedia and has no [neutral point of view](https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view) rule.

**Comment by Grinshpon** [comment]
> it truly does no one any harm and it doesn't disparage any groups, so overall, we prefer to leave it in.

[b872229](https://github.com/godotengine/godot-docs/commit/b872229427dddb9b749f46af597e85e25cf2955a) Looks like you were wrong. It's good to see that enough people finally realized that calling a portion of your demographic pieces of shit in the docs was a bad idea, although the damage is done and I still don't feel comfortable being part of a community that actively despises me and my lifestyle.

**Pull request closed without merging**
