### PR TITLE
Update and fix some images for key concepts page

### PR DESCRIPTION
**Pull request by skyace65**
I accidentally updated an image on the wrong page in #6366 and didn't update the pages text. This fixes that and updates two more images. I couldn't do them all because I don't have art assets to remake the first few ones, but I figured I should update what I can.

### CODE REVIEW

**Review by Piralein — CHANGES_REQUESTED** [review]
godot-docs\getting_started\introduction\learning_new_features.rst:: WARNING: image file not readable: getting_started/introduction/img/key_concepts_scene_tree.png

learning_new_features.rst line 119

**Comment by skyace65** [comment]
Fixed.

**Review by Calinou — APPROVED** [review]
Thanks!

**Review by Piralein — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks, merged - and thanks for the reviews everyone!

**Pull request merged**
