### PR TITLE
Add a table of contents on the gdscript_basics doc

### PR DESCRIPTION
**Pull request by Jesusemora**
the gdscript_basics page is too long, it takes ages to scroll down to the part you are looking for, i added links to specific parts for easier access.
 for example, if we are looking for the way of doing conditions in gdscript, we would simply click on if/else/elif instead of scrolling for 3 minutes.
 I'm not very familiar with srt, so someone with more experience could improve it.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Hey there! Isn't that already available in the sidebar?

**Comment by Jesusemora** [comment]
> Hey there! Isn't that already available in the sidebar?

not in the website, the links take you to other pages. this is a temporary but practical solution.
Captura desde 2023-09-23 19-20-21

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html#contributing-changes).

If you need more information about the update process please see: [PR Workflow - Updating your branch](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch).

**Comment by mhilbrunner** [comment]
Thanks for contributing! I'm going to close this as per the comment above. Please open a new PR targeting the `master` branch instead. :)

**Pull request closed without merging**
