### PR TITLE
Add a page to the introduction linking to the learn gdscript app

### PR DESCRIPTION
**Pull request by NathanLovato**
As discussed in the development chat, this PR adds a link to our open-source app, learn gdscript from zero.

The link contains a variable we use to show a sponsorless end screen when the user completes the app. That way, when accessing the app from the Godot documentation, users will not see any links promoting our paid course upon completing the app.

The end screen users will see if they do the app from the Godot docs looks like this. I submitted it to the Godot dev chat / #documentation channel for validation already:

image

Right now, it works like this: if the user starts the course from the good of docks, this end screen will appear even if they later click the link on gdquest.com. If they start on our website, they will get the end screen with a link to our paid course.

Please let me know if you need us to change the behavior.

The app teaches GDScript in Godot 3, hence the merge to the stable branch. We plan to make a new version for Godot 4, but we're waiting for the engine to be more stable. We also gradually make improvements, and we'll take the opportunity of porting to Godot 4 to improve the lessons and practices further.

This pr also removes the suggestion to follow the CS50 course or to learn Python with a textbook. We try to teach the mindset to have as a programmer directly as we teach the basics of GDScript.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
> The app teaches GDScript in Godot 3, hence the merge to the stable branch. 

We don't merge PRs in the `stable` branch, the "development" branch for the current stable is `3.6`, and we can then cherry-pick to `3.5` too.

**Comment by NathanLovato** [comment]
@akien-mga Thanks, I just changed the base and dropped all the extra commits so there's only the one relevant to this PR. Is this good for you?

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by NathanLovato** [comment]
Thank you very much for your time!

**Pull request merged**
