### PR TITLE
Update getting started link

### PR DESCRIPTION
**Pull request by Kaspazza**
Previously there was suggested 5 minutes video from GDQuest youtube channel.  They've prepared new video that is about GODOT 4, which is more relevant for godot 4 tutorial.

### CODE REVIEW

**Comment by AThousandShips** [comment]
I'm not sure the GDQuest video should be replaced

**Comment by skyace65** [comment]
I would actually be in favor of removing or replacing that original video. It was made for Godot 3.2 specifically and lists a few cons like the tilemap editor and node based editor (visual shader editor) lacking maturity, which no longer apply (visual shader editor is being updated in 4.3), at the very least they're noticeably improved compared to back then.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I think updating the link makes sense, GDQuest linked to it in the old video's description themselves; like they and Sky say, quite a bit changed in the 3 years since then.

**Review by skyace65 — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Merged. Thanks and congrats on your first merged contribution!

**Pull request merged**
