### PR TITLE
Update particle shader format in Controlling thousands of fish

### PR DESCRIPTION
**Pull request by jmdejong**
The tutorial mentioned using a vertex function in particle shaders, which is not how particle shaders work anymore

### CODE REVIEW

**Comment by jmdejong** [comment]
I'm not sure what's the best way to style function names (start and process) in this tutorial: with or without backticks.

**Comment by Calinou** [comment]
> I'm not sure what's the best way to style function names (start and process) in this tutorial: with or without backticks.

Backticks are good, but make sure to also add parentheses:

```
``start()``
```

**Comment by jmdejong** [comment]
What about functions that take arguments? The `hash` function was already mentioned by the original text.
Should that be written as `hash()`, `hash(...)` , `hash(x)` or `hash(uint x)`?

**Comment by Calinou** [comment]
> What about functions that take arguments? The `hash` function was already mentioned by the original text. Should that be written as `hash()`, `hash(...)` , `hash(x)` or `hash(uint x)`?

I suggest writing it as `hash()`. We don't need to state the arguments every time, just make sure there are parentheses to make it explicit that it's a function.

**Review by clayjohn — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
