### PR TITLE
Updated required package link for Android docs

### LINKED ISSUE #9547: Exporting for Android page has a link that says "Required Packages" but links to recommended packages
**Your Godot version:** 4.2.3

**Issue description:**
> Ensure that the [required packages](https://developer.android.com/studio/intro/update#recommended) are installed as well.

The text states "required packages" but the link is to recommended packages. Should the link text be changed to "Ensure that the recommended packages..." or should the link be changed to https://developer.android.com/studio/intro/update#required

**URL to the documentation page:** https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#download-the-android-sdk

### PR DESCRIPTION
**Pull request by ayanchavand**
Fixes #9547 
Updated the `https://developer.android.com/studio/intro/update#recommended` link to `https://developer.android.com/studio/intro/update#required`

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]

**Review by skyace65 — COMMENTED** [review]
@m4gr3d should the NDK still be listed here? It's not listed on the required packages page

**Comment by mhilbrunner** [comment]
@m4gr3d poke ^

**Comment by mhilbrunner** [comment]
Well, I guess the NDK one is going to be a different issue. Thanks for contributing, merged :)

**Comment by m4gr3d** [comment]
> @m4gr3d should the NDK still be listed here? It's not listed on the required packages page

Apologies for the delayed response - yes the NDK and CMake should still be listed, though we should group them under a separate bullet point, and link to the following page instead for them

https://developer.android.com/studio/projects/install-ndk

**Pull request merged**
