### PR TITLE
Add instructions on compiling Godot with MinGW.

### PR DESCRIPTION
**Pull request by jtank4**
Adds instructions in development/compiling/compiling_for_windows.rst for how to compile Godot with MinGW.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for your contribution :slightly_smiling_face:

Unfortunately, this makes the page (which is already quite long) even longer. I have [a branch in my fork](https://github.com/Calinou/godot-docs/commits/improve-compiling-for-windows) that greatly shortens the page while adding MinGW build instructions, but merging it is held back by https://github.com/godotengine/godot/issues/21418. (It is otherwise ready to be submitted.)

**Comment by jtank4** [comment]
Hey Calinou, I would still ask that my pull request be merged, as I do not wish for a third person to write this tutorial. I will of course not be offended when you merge your changes and replace my tutorial.

**Comment by Xrayez** [comment]
@jtank4 you can be [co-authored](https://help.github.com/articles/creating-a-commit-with-multiple-authors/) with @Calinou without your changes being merged if you prefer so.

**Comment by Calinou** [comment]
The issue I linked seems to have been tested, I'll double-check and send a documentatipn PR soon :smiley:

**Comment by akien-mga** [comment]
Superseded by #2579. Thanks for the contribution nevertheless!

**Pull request closed without merging**
