### PR TITLE
c_sharp_exports.rst: use uint for layers; update casing to C# convention

### PR DESCRIPTION
**Pull request by tetrapod00**
Fix for https://github.com/godotengine/godot-docs/issues/8439.
If accepted, would supersede https://github.com/godotengine/godot-docs/pull/8438.

### CODE REVIEW

**Comment by skyace65** [comment]
Just asking since you made a new PR instead of editing the old one, are you using the github web editor?

**Review by mhilbrunner — APPROVED** [review]

**Comment by tetrapod00** [comment]
Yes, I'm using the web editor. My contributions so far have been minor fixes, and the web editor seems good enough to make those changes.

In this case I left two commits because the casing change was uncontroversial, but the int -> uint change may have required discussion or further work.

**Review by raulsntos — APPROVED** [review]
Makes sense to me. Thank you for contributing to the .NET documentation!

**Comment by mhilbrunner** [comment]
Thanks! Merged.

**Comment by mhilbrunner** [comment]
Cherry-picked to 4.1.

**Pull request merged**
