### PR TITLE
Change NetworkedMultiplayerENet to ENetMultiplayerPeer in high_level_…

### PR DESCRIPTION
**Pull request by FeralBytes**
Change NetworkedMultiplayerENet to ENetMultiplayerPeer in high_level_multiplayer.rst

### CODE REVIEW

**Comment by FeralBytes** [comment]
Looking through this I see there is a lot more to be done. I will revisit this with a future pull request.

**Comment by mhilbrunner** [comment]
Only if you have the time - I have a draft that is mostly finished overhauling this page, so it would be mostly duplicate work :)

**Comment by FeralBytes** [comment]
@mhilbrunner OK, then should I just close this PR in favor of your PR that is more complete. Thank you for fixing the documentation.

**Comment by mhilbrunner** [comment]
Superseded by https://github.com/godotengine/godot-docs/pull/7675. Thanks for contributing!

**Pull request closed without merging**
